<p> <center><img src="https://datascientest.fr/train/assets/logo_datascientest.png" style="height:200px"> </p>

<hr style="border-width:2px;border-color:#75DFC1">
<center><h1> Analyse et prédiction de la variabilité de la production solaire à partir de données ouvertes de la région PACA </h1></center>
<center><h2> Regroupement des variables au niveau régional </h2></center>
<hr style="border-width:2px;border-color:#75DFC1">

# I - Imports et récupération des données précédentes

Nous commencons par importer les librairies nécessaires pour manipuler nos données :

In [1]:
# Gestion des chemins
from pathlib import Path

# Données et calculs
import pandas as pd
import numpy as np

Puis on récupère les données collectées aux étapes précédentes :

In [2]:
# Chemin vers le répertoire de données d'entrée
input_path = Path('../../data/local_data/input/')

# Chemin vers le répertoire de résultats temporaires
temp_path = Path('../../data/local_data/temp/')

# Chemin vers le répertoire de résultats finaux
output_path = Path('../../data/local_data/output/')

# Chemin du dataset des communes sélectionnées 
communes = output_path / 'best_communes_geo_energy.csv'

In [3]:
# Charger les datasets
all_df = {
    'raw_train' : pd.read_csv(temp_path / ('raw_train_5pts.csv'), index_col='datetime_utc', parse_dates=True),
    'raw_valid' : pd.read_csv(temp_path / ('raw_valid_5pts.csv'), index_col='datetime_utc', parse_dates=True),
    'raw_test' : pd.read_csv(temp_path / ('raw_test_5pts.csv'), index_col='datetime_utc', parse_dates=True),
    'train' : pd.read_csv(temp_path / ('train_5pts.csv'), index_col='datetime_utc', parse_dates=True),
    'valid' : pd.read_csv(temp_path / ('valid_5pts.csv'), index_col='datetime_utc', parse_dates=True),
    'test' : pd.read_csv(temp_path / ('test_5pts.csv'), index_col='datetime_utc', parse_dates=True)}

for df in all_df.values():
    display(df.head())

,consommation,solaire,tco_solaire,tch_solaire,cru_azimuth,cru_altitude,sel_azimuth,sel_altitude,svt_azimuth,svt_altitude,...,bra_humidite,eyg_temperature,eyg_vitesse_vent,eyg_nebulosite,eyg_humidite,target,sin_hour,cos_hour,sin_doy,cos_doy
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2019-12-31 23:00:00+00:00,6123.0,0.0,0.0,0.0,335.596867,-67.454606,336.734433,-67.160776,337.561520,-68.097845,...,86.880,2.720,1.220,51.750,100.000,0.0,-0.258819,0.965926,-0.017213,0.999852
2019-12-31 23:30:00+00:00,5907.0,0.0,0.0,0.0,353.817769,-68.883102,354.738150,-68.485180,356.336005,-69.329403,...,84.455,2.760,1.405,54.215,98.790,0.0,-0.130526,0.991445,-0.017213,0.999852
2020-01-01 00:00:00+00:00,5724.0,0.0,0.0,0.0,12.883689,-68.564280,13.430816,-68.099948,15.637215,-68.757908,...,82.030,2.800,1.590,56.680,97.580,0.0,0.000000,1.000000,0.000000,1.000000
2020-01-01 00:30:00+00:00,5749.0,0.0,0.0,0.0,30.261125,-66.570892,30.451783,-66.089459,32.859299,-66.517353,...,79.380,2.675,1.635,33.325,96.065,0.0,0.130526,0.991445,0.000000,1.000000
2020-01-01 01:00:00+00:00,5700.0,0.0,0.0,0.0,44.631373,-63.284229,44.594428,-62.821307,46.883423,-63.030485,...,76.730,2.550,1.680,9.970,94.550,0.0,0.258819,0.965926,0.000000,1.000000

,consommation,solaire,tco_solaire,tch_solaire,cru_azimuth,cru_altitude,sel_azimuth,sel_altitude,svt_azimuth,svt_altitude,...,bra_humidite,eyg_temperature,eyg_vitesse_vent,eyg_nebulosite,eyg_humidite,target,sin_hour,cos_hour,sin_doy,cos_doy
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00+00:00,4815.0,0.0,0.0,0.0,12.879512,-68.564229,13.426722,-68.099906,15.632999,-68.757915,...,95.680,2.710,1.440,99.410,96.430,0.0,0.000000,1.000000,0.0,1.0
2024-01-01 00:30:00+00:00,4853.0,0.0,0.0,0.0,30.257376,-66.571182,30.448105,-66.089748,32.855587,-66.517697,...,94.865,2.620,1.395,99.705,96.195,0.0,0.130526,0.991445,0.0,1.0
2024-01-01 01:00:00+00:00,4834.0,0.0,0.0,0.0,44.628236,-63.284768,44.591334,-62.821838,46.880350,-63.031066,...,94.050,2.530,1.350,100.000,95.960,0.0,0.258819,0.965926,0.0,1.0
2024-01-01 01:30:00+00:00,4964.0,0.0,0.0,0.0,56.102397,-59.130058,55.958833,-58.702637,57.998488,-58.727575,...,93.455,2.535,1.290,99.585,95.500,0.0,0.382683,0.923880,0.0,1.0
2024-01-01 02:00:00+00:00,4791.0,0.0,0.0,0.0,65.344202,-54.429271,65.169535,-54.042984,66.942140,-53.918107,...,92.860,2.540,1.230,99.170,95.040,0.0,0.500000,0.866025,0.0,1.0

,consommation,solaire,tco_solaire,tch_solaire,cru_azimuth,cru_altitude,sel_azimuth,sel_altitude,svt_azimuth,svt_altitude,...,bra_humidite,eyg_temperature,eyg_vitesse_vent,eyg_nebulosite,eyg_humidite,target,sin_hour,cos_hour,sin_doy,cos_doy
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00+00:00,5492.0,0.0,0.0,0.0,12.621973,-68.519484,13.173648,-68.055736,15.368659,-68.716819,...,89.010,3.26,1.000,96.43,93.350,0.0,0.000000,1.000000,0.0,1.0
2025-01-01 00:30:00+00:00,5498.0,0.0,0.0,0.0,30.001046,-66.548921,30.196673,-66.067425,32.597940,-66.499127,...,89.245,3.18,1.000,97.87,93.565,0.0,0.130526,0.991445,0.0,1.0
2025-01-01 01:00:00+00:00,5424.0,0.0,0.0,0.0,44.396127,-63.280642,44.362936,-62.817182,46.650081,-63.030109,...,89.480,3.10,1.000,99.31,93.780,0.0,0.258819,0.965926,0.0,1.0
2025-01-01 01:30:00+00:00,5506.0,0.0,0.0,0.0,55.899419,-59.138851,55.758234,-58.710650,57.798329,-58.738902,...,89.010,3.09,0.995,99.64,93.325,0.0,0.382683,0.923880,0.0,1.0
2025-01-01 02:00:00+00:00,5285.0,0.0,0.0,0.0,65.166910,-54.446690,64.993649,-54.059517,66.767626,-53.937514,...,88.540,3.08,0.990,99.97,92.870,0.0,0.500000,0.866025,0.0,1.0

,consommation,solaire,tco_solaire,tch_solaire,cru_azimuth,cru_altitude,sel_azimuth,sel_altitude,svt_azimuth,svt_altitude,...,tch_lag_1,tch_lag_2,tch_lag_3,target_lag_1,target_lag_2,target_lag_3,tch_mean_2h,tch_mean_4h,tch_std_2h,tch_std_4h
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 03:00:00+00:00,5332.0,0.0,0.0,0.0,79.584354,-44.161912,79.447862,-43.858394,80.769679,-43.509092,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 03:30:00+00:00,5219.0,0.0,0.0,0.0,85.424299,-38.823177,85.326319,-38.559425,86.472049,-38.123002,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 04:00:00+00:00,5157.0,0.0,0.0,0.0,90.773227,-33.441532,90.717934,-33.216659,91.715185,-32.704136,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 04:30:00+00:00,5161.0,0.0,0.0,0.0,95.807765,-28.065765,95.796716,-27.879311,96.668578,-27.299031,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 05:00:00+00:00,5108.0,0.0,0.0,0.0,100.660015,-22.736496,100.693455,-22.588455,101.459404,-21.946957,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,consommation,solaire,tco_solaire,tch_solaire,cru_azimuth,cru_altitude,sel_azimuth,sel_altitude,svt_azimuth,svt_altitude,...,tch_lag_1,tch_lag_2,tch_lag_3,target_lag_1,target_lag_2,target_lag_3,tch_mean_2h,tch_mean_4h,tch_std_2h,tch_std_4h
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-01-01 04:00:00+00:00,4358.0,0.0,0.0,0.0,90.771843,-33.442421,90.716545,-33.217538,91.713821,-32.705034,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 04:30:00+00:00,4359.0,0.0,0.0,0.0,95.806454,-28.066637,95.795398,-27.880173,96.667282,-27.299910,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 05:00:00+00:00,4302.0,0.0,0.0,0.0,100.658750,-22.737341,100.692183,-22.589290,101.458151,-21.947808,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 05:30:00+00:00,4305.0,0.0,0.0,0.0,105.432107,-17.491337,105.509585,-17.382122,106.186495,-16.684796,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 06:00:00+00:00,4313.0,0.0,0.0,0.0,110.211322,-12.364522,110.331968,-12.294953,110.934961,-11.546493,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,consommation,solaire,tco_solaire,tch_solaire,cru_azimuth,cru_altitude,sel_azimuth,sel_altitude,svt_azimuth,svt_altitude,...,tch_lag_1,tch_lag_2,tch_lag_3,target_lag_1,target_lag_2,target_lag_3,tch_mean_2h,tch_mean_4h,tch_std_2h,tch_std_4h
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 04:00:00+00:00,4860.0,0.0,0.0,0.0,90.650757,-33.470475,90.595478,-33.244692,91.594006,-32.733866,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 04:30:00+00:00,4861.0,0.0,0.0,0.0,95.691654,-28.093986,95.680530,-27.906632,96.553472,-27.327866,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 05:00:00+00:00,4807.0,0.0,0.0,0.0,100.548392,-22.763105,100.581707,-22.614171,101.348542,-21.974031,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 05:30:00+00:00,4805.0,0.0,0.0,0.0,105.324719,-17.514720,105.402056,-17.404626,106.079648,-16.708503,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 06:00:00+00:00,4856.0,0.0,0.0,0.0,110.105716,-12.384770,110.226218,-12.314322,110.829714,-11.566934,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# II - Regroupement au niveau régional

Nos jeux de données contiennent un **grand nombre de variables** (90 variables avant ajout de variables mémoires), en particuliers de variables collectées en cinq points différents. Comme on l'a vu, ces cinq points sont des points d'`intérêt régional` au niveau de la **région PACA**.

On se demande cependant si conserver cinq fois toutes ces variables ne va pas réduire les performances de notre future modélisation : c'est pourquoi on crée une version de nos jeux de données d'entrainement, de validation et de test

In [4]:
# On va créé un second dataset avec moins de colonnes
# en utilisant des moyennes pondérées sur les colonnes concernant les 5 points d'intérêts retenus
dico_col = {}
for key, df in all_df.items():
    print(f"\n{key} :")
    # Récupération de la base des noms de colonnes concernés
    col_par_ville = []
    # Comme tous les points d'intérêts ont exactement les même colonnes les concernant
    # On fait une recherche des noms concernant la ville de Bras
    for col in df.columns :
        if col[:3] == "bra":
            col_par_ville.append(col[4:])
    dico_col[key] = col_par_ville
    print(dico_col[key])
    print("Nombre de colonnes concernant chaque point d'intérêt :", len(dico_col[key]))

raw_train :
['azimuth', 'altitude', 'toa', 'clear_sky_ghi', 'clear_sky_bhi', 'clear_sky_dhi', 'clear_sky_bni', 'ghi', 'bhi', 'dhi', 'bni', 'temperature', 'vitesse_vent', 'nebulosite', 'humidite']
Nombre de colonnes concernant chaque point d'intérêt : 15

raw_valid :
['azimuth', 'altitude', 'toa', 'clear_sky_ghi', 'clear_sky_bhi', 'clear_sky_dhi', 'clear_sky_bni', 'ghi', 'bhi', 'dhi', 'bni', 'temperature', 'vitesse_vent', 'nebulosite', 'humidite']
Nombre de colonnes concernant chaque point d'intérêt : 15

raw_test :
['azimuth', 'altitude', 'toa', 'clear_sky_ghi', 'clear_sky_bhi', 'clear_sky_dhi', 'clear_sky_bni', 'ghi', 'bhi', 'dhi', 'bni', 'temperature', 'vitesse_vent', 'nebulosite', 'humidite']
Nombre de colonnes concernant chaque point d'intérêt : 15

train :
['azimuth', 'altitude', 'toa', 'clear_sky_ghi', 'clear_sky_bhi', 'clear_sky_dhi', 'clear_sky_bni', 'ghi', 'bhi', 'dhi', 'bni', 'reliability', 'temperature', 'vitesse_vent', 'nebulosite', 'humidite', 'dghi_dt', 'ghi_lag_1', 'ghi_lag_2', 'dghi_lag_1', 'dghi_lag_2', 'dghi_lag_3', 'ghi_mean_2h', 'ghi_mean_4h', 'ghi_std_2h', 'ghi_std_4h', 'dnebulosite_dt', 'nebulosite_lag_1', 'nebulosite_lag_2', 'dnebulosite_lag_1', 'dnebulosite_lag_2']
Nombre de colonnes concernant chaque point d'intérêt : 31

valid :
['azimuth', 'altitude', 'toa', 'clear_sky_ghi', 'clear_sky_bhi', 'clear_sky_dhi', 'clear_sky_bni', 'ghi', 'bhi', 'dhi', 'bni', 'reliability', 'temperature', 'vitesse_vent', 'nebulosite', 'humidite', 'dghi_dt', 'ghi_lag_1', 'ghi_lag_2', 'dghi_lag_1', 'dghi_lag_2', 'dghi_lag_3', 'ghi_mean_2h', 'ghi_mean_4h', 'ghi_std_2h', 'ghi_std_4h', 'dnebulosite_dt', 'nebulosite_lag_1', 'nebulosite_lag_2', 'dnebulosite_lag_1', 'dnebulosite_lag_2']
Nombre de colonnes concernant chaque point d'intérêt : 31

test :
['azimuth', 'altitude', 'toa', 'clear_sky_ghi', 'clear_sky_bhi', 'clear_sky_dhi', 'clear_sky_bni', 'ghi', 'bhi', 'dhi', 'bni', 'reliability', 'temperature', 'vitesse_vent', 'nebulosite', 'humidite', 'dghi_dt', 'ghi_lag_1', 'ghi_lag_2', 'dghi_lag_1', 'dghi_lag_2', 'dghi_lag_3', 'ghi_mean_2h', 'ghi_mean_4h', 'ghi_std_2h', 'ghi_std_4h', 'dnebulosite_dt', 'nebulosite_lag_1', 'nebulosite_lag_2', 'dnebulosite_lag_1', 'dnebulosite_lag_2']
Nombre de colonnes concernant chaque point d'intérêt : 31

In [5]:
# Récupération des coefficients de pondération
# Chargement du fichier contenant les communes représentatives
# et leur contribution énergétique associée
df_communes = pd.read_csv(communes)

# Affichage des noms de colonnes pour vérification
display(df_communes)

# Passsage du préfixe en minuscule
df_communes['prefix'] = df_communes['prefix'].str.lower() 

# Récupération des coefficients de pondération
coeff_ponderation = []
for poids in df_communes['poids'] :
    coeff_ponderation.append(poids)
print(coeff_ponderation)

for key, df in all_df.items():
    # Calcul de la somme pondérée
    for col in dico_col[key]:
        col_name_region = f"region_{col}"
        df[col_name_region] = 0.0

        # Récupération de tous les noms des colonnes à pondérer
        all_concerns_cols = []
        for ville in df_communes['prefix'] :
            all_concerns_cols.append(f"{ville}_{col}")

        # Calcul
        for poids, ville in zip(coeff_ponderation, all_concerns_cols):
            df[col_name_region] = df[col_name_region] + poids * df[ville]

        # Supression des colonnes devenues inutiles
        df.drop(all_concerns_cols, axis=1, inplace=True)

    print(f"Taille de {key} : {df.shape}")

,cluster_geo,best_commune,code_insee,lat,lon,energie_totale,poids,prefix
0,2,Cruis,4065,44.0845,5.8397,20356525.0,0.22,cru
1,4,Saint-Étienne-le-Laus,5140,44.5075,6.1616,325158.0,0.06,sel
2,0,Saint-Vallier-de-Thiey,6130,43.6994,6.8516,344281.0,0.07,svt
3,1,Bras,83021,43.4723,5.9558,10603661.0,0.29,bra
4,3,Eygalières,13034,43.7638,4.9554,1510927.0,0.36,eyg

[0.22, 0.06, 0.07, 0.29, 0.36]
Taille de raw_train : (70130, 24)
Taille de raw_valid : (17568, 24)
Taille de raw_test : (17520, 24)
Taille de train : (70121, 50)
Taille de valid : (17559, 50)
Taille de test : (17511, 50)

In [6]:
# Sauvegarde des datasets 
for key, df in all_df.items():
    df.to_csv(temp_path / (key + '_region.csv'))

In [8]:
# Vérification
df_raw_train = pd.read_csv(
    temp_path / ('raw_train_region.csv'), 
    index_col='datetime_utc', 
    parse_dates=True)
display(df_train)


df_raw_valid = pd.read_csv(
    temp_path / ('raw_valid_region.csv'), 
    index_col='datetime_utc', 
    parse_dates=True)
display(df_valid)


df_raw_test = pd.read_csv(
    temp_path / ('raw_test_region.csv'), 
    index_col='datetime_utc', 
    parse_dates=True)
display(df_test)


df_train = pd.read_csv(
    temp_path / ('train_region.csv'), 
    index_col='datetime_utc', 
    parse_dates=True)
display(df_train)


df_valid = pd.read_csv(
    temp_path / ('valid_region.csv'), 
    index_col='datetime_utc', 
    parse_dates=True)
display(df_valid)


df_test = pd.read_csv(
    temp_path / ('test_region.csv'), 
    index_col='datetime_utc', 
    parse_dates=True)
display(df_test)

,consommation,solaire,tco_solaire,tch_solaire,target,sin_hour,cos_hour,sin_doy,cos_doy,tch_lag_1,...,region_dghi_lag_3,region_ghi_mean_2h,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_dnebulosite_dt,region_nebulosite_lag_1,region_nebulosite_lag_2,region_dnebulosite_lag_1,region_dnebulosite_lag_2
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 03:00:00+00:00,5332.0,0.0,0.0,0.0,0.0,0.707107,0.707107,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,12.21470,19.95190,7.73720,12.21470,1.25940
2020-01-01 03:30:00+00:00,5219.0,0.0,0.0,0.0,0.0,0.793353,0.608761,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.05210,32.16660,19.95190,12.21470,12.21470
2020-01-01 04:00:00+00:00,5157.0,0.0,0.0,0.0,0.0,0.866025,0.500000,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.05210,32.21870,32.16660,0.05210,12.21470
2020-01-01 04:30:00+00:00,5161.0,0.0,0.0,0.0,0.0,0.923880,0.382683,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.30945,32.27080,32.21870,0.05210,0.05210
2020-01-01 05:00:00+00:00,5108.0,0.0,0.0,0.0,0.0,0.965926,0.258819,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.30945,32.58025,32.27080,0.30945,0.05210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-31 21:00:00+00:00,4752.0,0.0,0.0,0.0,0.0,-0.707107,0.707107,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,10.71000,55.66330,44.95330,10.71000,6.45090
2023-12-31 21:30:00+00:00,4827.0,0.0,0.0,0.0,0.0,-0.608761,0.793353,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,6.50855,66.37330,55.66330,10.71000,10.71000
2023-12-31 22:00:00+00:00,4982.0,0.0,0.0,0.0,0.0,-0.500000,0.866025,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,6.50855,72.88185,66.37330,6.50855,10.71000
2023-12-31 22:30:00+00:00,5232.0,0.0,0.0,0.0,0.0,-0.382683,0.923880,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,2.43890,79.39040,72.88185,6.50855,6.50855
2023-12-31 23:00:00+00:00,5104.0,0.0,0.0,0.0,0.0,-0.258819,0.965926,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,2.43890,81.82930,79.39040,2.43890,6.50855

,consommation,solaire,tco_solaire,tch_solaire,target,sin_hour,cos_hour,sin_doy,cos_doy,tch_lag_1,...,region_dghi_lag_3,region_ghi_mean_2h,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_dnebulosite_dt,region_nebulosite_lag_1,region_nebulosite_lag_2,region_dnebulosite_lag_1,region_dnebulosite_lag_2
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-01-01 04:00:00+00:00,4358.0,0.0,0.00,0.00,0.00,0.866025,5.000000e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.25240,98.98780,98.73540,0.25240,-0.24750
2024-01-01 04:30:00+00:00,4359.0,0.0,0.00,0.00,0.00,0.923880,3.826834e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.07910,99.24020,98.98780,0.25240,0.25240
2024-01-01 05:00:00+00:00,4302.0,0.0,0.00,0.00,0.00,0.965926,2.588190e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.07910,99.31930,99.24020,0.07910,0.25240
2024-01-01 05:30:00+00:00,4305.0,0.0,0.00,0.00,0.00,0.991445,1.305262e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.87595,99.39840,99.31930,0.07910,0.07910
2024-01-01 06:00:00+00:00,4313.0,0.0,0.00,0.00,0.00,1.000000,6.123234e-17,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.87595,98.52245,99.39840,-0.87595,0.07910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 21:00:00+00:00,5495.0,0.0,0.00,0.00,0.00,-0.707107,7.071068e-01,-0.017166,0.999853,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.64325,47.63105,48.27430,-0.64325,4.07085
2024-12-31 21:30:00+00:00,5556.0,0.0,0.00,0.00,0.00,-0.608761,7.933533e-01,-0.017166,0.999853,0.0,...,0.0,0.0,0.0,0.0,0.0,3.65855,46.98780,47.63105,-0.64325,-0.64325
2024-12-31 22:00:00+00:00,5638.0,0.0,0.00,0.00,0.00,-0.500000,8.660254e-01,-0.017166,0.999853,0.0,...,0.0,0.0,0.0,0.0,0.0,3.65855,50.64635,46.98780,3.65855,-0.64325
2024-12-31 22:30:00+00:00,5955.0,0.0,0.00,0.00,0.04,-0.382683,9.238795e-01,-0.017166,0.999853,0.0,...,0.0,0.0,0.0,0.0,0.0,3.32505,54.30490,50.64635,3.65855,3.65855
2024-12-31 23:00:00+00:00,5751.0,1.0,0.02,0.04,-0.04,-0.258819,9.659258e-01,-0.017166,0.999853,0.0,...,0.0,0.0,0.0,0.0,0.0,3.32505,57.62995,54.30490,3.32505,3.65855

,consommation,solaire,tco_solaire,tch_solaire,target,sin_hour,cos_hour,sin_doy,cos_doy,tch_lag_1,...,region_dghi_lag_3,region_ghi_mean_2h,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_dnebulosite_dt,region_nebulosite_lag_1,region_nebulosite_lag_2,region_dnebulosite_lag_1,region_dnebulosite_lag_2
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 04:00:00+00:00,4860.0,0.0,0.0,0.0,0.0,0.866025,5.000000e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-4.82125,63.62825,68.44950,-4.82125,-1.14550
2025-01-01 04:30:00+00:00,4861.0,0.0,0.0,0.0,0.0,0.923880,3.826834e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-2.56890,58.80700,63.62825,-4.82125,-4.82125
2025-01-01 05:00:00+00:00,4807.0,0.0,0.0,0.0,0.0,0.965926,2.588190e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-2.56890,56.23810,58.80700,-2.56890,-4.82125
2025-01-01 05:30:00+00:00,4805.0,0.0,0.0,0.0,0.0,0.991445,1.305262e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-5.90755,53.66920,56.23810,-2.56890,-2.56890
2025-01-01 06:00:00+00:00,4856.0,0.0,0.0,0.0,0.0,1.000000,6.123234e-17,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-5.90755,47.76165,53.66920,-5.90755,-2.56890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-31 21:00:00+00:00,5673.0,0.0,0.0,0.0,0.0,-0.707107,7.071068e-01,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,2.17770,40.10190,37.92420,2.17770,0.74965
2025-12-31 21:30:00+00:00,5722.0,0.0,0.0,0.0,0.0,-0.608761,7.933533e-01,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,0.19855,42.27960,40.10190,2.17770,2.17770
2025-12-31 22:00:00+00:00,5775.0,0.0,0.0,0.0,0.0,-0.500000,8.660254e-01,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,0.19855,42.47815,42.27960,0.19855,2.17770
2025-12-31 22:30:00+00:00,6046.0,0.0,0.0,0.0,0.0,-0.382683,9.238795e-01,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,2.95265,42.67670,42.47815,0.19855,0.19855
2025-12-31 23:00:00+00:00,5905.0,0.0,0.0,0.0,0.0,-0.258819,9.659258e-01,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,2.95265,45.62935,42.67670,2.95265,0.19855

,consommation,solaire,tco_solaire,tch_solaire,target,sin_hour,cos_hour,sin_doy,cos_doy,tch_lag_1,...,region_dghi_lag_3,region_ghi_mean_2h,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_dnebulosite_dt,region_nebulosite_lag_1,region_nebulosite_lag_2,region_dnebulosite_lag_1,region_dnebulosite_lag_2
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 03:00:00+00:00,5332.0,0.0,0.0,0.0,0.0,0.707107,0.707107,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,12.21470,19.95190,7.73720,12.21470,1.25940
2020-01-01 03:30:00+00:00,5219.0,0.0,0.0,0.0,0.0,0.793353,0.608761,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.05210,32.16660,19.95190,12.21470,12.21470
2020-01-01 04:00:00+00:00,5157.0,0.0,0.0,0.0,0.0,0.866025,0.500000,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.05210,32.21870,32.16660,0.05210,12.21470
2020-01-01 04:30:00+00:00,5161.0,0.0,0.0,0.0,0.0,0.923880,0.382683,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.30945,32.27080,32.21870,0.05210,0.05210
2020-01-01 05:00:00+00:00,5108.0,0.0,0.0,0.0,0.0,0.965926,0.258819,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.30945,32.58025,32.27080,0.30945,0.05210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-31 21:00:00+00:00,4752.0,0.0,0.0,0.0,0.0,-0.707107,0.707107,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,10.71000,55.66330,44.95330,10.71000,6.45090
2023-12-31 21:30:00+00:00,4827.0,0.0,0.0,0.0,0.0,-0.608761,0.793353,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,6.50855,66.37330,55.66330,10.71000,10.71000
2023-12-31 22:00:00+00:00,4982.0,0.0,0.0,0.0,0.0,-0.500000,0.866025,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,6.50855,72.88185,66.37330,6.50855,10.71000
2023-12-31 22:30:00+00:00,5232.0,0.0,0.0,0.0,0.0,-0.382683,0.923880,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,2.43890,79.39040,72.88185,6.50855,6.50855
2023-12-31 23:00:00+00:00,5104.0,0.0,0.0,0.0,0.0,-0.258819,0.965926,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,2.43890,81.82930,79.39040,2.43890,6.50855

,consommation,solaire,tco_solaire,tch_solaire,target,sin_hour,cos_hour,sin_doy,cos_doy,tch_lag_1,...,region_dghi_lag_3,region_ghi_mean_2h,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_dnebulosite_dt,region_nebulosite_lag_1,region_nebulosite_lag_2,region_dnebulosite_lag_1,region_dnebulosite_lag_2
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-01-01 04:00:00+00:00,4358.0,0.0,0.00,0.00,0.00,0.866025,5.000000e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.25240,98.98780,98.73540,0.25240,-0.24750
2024-01-01 04:30:00+00:00,4359.0,0.0,0.00,0.00,0.00,0.923880,3.826834e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.07910,99.24020,98.98780,0.25240,0.25240
2024-01-01 05:00:00+00:00,4302.0,0.0,0.00,0.00,0.00,0.965926,2.588190e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.07910,99.31930,99.24020,0.07910,0.25240
2024-01-01 05:30:00+00:00,4305.0,0.0,0.00,0.00,0.00,0.991445,1.305262e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.87595,99.39840,99.31930,0.07910,0.07910
2024-01-01 06:00:00+00:00,4313.0,0.0,0.00,0.00,0.00,1.000000,6.123234e-17,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.87595,98.52245,99.39840,-0.87595,0.07910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 21:00:00+00:00,5495.0,0.0,0.00,0.00,0.00,-0.707107,7.071068e-01,-0.017166,0.999853,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.64325,47.63105,48.27430,-0.64325,4.07085
2024-12-31 21:30:00+00:00,5556.0,0.0,0.00,0.00,0.00,-0.608761,7.933533e-01,-0.017166,0.999853,0.0,...,0.0,0.0,0.0,0.0,0.0,3.65855,46.98780,47.63105,-0.64325,-0.64325
2024-12-31 22:00:00+00:00,5638.0,0.0,0.00,0.00,0.00,-0.500000,8.660254e-01,-0.017166,0.999853,0.0,...,0.0,0.0,0.0,0.0,0.0,3.65855,50.64635,46.98780,3.65855,-0.64325
2024-12-31 22:30:00+00:00,5955.0,0.0,0.00,0.00,0.04,-0.382683,9.238795e-01,-0.017166,0.999853,0.0,...,0.0,0.0,0.0,0.0,0.0,3.32505,54.30490,50.64635,3.65855,3.65855
2024-12-31 23:00:00+00:00,5751.0,1.0,0.02,0.04,-0.04,-0.258819,9.659258e-01,-0.017166,0.999853,0.0,...,0.0,0.0,0.0,0.0,0.0,3.32505,57.62995,54.30490,3.32505,3.65855

,consommation,solaire,tco_solaire,tch_solaire,target,sin_hour,cos_hour,sin_doy,cos_doy,tch_lag_1,...,region_dghi_lag_3,region_ghi_mean_2h,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_dnebulosite_dt,region_nebulosite_lag_1,region_nebulosite_lag_2,region_dnebulosite_lag_1,region_dnebulosite_lag_2
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 04:00:00+00:00,4860.0,0.0,0.0,0.0,0.0,0.866025,5.000000e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-4.82125,63.62825,68.44950,-4.82125,-1.14550
2025-01-01 04:30:00+00:00,4861.0,0.0,0.0,0.0,0.0,0.923880,3.826834e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-2.56890,58.80700,63.62825,-4.82125,-4.82125
2025-01-01 05:00:00+00:00,4807.0,0.0,0.0,0.0,0.0,0.965926,2.588190e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-2.56890,56.23810,58.80700,-2.56890,-4.82125
2025-01-01 05:30:00+00:00,4805.0,0.0,0.0,0.0,0.0,0.991445,1.305262e-01,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-5.90755,53.66920,56.23810,-2.56890,-2.56890
2025-01-01 06:00:00+00:00,4856.0,0.0,0.0,0.0,0.0,1.000000,6.123234e-17,0.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,-5.90755,47.76165,53.66920,-5.90755,-2.56890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-31 21:00:00+00:00,5673.0,0.0,0.0,0.0,0.0,-0.707107,7.071068e-01,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,2.17770,40.10190,37.92420,2.17770,0.74965
2025-12-31 21:30:00+00:00,5722.0,0.0,0.0,0.0,0.0,-0.608761,7.933533e-01,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,0.19855,42.27960,40.10190,2.17770,2.17770
2025-12-31 22:00:00+00:00,5775.0,0.0,0.0,0.0,0.0,-0.500000,8.660254e-01,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,0.19855,42.47815,42.27960,0.19855,2.17770
2025-12-31 22:30:00+00:00,6046.0,0.0,0.0,0.0,0.0,-0.382683,9.238795e-01,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,2.95265,42.67670,42.47815,0.19855,0.19855
2025-12-31 23:00:00+00:00,5905.0,0.0,0.0,0.0,0.0,-0.258819,9.659258e-01,-0.017213,0.999852,0.0,...,0.0,0.0,0.0,0.0,0.0,2.95265,45.62935,42.67670,2.95265,0.19855

In [10]:
print(df_raw_test.columns,'\n')
print(df_test.columns)

Index(['consommation', 'solaire', 'tco_solaire', 'tch_solaire', 'target',
       'sin_hour', 'cos_hour', 'sin_doy', 'cos_doy', 'region_azimuth',
       'region_altitude', 'region_toa', 'region_clear_sky_ghi',
       'region_clear_sky_bhi', 'region_clear_sky_dhi', 'region_clear_sky_bni',
       'region_ghi', 'region_bhi', 'region_dhi', 'region_bni',
       'region_temperature', 'region_vitesse_vent', 'region_nebulosite',
       'region_humidite'],
      dtype='object')

Index(['consommation', 'solaire', 'tco_solaire', 'tch_solaire', 'target',
       'sin_hour', 'cos_hour', 'sin_doy', 'cos_doy', 'tch_lag_1', 'tch_lag_2',
       'tch_lag_3', 'target_lag_1', 'target_lag_2', 'target_lag_3',
       'tch_mean_2h', 'tch_mean_4h', 'tch_std_2h', 'tch_std_4h',
       'region_azimuth', 'region_altitude', 'region_toa',
       'region_clear_sky_ghi', 'region_clear_sky_bhi', 'region_clear_sky_dhi',
       'region_clear_sky_bni', 'region_ghi', 'region_bhi', 'region_dhi',
       'region_bni', 'region_reliability', 'region_temperature',
       'region_vitesse_vent', 'region_nebulosite', 'region_humidite',
       'region_dghi_dt', 'region_ghi_lag_1', 'region_ghi_lag_2',
       'region_dghi_lag_1', 'region_dghi_lag_2', 'region_dghi_lag_3',
       'region_ghi_mean_2h', 'region_ghi_mean_4h', 'region_ghi_std_2h',
       'region_ghi_std_4h', 'region_dnebulosite_dt', 'region_nebulosite_lag_1',
       'region_nebulosite_lag_2', 'region_dnebulosite_lag_1',
       'region_dnebulosite_lag_2'],
      dtype='object')