In [1]:
# Gestion des chemins
from pathlib import Path

# Données et calculs
import pandas as pd
import numpy as np

# Dataviz
import matplotlib.pyplot as plt
%matplotlib inline

# Réduction de dimension
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Séparation des données entrainement / validation
from sklearn.model_selection import train_test_split

In [2]:
# Lecture du fichier de données brutes 2020-2024 et affichage d'informations générales
# Chemin
filepath_2020_2024= Path("../../data/raw_2020_2024.csv")

# Charger le dataset
df_2020_2024 = pd.read_csv(filepath_2020_2024, 
                           index_col='datetime_utc', 
                           parse_dates=True)

# Afficher les premières lignes
display(df_2020_2024.head())

# Afficher les dimensions du dataset
print('Dimensions df_2020_2024 :', df_2020_2024.shape)

# Afficher les statistiques des variables numériques
display(df_2020_2024.describe())

# Afficher le type des colonnes, les valeurs manquantes
df_2020_2024.info()

/tmp/ipykernel_11347/3355731266.py:6: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020_2024 = pd.read_csv(filepath_2020_2024,

,Périmètre,Nature,Consommation,Solaire,Ech. physiques,Stockage batterie,Déstockage batterie,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2019-12-31 23:00:00+00:00,PACA,Données définitives,6123.0,0.0,3332.0,-,-,0.0,0.0,335.596867,...,29.440,57.600,3.230,1.620,5.700,86.880,2.720,1.220,51.750,100.000
2019-12-31 23:30:00+00:00,PACA,Données définitives,5907.0,0.0,2837.0,-,-,0.0,0.0,353.817769,...,24.785,56.165,3.345,1.565,4.635,84.455,2.760,1.405,54.215,98.790
2020-01-01 00:00:00+00:00,PACA,Données définitives,5724.0,0.0,2668.0,-,-,0.0,0.0,12.883689,...,20.130,54.730,3.460,1.510,3.570,82.030,2.800,1.590,56.680,97.580
2020-01-01 00:30:00+00:00,PACA,Données définitives,5749.0,0.0,2754.0,-,-,0.0,0.0,30.261125,...,10.340,54.250,3.650,1.435,3.040,79.380,2.675,1.635,33.325,96.065
2020-01-01 01:00:00+00:00,PACA,Données définitives,5700.0,0.0,2886.0,-,-,0.0,0.0,44.631373,...,0.550,53.770,3.840,1.360,2.510,76.730,2.550,1.680,9.970,94.550

Dimensions df_2020_2024 : (87696, 89)

,Consommation,Solaire,Ech. physiques,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,CRU_altitude,SEL_azimuth,SEL_altitude,SVT_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
count,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,...,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000
mean,4485.721048,301.790241,2362.531826,6.700169,16.873232,180.414164,0.332711,180.600596,0.334114,180.383371,...,52.330814,69.673134,15.387987,2.713704,46.548744,67.673899,14.864098,2.941427,51.525113,68.993747
std,855.835873,438.892803,862.312299,9.822056,23.957124,101.362763,34.060740,101.415049,33.843022,101.319389,...,35.749373,15.507962,8.317463,1.804534,38.648557,21.023569,8.860135,1.993310,37.500944,21.480904
min,1640.000000,0.000000,-615.000000,0.000000,0.000000,0.017255,-69.332104,0.001426,-68.919902,0.005349,...,0.000000,16.700000,-2.950000,0.010000,0.000000,12.460000,-5.060000,0.010000,0.000000,11.140000
25%,3852.000000,0.000000,1793.000000,0.000000,0.000000,90.222951,-25.625496,90.314566,-25.403531,90.048959,...,17.890000,58.488750,8.700000,1.310000,6.973750,51.510000,7.975000,1.300000,12.680000,52.710000
50%,4379.000000,3.000000,2351.000000,0.080000,0.200000,180.009202,0.614024,179.996787,0.677727,180.004222,...,49.475000,70.885000,14.430000,2.220000,38.785000,69.890000,14.100000,2.440000,50.645000,72.660000
75%,5051.000000,559.000000,2895.000000,12.180000,32.320000,270.809415,26.241474,270.866820,25.979124,270.771208,...,91.290000,81.690000,21.260000,3.745000,90.201250,85.330000,21.035000,4.175000,93.141250,87.155000
max,8044.000000,1942.000000,5657.000000,62.320000,91.350000,359.990157,69.288364,359.969741,68.886867,359.995370,...,100.000000,100.000000,39.670000,13.020000,100.000000,100.000000,42.970000,11.240000,100.000000,100.000000

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 87696 entries, 2019-12-31 23:00:00+00:00 to 2024-12-31 22:30:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Périmètre            87696 non-null  object
 1   Nature               87696 non-null  object
 2   Consommation         87696 non-null  float64
 3   Solaire              87696 non-null  float64
 4   Ech. physiques       87696 non-null  float64
 5   Stockage batterie    87696 non-null  object
 6   Déstockage batterie  87696 non-null  object
 7   TCO Solaire (%)      87696 non-null  float64
 8   TCH Solaire (%)      87696 non-null  float64
 9   CRU_azimuth          87696 non-null  float64
 10  CRU_altitude         87696 non-null  float64
 11  SEL_azimuth          87696 non-null  float64
 12  SEL_altitude         87696 non-null  float64
 13  SVT_azimuth          87696 non-null  float64
 14  SVT_altitude         87696 non-null  float64
 15  BRA_azimuth          87696 non-null  float64
 16  BRA_altitude         87696 non-null  float64
 17  EYG_azimuth          87696 non-null  float64
 18  EYG_altitude         87696 non-null  float64
 19  CRU_TOA              87696 non-null  float64
 20  CRU_Clear sky GHI    87696 non-null  float64
 21  CRU_Clear sky BHI    87696 non-null  float64
 22  CRU_Clear sky DHI    87696 non-null  float64
 23  CRU_Clear sky BNI    87696 non-null  float64
 24  CRU_GHI              87696 non-null  float64
 25  CRU_BHI              87696 non-null  float64
 26  CRU_DHI              87696 non-null  float64
 27  CRU_BNI              87696 non-null  float64
 28  CRU_Reliability      87696 non-null  float64
 29  SEL_TOA              87696 non-null  float64
 30  SEL_Clear sky GHI    87696 non-null  float64
 31  SEL_Clear sky BHI    87696 non-null  float64
 32  SEL_Clear sky DHI    87696 non-null  float64
 33  SEL_Clear sky BNI    87696 non-null  float64
 34  SEL_GHI              87696 non-null  float64
 35  SEL_BHI              87696 non-null  float64
 36  SEL_DHI              87696 non-null  float64
 37  SEL_BNI              87696 non-null  float64
 38  SEL_Reliability      87696 non-null  float64
 39  SVT_TOA              87696 non-null  float64
 40  SVT_Clear sky GHI    87696 non-null  float64
 41  SVT_Clear sky BHI    87696 non-null  float64
 42  SVT_Clear sky DHI    87696 non-null  float64
 43  SVT_Clear sky BNI    87696 non-null  float64
 44  SVT_GHI              87696 non-null  float64
 45  SVT_BHI              87696 non-null  float64
 46  SVT_DHI              87696 non-null  float64
 47  SVT_BNI              87696 non-null  float64
 48  SVT_Reliability      87696 non-null  float64
 49  BRA_TOA              87696 non-null  float64
 50  BRA_Clear sky GHI    87696 non-null  float64
 51  BRA_Clear sky BHI    87696 non-null  float64
 52  BRA_Clear sky DHI    87696 non-null  float64
 53  BRA_Clear sky BNI    87696 non-null  float64
 54  BRA_GHI              87696 non-null  float64
 55  BRA_BHI              87696 non-null  float64
 56  BRA_DHI              87696 non-null  float64
 57  BRA_BNI              87696 non-null  float64
 58  BRA_Reliability      87696 non-null  float64
 59  EYG_TOA              87696 non-null  float64
 60  EYG_Clear sky GHI    87696 non-null  float64
 61  EYG_Clear sky BHI    87696 non-null  float64
 62  EYG_Clear sky DHI    87696 non-null  float64
 63  EYG_Clear sky BNI    87696 non-null  float64
 64  EYG_GHI              87696 non-null  float64
 65  EYG_BHI              87696 non-null  float64
 66  EYG_DHI              87696 non-null  float64
 67  EYG_BNI              87696 non-null  float64
 68  EYG_Reliability      87696 non-null  float64
 69  CRU_Temperature      87696 non-null  float64
 70  CRU_Vitesse_Vent     87696 non-null  float64
 71  CRU_Nebulosite       87696 non-null  float64
 72  CRU_Humidite         87696 non-null  float64
 73  SEL_Temperature      87696 non-null  float64
 74  SEL_Vitesse_Vent     87696 non-null  float64
 75  SEL_Nebulosite       87696 non-null  float64
 76  SEL_Humidite         87696 non-null  float64
 77  SVT_Temperature      87696 non-null  float64
 78  SVT_Vitesse_Vent     87696 non-null  float64
 79  SVT_Nebulosite       87696 non-null  float64
 80  SVT_Humidite         87696 non-null  float64
 81  BRA_Temperature      87696 non-null  float64
 82  BRA_Vitesse_Vent     87696 non-null  float64
 83  BRA_Nebulosite       87696 non-null  float64
 84  BRA_Humidite         87696 non-null  float64
 85  EYG_Temperature      87696 non-null  float64
 86  EYG_Vitesse_Vent     87696 non-null  float64
 87  EYG_Nebulosite       87696 non-null  float64
 88  EYG_Humidite         87696 non-null  float64
dtypes: float64(85), object(4)
memory usage: 60.2+ MB

In [3]:
# Lecture du fichier de données brutes 2025-2026 et affichage d'informations générales
# Chemin
filepath_2025_2026= Path("../../data/raw_2025_2026.csv")

# Charger le dataset
df_2025_2026 = pd.read_csv(filepath_2025_2026, 
                           index_col='datetime_utc', 
                           parse_dates=True)

# Afficher les premières lignes
display(df_2025_2026.head())

# Afficher les dimensions du dataset
print('Dimensions df_2025_2026 :', df_2025_2026.shape)

# Afficher le type des colonnes, les valeurs manquantes
df_2025_2026.info() # 'TCO Solaire (%)' est de type 'object'

df_pbl = df_2025_2026.loc[df_2025_2026['TCO Solaire (%)'] == 'ND']
print("\nNombre de lignes où 'TCO Solaire (%)' vaut 'ND' :", len(df_pbl))
print(f"Nombre de valeur de 'TCH Solaire (%)' correspondante : {df_pbl['TCH Solaire (%)'].nunique()} {df_pbl['TCH Solaire (%)'].unique()}")

# On remplace 'ND' par 0.0
df_2025_2026.loc[df_2025_2026['TCO Solaire (%)'] == 'ND'] = 0.0

# On converti le type de la colonne
df_2025_2026['TCO Solaire (%)'] = df_2025_2026['TCO Solaire (%)'].astype(float, errors="raise")

# On vérifie
df_2025_2026.info()

/tmp/ipykernel_11347/3320912934.py:6: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025_2026 = pd.read_csv(filepath_2025_2026,

,Périmètre,Nature,Consommation,Solaire,Ech. physiques,Stockage batterie,Déstockage batterie,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-12-31 23:00:00+00:00,PACA,Données temps réel,5583.0,0.0,4293.0,0.0,0.0,0.0,0.0,335.434321,...,52.460,84.21,5.60,0.16,83.520,87.540,3.310,1.010,81.11,93.650
2024-12-31 23:30:00+00:00,PACA,Données temps réel,5430.0,0.0,4290.0,0.0,0.0,0.0,0.0,353.592974,...,49.245,83.45,5.45,0.11,85.310,88.275,3.285,1.005,88.77,93.500
2025-01-01 00:00:00+00:00,PACA,Données temps réel,5277.0,0.0,4321.0,0.0,0.0,0.0,0.0,12.621973,...,46.030,82.69,5.30,0.06,87.100,89.010,3.260,1.000,96.43,93.350
2025-01-01 00:30:00+00:00,PACA,Données temps réel,5314.0,0.0,4380.0,0.0,0.0,0.0,0.0,30.001046,...,45.480,81.73,5.19,0.14,87.325,89.245,3.180,1.000,97.87,93.565
2025-01-01 01:00:00+00:00,PACA,Données temps réel,5262.0,0.0,4452.0,0.0,0.0,0.0,0.0,44.396127,...,44.930,80.77,5.08,0.22,87.550,89.480,3.100,1.000,99.31,93.780

Dimensions df_2025_2026 : (19901, 89)
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 19901 entries, 2024-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Périmètre            19901 non-null  object
 1   Nature               19901 non-null  object
 2   Consommation         19901 non-null  float64
 3   Solaire              19901 non-null  float64
 4   Ech. physiques       19901 non-null  float64
 5   Stockage batterie    19901 non-null  float64
 6   Déstockage batterie  19901 non-null  float64
 7   TCO Solaire (%)      19901 non-null  object
 8   TCH Solaire (%)      19901 non-null  float64
 9   CRU_azimuth          19901 non-null  float64
 10  CRU_altitude         19901 non-null  float64
 11  SEL_azimuth          19901 non-null  float64
 12  SEL_altitude         19901 non-null  float64
 13  SVT_azimuth          19901 non-null  float64
 14  SVT_altitude         19901 non-null  float64
 15  BRA_azimuth          19901 non-null  float64
 16  BRA_altitude         19901 non-null  float64
 17  EYG_azimuth          19901 non-null  float64
 18  EYG_altitude         19901 non-null  float64
 19  CRU_TOA              19901 non-null  float64
 20  CRU_Clear sky GHI    19901 non-null  float64
 21  CRU_Clear sky BHI    19901 non-null  float64
 22  CRU_Clear sky DHI    19901 non-null  float64
 23  CRU_Clear sky BNI    19901 non-null  float64
 24  CRU_GHI              19901 non-null  float64
 25  CRU_BHI              19901 non-null  float64
 26  CRU_DHI              19901 non-null  float64
 27  CRU_BNI              19901 non-null  float64
 28  CRU_Reliability      19901 non-null  float64
 29  SEL_TOA              19901 non-null  float64
 30  SEL_Clear sky GHI    19901 non-null  float64
 31  SEL_Clear sky BHI    19901 non-null  float64
 32  SEL_Clear sky DHI    19901 non-null  float64
 33  SEL_Clear sky BNI    19901 non-null  float64
 34  SEL_GHI              19901 non-null  float64
 35  SEL_BHI              19901 non-null  float64
 36  SEL_DHI              19901 non-null  float64
 37  SEL_BNI              19901 non-null  float64
 38  SEL_Reliability      19901 non-null  float64
 39  SVT_TOA              19901 non-null  float64
 40  SVT_Clear sky GHI    19901 non-null  float64
 41  SVT_Clear sky BHI    19901 non-null  float64
 42  SVT_Clear sky DHI    19901 non-null  float64
 43  SVT_Clear sky BNI    19901 non-null  float64
 44  SVT_GHI              19901 non-null  float64
 45  SVT_BHI              19901 non-null  float64
 46  SVT_DHI              19901 non-null  float64
 47  SVT_BNI              19901 non-null  float64
 48  SVT_Reliability      19901 non-null  float64
 49  BRA_TOA              19901 non-null  float64
 50  BRA_Clear sky GHI    19901 non-null  float64
 51  BRA_Clear sky BHI    19901 non-null  float64
 52  BRA_Clear sky DHI    19901 non-null  float64
 53  BRA_Clear sky BNI    19901 non-null  float64
 54  BRA_GHI              19901 non-null  float64
 55  BRA_BHI              19901 non-null  float64
 56  BRA_DHI              19901 non-null  float64
 57  BRA_BNI              19901 non-null  float64
 58  BRA_Reliability      19901 non-null  float64
 59  EYG_TOA              19901 non-null  float64
 60  EYG_Clear sky GHI    19901 non-null  float64
 61  EYG_Clear sky BHI    19901 non-null  float64
 62  EYG_Clear sky DHI    19901 non-null  float64
 63  EYG_Clear sky BNI    19901 non-null  float64
 64  EYG_GHI              19901 non-null  float64
 65  EYG_BHI              19901 non-null  float64
 66  EYG_DHI              19901 non-null  float64
 67  EYG_BNI              19901 non-null  float64
 68  EYG_Reliability      19901 non-null  float64
 69  CRU_Temperature      19901 non-null  float64
 70  CRU_Vitesse_Vent     19901 non-null  float64
 71  CRU_Nebulosite       19901 non-null  float64
 72  CRU_Humidite         19901 non-null  float64
 73  SEL_Temperature      19901 non-null  float64
 74  SEL_Vitesse_Vent     19901 non-null  float64
 75  SEL_Nebulosite       19901 non-null  float64
 76  SEL_Humidite         19901 non-null  float64
 77  SVT_Temperature      19901 non-null  float64
 78  SVT_Vitesse_Vent     19901 non-null  float64
 79  SVT_Nebulosite       19901 non-null  float64
 80  SVT_Humidite         19901 non-null  float64
 81  BRA_Temperature      19901 non-null  float64
 82  BRA_Vitesse_Vent     19901 non-null  float64
 83  BRA_Nebulosite       19901 non-null  float64
 84  BRA_Humidite         19901 non-null  float64
 85  EYG_Temperature      19901 non-null  float64
 86  EYG_Vitesse_Vent     19901 non-null  float64
 87  EYG_Nebulosite       19901 non-null  float64
 88  EYG_Humidite         19901 non-null  float64
dtypes: float64(86), object(3)
memory usage: 13.7+ MB

Nombre de lignes où 'TCO Solaire (%)' vaut 'ND' : 64
Nombre de valeur de 'TCH Solaire (%)' correspondante : 1 [0.]
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 19901 entries, 2024-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Périmètre            19901 non-null  object
 1   Nature               19901 non-null  object
 2   Consommation         19901 non-null  float64
 3   Solaire              19901 non-null  float64
 4   Ech. physiques       19901 non-null  float64
 5   Stockage batterie    19901 non-null  float64
 6   Déstockage batterie  19901 non-null  float64
 7   TCO Solaire (%)      19901 non-null  float64
 8   TCH Solaire (%)      19901 non-null  float64
 9   CRU_azimuth          19901 non-null  float64
 10  CRU_altitude         19901 non-null  float64
 11  SEL_azimuth          19901 non-null  float64
 12  SEL_altitude         19901 non-null  float64
 13  SVT_azimuth          19901 non-null  float64
 14  SVT_altitude         19901 non-null  float64
 15  BRA_azimuth          19901 non-null  float64
 16  BRA_altitude         19901 non-null  float64
 17  EYG_azimuth          19901 non-null  float64
 18  EYG_altitude         19901 non-null  float64
 19  CRU_TOA              19901 non-null  float64
 20  CRU_Clear sky GHI    19901 non-null  float64
 21  CRU_Clear sky BHI    19901 non-null  float64
 22  CRU_Clear sky DHI    19901 non-null  float64
 23  CRU_Clear sky BNI    19901 non-null  float64
 24  CRU_GHI              19901 non-null  float64
 25  CRU_BHI              19901 non-null  float64
 26  CRU_DHI              19901 non-null  float64
 27  CRU_BNI              19901 non-null  float64
 28  CRU_Reliability      19901 non-null  float64
 29  SEL_TOA              19901 non-null  float64
 30  SEL_Clear sky GHI    19901 non-null  float64
 31  SEL_Clear sky BHI    19901 non-null  float64
 32  SEL_Clear sky DHI    19901 non-null  float64
 33  SEL_Clear sky BNI    19901 non-null  float64
 34  SEL_GHI              19901 non-null  float64
 35  SEL_BHI              19901 non-null  float64
 36  SEL_DHI              19901 non-null  float64
 37  SEL_BNI              19901 non-null  float64
 38  SEL_Reliability      19901 non-null  float64
 39  SVT_TOA              19901 non-null  float64
 40  SVT_Clear sky GHI    19901 non-null  float64
 41  SVT_Clear sky BHI    19901 non-null  float64
 42  SVT_Clear sky DHI    19901 non-null  float64
 43  SVT_Clear sky BNI    19901 non-null  float64
 44  SVT_GHI              19901 non-null  float64
 45  SVT_BHI              19901 non-null  float64
 46  SVT_DHI              19901 non-null  float64
 47  SVT_BNI              19901 non-null  float64
 48  SVT_Reliability      19901 non-null  float64
 49  BRA_TOA              19901 non-null  float64
 50  BRA_Clear sky GHI    19901 non-null  float64
 51  BRA_Clear sky BHI    19901 non-null  float64
 52  BRA_Clear sky DHI    19901 non-null  float64
 53  BRA_Clear sky BNI    19901 non-null  float64
 54  BRA_GHI              19901 non-null  float64
 55  BRA_BHI              19901 non-null  float64
 56  BRA_DHI              19901 non-null  float64
 57  BRA_BNI              19901 non-null  float64
 58  BRA_Reliability      19901 non-null  float64
 59  EYG_TOA              19901 non-null  float64
 60  EYG_Clear sky GHI    19901 non-null  float64
 61  EYG_Clear sky BHI    19901 non-null  float64
 62  EYG_Clear sky DHI    19901 non-null  float64
 63  EYG_Clear sky BNI    19901 non-null  float64
 64  EYG_GHI              19901 non-null  float64
 65  EYG_BHI              19901 non-null  float64
 66  EYG_DHI              19901 non-null  float64
 67  EYG_BNI              19901 non-null  float64
 68  EYG_Reliability      19901 non-null  float64
 69  CRU_Temperature      19901 non-null  float64
 70  CRU_Vitesse_Vent     19901 non-null  float64
 71  CRU_Nebulosite       19901 non-null  float64
 72  CRU_Humidite         19901 non-null  float64
 73  SEL_Temperature      19901 non-null  float64
 74  SEL_Vitesse_Vent     19901 non-null  float64
 75  SEL_Nebulosite       19901 non-null  float64
 76  SEL_Humidite         19901 non-null  float64
 77  SVT_Temperature      19901 non-null  float64
 78  SVT_Vitesse_Vent     19901 non-null  float64
 79  SVT_Nebulosite       19901 non-null  float64
 80  SVT_Humidite         19901 non-null  float64
 81  BRA_Temperature      19901 non-null  float64
 82  BRA_Vitesse_Vent     19901 non-null  float64
 83  BRA_Nebulosite       19901 non-null  float64
 84  BRA_Humidite         19901 non-null  float64
 85  EYG_Temperature      19901 non-null  float64
 86  EYG_Vitesse_Vent     19901 non-null  float64
 87  EYG_Nebulosite       19901 non-null  float64
 88  EYG_Humidite         19901 non-null  float64
dtypes: float64(87), object(2)
memory usage: 13.7+ MB

In [4]:
df = pd.concat([df_2020_2024, df_2025_2026])

# Afficher les premières lignes
display(df.head())

# Afficher les dimensions du dataset
print('Dimensions df :', df.shape, '\n')
print('Taille de df_2020_2024 + taille de df_2025_2026 = taille de df ?', 
      (df_2020_2024.shape[0] + df_2025_2026.shape[0] == df.shape[0]) and
      (df_2020_2024.shape[1] == df.shape[1]) and (df_2025_2026.shape[1] == df.shape[1]))

df.info()

,Périmètre,Nature,Consommation,Solaire,Ech. physiques,Stockage batterie,Déstockage batterie,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2019-12-31 23:00:00+00:00,PACA,Données définitives,6123.0,0.0,3332.0,-,-,0.0,0.0,335.596867,...,29.440,57.600,3.230,1.620,5.700,86.880,2.720,1.220,51.750,100.000
2019-12-31 23:30:00+00:00,PACA,Données définitives,5907.0,0.0,2837.0,-,-,0.0,0.0,353.817769,...,24.785,56.165,3.345,1.565,4.635,84.455,2.760,1.405,54.215,98.790
2020-01-01 00:00:00+00:00,PACA,Données définitives,5724.0,0.0,2668.0,-,-,0.0,0.0,12.883689,...,20.130,54.730,3.460,1.510,3.570,82.030,2.800,1.590,56.680,97.580
2020-01-01 00:30:00+00:00,PACA,Données définitives,5749.0,0.0,2754.0,-,-,0.0,0.0,30.261125,...,10.340,54.250,3.650,1.435,3.040,79.380,2.675,1.635,33.325,96.065
2020-01-01 01:00:00+00:00,PACA,Données définitives,5700.0,0.0,2886.0,-,-,0.0,0.0,44.631373,...,0.550,53.770,3.840,1.360,2.510,76.730,2.550,1.680,9.970,94.550

Dimensions df : (107597, 89)

Taille de df_2020_2024 + taille de df_2025_2026 = taille de df ? True
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 107597 entries, 2019-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Périmètre            107597 non-null  object
 1   Nature               107597 non-null  object
 2   Consommation         107597 non-null  float64
 3   Solaire              107597 non-null  float64
 4   Ech. physiques       107597 non-null  float64
 5   Stockage batterie    107597 non-null  object
 6   Déstockage batterie  107597 non-null  object
 7   TCO Solaire (%)      107597 non-null  float64
 8   TCH Solaire (%)      107597 non-null  float64
 9   CRU_azimuth          107597 non-null  float64
 10  CRU_altitude         107597 non-null  float64
 11  SEL_azimuth          107597 non-null  float64
 12  SEL_altitude         107597 non-null  float64
 13  SVT_azimuth          107597 non-null  float64
 14  SVT_altitude         107597 non-null  float64
 15  BRA_azimuth          107597 non-null  float64
 16  BRA_altitude         107597 non-null  float64
 17  EYG_azimuth          107597 non-null  float64
 18  EYG_altitude         107597 non-null  float64
 19  CRU_TOA              107597 non-null  float64
 20  CRU_Clear sky GHI    107597 non-null  float64
 21  CRU_Clear sky BHI    107597 non-null  float64
 22  CRU_Clear sky DHI    107597 non-null  float64
 23  CRU_Clear sky BNI    107597 non-null  float64
 24  CRU_GHI              107597 non-null  float64
 25  CRU_BHI              107597 non-null  float64
 26  CRU_DHI              107597 non-null  float64
 27  CRU_BNI              107597 non-null  float64
 28  CRU_Reliability      107597 non-null  float64
 29  SEL_TOA              107597 non-null  float64
 30  SEL_Clear sky GHI    107597 non-null  float64
 31  SEL_Clear sky BHI    107597 non-null  float64
 32  SEL_Clear sky DHI    107597 non-null  float64
 33  SEL_Clear sky BNI    107597 non-null  float64
 34  SEL_GHI              107597 non-null  float64
 35  SEL_BHI              107597 non-null  float64
 36  SEL_DHI              107597 non-null  float64
 37  SEL_BNI              107597 non-null  float64
 38  SEL_Reliability      107597 non-null  float64
 39  SVT_TOA              107597 non-null  float64
 40  SVT_Clear sky GHI    107597 non-null  float64
 41  SVT_Clear sky BHI    107597 non-null  float64
 42  SVT_Clear sky DHI    107597 non-null  float64
 43  SVT_Clear sky BNI    107597 non-null  float64
 44  SVT_GHI              107597 non-null  float64
 45  SVT_BHI              107597 non-null  float64
 46  SVT_DHI              107597 non-null  float64
 47  SVT_BNI              107597 non-null  float64
 48  SVT_Reliability      107597 non-null  float64
 49  BRA_TOA              107597 non-null  float64
 50  BRA_Clear sky GHI    107597 non-null  float64
 51  BRA_Clear sky BHI    107597 non-null  float64
 52  BRA_Clear sky DHI    107597 non-null  float64
 53  BRA_Clear sky BNI    107597 non-null  float64
 54  BRA_GHI              107597 non-null  float64
 55  BRA_BHI              107597 non-null  float64
 56  BRA_DHI              107597 non-null  float64
 57  BRA_BNI              107597 non-null  float64
 58  BRA_Reliability      107597 non-null  float64
 59  EYG_TOA              107597 non-null  float64
 60  EYG_Clear sky GHI    107597 non-null  float64
 61  EYG_Clear sky BHI    107597 non-null  float64
 62  EYG_Clear sky DHI    107597 non-null  float64
 63  EYG_Clear sky BNI    107597 non-null  float64
 64  EYG_GHI              107597 non-null  float64
 65  EYG_BHI              107597 non-null  float64
 66  EYG_DHI              107597 non-null  float64
 67  EYG_BNI              107597 non-null  float64
 68  EYG_Reliability      107597 non-null  float64
 69  CRU_Temperature      107597 non-null  float64
 70  CRU_Vitesse_Vent     107597 non-null  float64
 71  CRU_Nebulosite       107597 non-null  float64
 72  CRU_Humidite         107597 non-null  float64
 73  SEL_Temperature      107597 non-null  float64
 74  SEL_Vitesse_Vent     107597 non-null  float64
 75  SEL_Nebulosite       107597 non-null  float64
 76  SEL_Humidite         107597 non-null  float64
 77  SVT_Temperature      107597 non-null  float64
 78  SVT_Vitesse_Vent     107597 non-null  float64
 79  SVT_Nebulosite       107597 non-null  float64
 80  SVT_Humidite         107597 non-null  float64
 81  BRA_Temperature      107597 non-null  float64
 82  BRA_Vitesse_Vent     107597 non-null  float64
 83  BRA_Nebulosite       107597 non-null  float64
 84  BRA_Humidite         107597 non-null  float64
 85  EYG_Temperature      107597 non-null  float64
 86  EYG_Vitesse_Vent     107597 non-null  float64
 87  EYG_Nebulosite       107597 non-null  float64
 88  EYG_Humidite         107597 non-null  float64
dtypes: float64(85), object(4)
memory usage: 73.9+ MB

In [5]:
# Normalisation du nom des colonnes (minuscules, pas d'espace, pas de caractères spéciaux autre que '_')

# Récupération du nom des colunnes
nom_cols = df.columns

# Création d'une fonction pour normaliser le nom des colonnes
def clean_name(name):
    resultat = name.lower()
    resultat = resultat.replace('(', '')
    resultat = resultat.replace(')', '')
    resultat = resultat.replace('%', '')
    resultat = resultat.replace('.', '')
    resultat = resultat.strip()
    resultat = resultat.replace(' ', '_')
    resultat = resultat.replace('é', 'e')
    resultat = resultat.replace('è', 'e')
    return resultat

# Initialisation d'un dictionnaire 
# les clés seront les noms initiaux
# les valeurs les noms normalisés
dico = {}

# Remplir le dictionnaire
for nom in nom_cols:
    dico[nom] = clean_name(nom)
    
# Normaliser le nom des colonnes
df = df.rename(columns=dico)
print(df.info())
df.tail()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 107597 entries, 2019-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   perimetre            107597 non-null  object
 1   nature               107597 non-null  object
 2   consommation         107597 non-null  float64
 3   solaire              107597 non-null  float64
 4   ech_physiques        107597 non-null  float64
 5   stockage_batterie    107597 non-null  object
 6   destockage_batterie  107597 non-null  object
 7   tco_solaire          107597 non-null  float64
 8   tch_solaire          107597 non-null  float64
 9   cru_azimuth          107597 non-null  float64
 10  cru_altitude         107597 non-null  float64
 11  sel_azimuth          107597 non-null  float64
 12  sel_altitude         107597 non-null  float64
 13  svt_azimuth          107597 non-null  float64
 14  svt_altitude         107597 non-null  float64
 15  bra_azimuth          107597 non-null  float64
 16  bra_altitude         107597 non-null  float64
 17  eyg_azimuth          107597 non-null  float64
 18  eyg_altitude         107597 non-null  float64
 19  cru_toa              107597 non-null  float64
 20  cru_clear_sky_ghi    107597 non-null  float64
 21  cru_clear_sky_bhi    107597 non-null  float64
 22  cru_clear_sky_dhi    107597 non-null  float64
 23  cru_clear_sky_bni    107597 non-null  float64
 24  cru_ghi              107597 non-null  float64
 25  cru_bhi              107597 non-null  float64
 26  cru_dhi              107597 non-null  float64
 27  cru_bni              107597 non-null  float64
 28  cru_reliability      107597 non-null  float64
 29  sel_toa              107597 non-null  float64
 30  sel_clear_sky_ghi    107597 non-null  float64
 31  sel_clear_sky_bhi    107597 non-null  float64
 32  sel_clear_sky_dhi    107597 non-null  float64
 33  sel_clear_sky_bni    107597 non-null  float64
 34  sel_ghi              107597 non-null  float64
 35  sel_bhi              107597 non-null  float64
 36  sel_dhi              107597 non-null  float64
 37  sel_bni              107597 non-null  float64
 38  sel_reliability      107597 non-null  float64
 39  svt_toa              107597 non-null  float64
 40  svt_clear_sky_ghi    107597 non-null  float64
 41  svt_clear_sky_bhi    107597 non-null  float64
 42  svt_clear_sky_dhi    107597 non-null  float64
 43  svt_clear_sky_bni    107597 non-null  float64
 44  svt_ghi              107597 non-null  float64
 45  svt_bhi              107597 non-null  float64
 46  svt_dhi              107597 non-null  float64
 47  svt_bni              107597 non-null  float64
 48  svt_reliability      107597 non-null  float64
 49  bra_toa              107597 non-null  float64
 50  bra_clear_sky_ghi    107597 non-null  float64
 51  bra_clear_sky_bhi    107597 non-null  float64
 52  bra_clear_sky_dhi    107597 non-null  float64
 53  bra_clear_sky_bni    107597 non-null  float64
 54  bra_ghi              107597 non-null  float64
 55  bra_bhi              107597 non-null  float64
 56  bra_dhi              107597 non-null  float64
 57  bra_bni              107597 non-null  float64
 58  bra_reliability      107597 non-null  float64
 59  eyg_toa              107597 non-null  float64
 60  eyg_clear_sky_ghi    107597 non-null  float64
 61  eyg_clear_sky_bhi    107597 non-null  float64
 62  eyg_clear_sky_dhi    107597 non-null  float64
 63  eyg_clear_sky_bni    107597 non-null  float64
 64  eyg_ghi              107597 non-null  float64
 65  eyg_bhi              107597 non-null  float64
 66  eyg_dhi              107597 non-null  float64
 67  eyg_bni              107597 non-null  float64
 68  eyg_reliability      107597 non-null  float64
 69  cru_temperature      107597 non-null  float64
 70  cru_vitesse_vent     107597 non-null  float64
 71  cru_nebulosite       107597 non-null  float64
 72  cru_humidite         107597 non-null  float64
 73  sel_temperature      107597 non-null  float64
 74  sel_vitesse_vent     107597 non-null  float64
 75  sel_nebulosite       107597 non-null  float64
 76  sel_humidite         107597 non-null  float64
 77  svt_temperature      107597 non-null  float64
 78  svt_vitesse_vent     107597 non-null  float64
 79  svt_nebulosite       107597 non-null  float64
 80  svt_humidite         107597 non-null  float64
 81  bra_temperature      107597 non-null  float64
 82  bra_vitesse_vent     107597 non-null  float64
 83  bra_nebulosite       107597 non-null  float64
 84  bra_humidite         107597 non-null  float64
 85  eyg_temperature      107597 non-null  float64
 86  eyg_vitesse_vent     107597 non-null  float64
 87  eyg_nebulosite       107597 non-null  float64
 88  eyg_humidite         107597 non-null  float64
dtypes: float64(85), object(4)
memory usage: 73.9+ MB
None

,perimetre,nature,consommation,solaire,ech_physiques,stockage_batterie,destockage_batterie,tco_solaire,tch_solaire,cru_azimuth,...,svt_nebulosite,svt_humidite,bra_temperature,bra_vitesse_vent,bra_nebulosite,bra_humidite,eyg_temperature,eyg_vitesse_vent,eyg_nebulosite,eyg_humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2026-02-19 11:00:00+00:00,PACA,Données temps réel,5181.0,678.0,3030.0,0.0,0.0,13.09,24.08,165.120233,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 11:30:00+00:00,PACA,Données temps réel,5211.0,825.0,2917.0,0.0,0.0,15.83,29.30,173.922880,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 12:00:00+00:00,PACA,Données temps réel,5152.0,842.0,2854.0,0.0,0.0,16.34,29.90,182.864978,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 12:30:00+00:00,PACA,Données temps réel,5177.0,909.0,2833.0,0.0,0.0,17.56,32.28,191.743652,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 13:00:00+00:00,PACA,Données temps réel,5060.0,726.0,2884.0,0.0,0.0,14.35,25.78,200.367731,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4

In [26]:
# Séparation train - valid - test 
date_debut_train = '2019-12-31'
date_fin_train = '2023-12-31'
date_debut_valid = '2024-01-01'
date_fin_valid = '2024-12-31'
date_debut_test = '2025-01-01'
date_fin_test = '2026-12-31'

df_train = df[date_debut_train : date_fin_train] # 2020, 2021, 2022, 2023
df_valid = df[date_debut_valid : date_fin_valid] # 2024
df_test = df[date_debut_test : date_fin_test] # 2025

# Vu les NaN qui seraient introduits par le calcul des lags, 
# on calculera les nouvelles variables sur df 
# (pour le choix des colonnes à supprimer, on se base sur df_train)

print(f"df_train commence le {df_train.index[0]} et s'arrête le {df_train.index[-1]}")
print(f"df_train commence le {df_valid.index[0]} et s'arrête le {df_valid.index[-1]}")
print(f"df_train commence le {df_test.index[0]} et s'arrête le {df_test.index[-1]}")

df_train commence le 2020-01-01 03:00:00+00:00 et s'arrête le 2023-12-31 23:30:00+00:00
df_train commence le 2024-01-01 00:00:00+00:00 et s'arrête le 2024-12-31 23:30:00+00:00
df_train commence le 2025-01-01 00:00:00+00:00 et s'arrête le 2026-02-19 13:00:00+00:00

In [7]:
# Etude des variables de type object
col_object = df_train.select_dtypes(include=['object']).columns

for col in col_object:
    print(f'{col} : {df_train[col].nunique()} valeurs différentes {df_train[col].unique()}')

perimetre : 1 valeurs différentes ['PACA']
nature : 2 valeurs différentes ['Données définitives' 'Données consolidées']
stockage_batterie : 4 valeurs différentes ['-' '0' '0.0' 0.0]
destockage_batterie : 4 valeurs différentes ['-' '0' '0.0' 0.0]

In [8]:
# Les variables de type object ne transportent pas d'information pouvant être utile à notre problématique
df_train = df_train.drop(col_object, axis=1)

# On les supprimera du dataset consolidé
# On crée une liste des variables à supprimer
colonnes_a_supprimer = list(col_object)

In [9]:
# Trouver les variables explicatives qui ont une variance inférieure à 0.01
sel = VarianceThreshold(threshold=0.01)
sel.fit(df_train)

# Afficher les variables concernées
mask = sel.get_support()
print("Variables de faible variance :", df_train.columns[~mask])

Variables de faible variance : Index(['cru_reliability', 'sel_reliability', 'svt_reliability',
       'bra_reliability', 'eyg_reliability'],
      dtype='object')

In [10]:
# On supprime les variables dont la variance est trop faible
colonnes_a_supprimer.extend(list(df_train.columns[~mask]))
print(colonnes_a_supprimer)

['perimetre', 'nature', 'stockage_batterie', 'destockage_batterie', 'cru_reliability', 'sel_reliability', 'svt_reliability', 'bra_reliability', 'eyg_reliability']

In [11]:
# La variable 'ech_physiques' correspond aux flux nets d'électricité échangés avec les zones voisines
# Elle ne concerne pas notre problématique
colonnes_a_supprimer.extend(['ech_physiques'])

In [12]:
# On a fini d'identifier les colonnes à supprimer à partir de df_train
# On applique à df
print(f"Taille de df avant supression des colonnes : {df.shape}")
df = df.drop(colonnes_a_supprimer, axis=1)
print(f"Taille de df après supression des colonnes : {df.shape}")

Taille de df avant supression des colonnes : (107597, 89)
Taille de df après supression des colonnes : (107597, 79)

In [13]:
# Calcul de la variable cible
df['target'] = df['tch_solaire'].diff()
df.head()

,consommation,solaire,tco_solaire,tch_solaire,cru_azimuth,cru_altitude,sel_azimuth,sel_altitude,svt_azimuth,svt_altitude,...,svt_humidite,bra_temperature,bra_vitesse_vent,bra_nebulosite,bra_humidite,eyg_temperature,eyg_vitesse_vent,eyg_nebulosite,eyg_humidite,target
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2019-12-31 23:00:00+00:00,6123.0,0.0,0.0,0.0,335.596867,-67.454606,336.734433,-67.160776,337.561520,-68.097845,...,57.600,3.230,1.620,5.700,86.880,2.720,1.220,51.750,100.000,NaN
2019-12-31 23:30:00+00:00,5907.0,0.0,0.0,0.0,353.817769,-68.883102,354.738150,-68.485180,356.336005,-69.329403,...,56.165,3.345,1.565,4.635,84.455,2.760,1.405,54.215,98.790,0.0
2020-01-01 00:00:00+00:00,5724.0,0.0,0.0,0.0,12.883689,-68.564280,13.430816,-68.099948,15.637215,-68.757908,...,54.730,3.460,1.510,3.570,82.030,2.800,1.590,56.680,97.580,0.0
2020-01-01 00:30:00+00:00,5749.0,0.0,0.0,0.0,30.261125,-66.570892,30.451783,-66.089459,32.859299,-66.517353,...,54.250,3.650,1.435,3.040,79.380,2.675,1.635,33.325,96.065,0.0
2020-01-01 01:00:00+00:00,5700.0,0.0,0.0,0.0,44.631373,-63.284229,44.594428,-62.821307,46.883423,-63.030485,...,53.770,3.840,1.360,2.510,76.730,2.550,1.680,9.970,94.550,0.0

In [14]:
# Encodage cyclique de l'heure (continu, heure + minutes)
#hour = df['hour'] + df['Date'].dt.minute / 60
hour = df.index.hour + df.index.minute / 60
df['sin_hour'] = np.sin(2 * np.pi * hour / 24)
df['cos_hour'] = np.cos(2 * np.pi * hour / 24)

# Encodage cyclique du jour de l'année (avec années bissextiles)
doy = df.index.dayofyear - 1
nb_jour_annee = np.where(df.index.is_leap_year, 366, 365)
df['sin_doy'] = np.sin(2 * np.pi * doy / nb_jour_annee)
df['cos_doy'] = np.cos(2 * np.pi * doy / nb_jour_annee)

display(df[['sin_hour', 'cos_hour', 'sin_doy', 'cos_doy']].head())
print(f"Taille de df : {df.shape}")

                           sin_hour  cos_hour   sin_doy   cos_doy
datetime_utc
2019-12-31 23:00:00+00:00 -0.258819  0.965926 -0.017213  0.999852
2019-12-31 23:30:00+00:00 -0.130526  0.991445 -0.017213  0.999852
2020-01-01 00:00:00+00:00  0.000000  1.000000  0.000000  1.000000
2020-01-01 00:30:00+00:00  0.130526  0.991445  0.000000  1.000000
2020-01-01 01:00:00+00:00  0.258819  0.965926  0.000000  1.000000

Taille de df : (107597, 84)

In [15]:
# Nombre de pas de temps correspondant aux fenêtres
window_2h = 4   # 2 heures = 4 pas de 30 minutes
window_4h = 8   # 4 heures = 8 pas de 30 minutes

In [16]:
# GHI
for ville in ['bra', 'cru', 'eyg', 'sel', 'svt'] :
    # Variation de l'irradiance
    df[ville+"_dghi_dt"] = df[ville+"_ghi"].diff()
    
    # Lags de l'irradiance
    df[ville+"_ghi_lag_1"] = df[ville+"_ghi"].shift(1)
    df[ville+"_ghi_lag_2"] = df[ville+"_ghi"].shift(2)
    
    # Lags de la variation de l'irradiance
    df[ville+"_dghi_lag_1"] = df[ville+"_dghi_dt"].shift(1)
    df[ville+"_dghi_lag_2"] = df[ville+"_dghi_dt"].shift(2)
    df[ville+"_dghi_lag_3"] = df[ville+"_dghi_dt"].shift(3)
    
    # Moyennes glissantes
    df[ville+"_ghi_mean_2h"] = df[ville+"_ghi"].rolling(window=window_2h).mean()
    df[ville+"_ghi_mean_4h"] = df[ville+"_ghi"].rolling(window=window_4h).mean()
    
    # Ecarts-type glissants
    df[ville+"_ghi_std_2h"] = df[ville+"_ghi"].rolling(window=window_2h).std()
    df[ville+"_ghi_std_4h"] = df[ville+"_ghi"].rolling(window=window_4h).std()

print(f"Taille de df : {df.shape}")

Taille de df : (107597, 134)

In [17]:
# Nébulosité
for ville in ['bra', 'cru', 'eyg', 'sel', 'svt'] :
    # Variation de la nébulosité
    df[ville+"_dnebulosite_dt"] = df[ville+"_nebulosite"].diff()
    
    # Lags de la nébulosité
    df[ville+"_nebulosite_lag_1"] = df[ville+"_nebulosite"].shift(1)
    df[ville+"_nebulosite_lag_2"] = df[ville+"_nebulosite"].shift(2)
    
    # Lags de la variation de la nébulosité
    df[ville+"_dnebulosite_lag_1"] = df[ville+"_dnebulosite_dt"].shift(1)
    df[ville+"_dnebulosite_lag_2"] = df[ville+"_dnebulosite_dt"].shift(2)

print(f"Taille de df : {df.shape}")

Taille de df : (107597, 159)

In [18]:
# TCH solaire
# Lags du TCH solaire
df["tch_lag_1"] = df["tch_solaire"].shift(1)
df["tch_lag_2"] = df["tch_solaire"].shift(2)
df["tch_lag_3"] = df["tch_solaire"].shift(3)
    
# Lags de la variation du TCH solaire
df["target_lag_1"] = df["target"].shift(1)
df["target_lag_2"] = df["target"].shift(2)
df["target_lag_3"] = df["target"].shift(3)

# Moyennes glissantes (calculées sur tch_lag_1 pour éviter la fuite de données)
df["tch_mean_2h"] = df["tch_lag_1"].rolling(window=window_2h).mean()
df["tch_mean_4h"] = df["tch_lag_1"].rolling(window=window_4h).mean()
    
# Ecarts-type glissants (calculés sur tch_lag_1 pour éviter la fuite de données)
df["tch_std_2h"] = df["tch_lag_1"].rolling(window=window_2h).std()
df["tch_std_4h"] = df["tch_lag_1"].rolling(window=window_4h).std()

print(f"Taille de df : {df.shape}")

Taille de df : (107597, 169)

In [19]:
df.info() # toutes les colonnes sont de type float64

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 107597 entries, 2019-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Columns: 169 entries, consommation to tch_std_4h
dtypes: float64(169)
memory usage: 143.6 MB

In [20]:
df = df.reindex(columns=df.columns.sort_values())
print(f"Taille de df : {df.shape}")
display(df.head())

Taille de df : (107597, 169)

,bra_altitude,bra_azimuth,bra_bhi,bra_bni,bra_clear_sky_bhi,bra_clear_sky_bni,bra_clear_sky_dhi,bra_clear_sky_ghi,bra_dghi_dt,bra_dghi_lag_1,...,target_lag_3,tch_lag_1,tch_lag_2,tch_lag_3,tch_mean_2h,tch_mean_4h,tch_solaire,tch_std_2h,tch_std_4h,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2019-12-31 23:00:00+00:00,-68.046190,335.241040,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0
2019-12-31 23:30:00+00:00,-69.500739,353.945722,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0
2020-01-01 00:00:00+00:00,-69.141123,13.536657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0
2020-01-01 00:30:00+00:00,-67.054165,31.240402,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0
2020-01-01 01:00:00+00:00,-63.656435,45.699703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0

In [22]:
# Suppression des valeurs nulles introduites
df = df.dropna()
print(f"Taille de df : {df.shape}")

Taille de df : (107589, 169)

In [27]:
# On enregistre 3 datasets pour train / valid / test
df[date_debut_train : date_fin_train].to_csv("../../data/train_5pts.csv")
df[date_debut_valid : date_fin_valid].to_csv("../../data/valid_5pts.csv")
df[date_debut_test : date_fin_test].to_csv("../../data/test_5pts.csv")

In [33]:
# Check
print("Train :")
df_train = pd.read_csv("../../data/train_5pts.csv", index_col='datetime_utc', parse_dates=True)
display(df_train.head())
print("Taille du dataset :", df_train.shape)

print("\nValid :")
df_valid = pd.read_csv("../../data/valid_5pts.csv", index_col='datetime_utc', parse_dates=True)
display(df_valid.head())
print("Taille du dataset :", df_valid.shape)

print("\nTest :")
df_test = pd.read_csv("../../data/test_5pts.csv", index_col='datetime_utc', parse_dates=True)
display(df_test.head())
print("Taille du dataset :", df_test.shape)

Train :

,bra_altitude,bra_azimuth,bra_bhi,bra_bni,bra_clear_sky_bhi,bra_clear_sky_bni,bra_clear_sky_dhi,bra_clear_sky_ghi,bra_dghi_dt,bra_dghi_lag_1,...,target_lag_3,tch_lag_1,tch_lag_2,tch_lag_3,tch_mean_2h,tch_mean_4h,tch_solaire,tch_std_2h,tch_std_4h,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 03:00:00+00:00,-44.186485,80.264541,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 03:30:00+00:00,-38.785359,86.000566,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 04:00:00+00:00,-33.346881,91.256074,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 04:30:00+00:00,-27.918331,96.207025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 05:00:00+00:00,-22.539213,100.984524,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Taille du dataset : (70122, 169)

Valid :

,bra_altitude,bra_azimuth,bra_bhi,bra_bni,bra_clear_sky_bhi,bra_clear_sky_bni,bra_clear_sky_dhi,bra_clear_sky_ghi,bra_dghi_dt,bra_dghi_lag_1,...,target_lag_3,tch_lag_1,tch_lag_2,tch_lag_3,tch_mean_2h,tch_mean_4h,tch_solaire,tch_std_2h,tch_std_4h,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00+00:00,-69.141088,13.532368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 00:30:00+00:00,-67.054481,31.236592,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 01:00:00+00:00,-63.657001,45.696549,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 01:30:00+00:00,-59.396982,57.119939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 02:00:00+00:00,-54.603773,66.256046,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Taille du dataset : (17568, 169)

Test :

,bra_altitude,bra_azimuth,bra_bhi,bra_bni,bra_clear_sky_bhi,bra_clear_sky_bni,bra_clear_sky_dhi,bra_clear_sky_ghi,bra_dghi_dt,bra_dghi_lag_1,...,target_lag_3,tch_lag_1,tch_lag_2,tch_lag_3,tch_mean_2h,tch_mean_4h,tch_solaire,tch_std_2h,tch_std_4h,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00+00:00,-69.097348,13.266719,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.04,0.02,0.030,0.0,0.023094,0.018516,0.0
2025-01-01 00:30:00+00:00,-67.033957,30.974224,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.04,0.0,0.0,0.00,0.01,0.025,0.0,0.020000,0.020702,0.0
2025-01-01 01:00:00+00:00,-63.654884,45.461256,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.00,0.00,0.020,0.0,0.000000,0.021381,0.0
2025-01-01 01:30:00+00:00,-59.407753,56.915724,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.00,0.00,0.015,0.0,0.000000,0.020702,0.0
2025-01-01 02:00:00+00:00,-54.623026,66.078554,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.0,0.0,0.00,0.00,0.010,0.0,0.000000,0.018516,0.0

Taille du dataset : (19899, 169)

In [25]:
# On va créé un second dataset avec moins de colonnes
# en utilisant des moyennes pondérées sur les colonnes concernant les 5 points d'intérêts retenus

# Récupération de la base des noms de colonnes concernés
col_par_ville = []
# Comme tous les points d'intérêts ont exactement les même colonnes les concernant
# On fait une recherche des noms concernant la ville de Bras
for col in df.columns :
    if col[:3] == "bra":
        col_par_ville.append(col[4:])
print(col_par_ville)
print("Nombre de colonnes concernant chaque point d'intérêt :", len(col_par_ville))

['altitude', 'azimuth', 'bhi', 'bni', 'clear_sky_bhi', 'clear_sky_bni', 'clear_sky_dhi', 'clear_sky_ghi', 'dghi_dt', 'dghi_lag_1', 'dghi_lag_2', 'dghi_lag_3', 'dhi', 'dnebulosite_dt', 'dnebulosite_lag_1', 'dnebulosite_lag_2', 'ghi', 'ghi_lag_1', 'ghi_lag_2', 'ghi_mean_2h', 'ghi_mean_4h', 'ghi_std_2h', 'ghi_std_4h', 'humidite', 'nebulosite', 'nebulosite_lag_1', 'nebulosite_lag_2', 'temperature', 'toa', 'vitesse_vent']
Nombre de colonnes concernant chaque point d'intérêt : 30

In [46]:
# Récupération des coefficients de pondération
# Chargement du fichier contenant les communes représentatives
# et leur contribution énergétique associée
df_communes = pd.read_csv("../../data/local_data/01_Clustering/output/best_communes_geo_energy.csv")

# Affichage des noms de colonnes pour vérification
display(df_communes)

# Passsage du préfixe en minuscule
df_communes['prefix'] = df_communes['prefix'].str.lower() 

# Récupération des coefficients de pondération
coeff_ponderation = []
for poids in df_communes['poids'] :
    coeff_ponderation.append(poids)
print(coeff_ponderation)

# Calcul de la somme pondérée
for col in col_par_ville:
    col_name_region = f"region_{col}"
    df[col_name_region] = 0.0
    
    # Récupération de tous les noms des colonnes à pondérer
    all_concerns_cols = []
    for ville in df_communes['prefix'] :
        all_concerns_cols.append(f"{ville}_{col}")
    
    # Calcul
    for poids, ville in zip(coeff_ponderation, all_concerns_cols):
        df[col_name_region] = df[col_name_region] + poids * df[ville]
    
    # Supression des colonnes devenues inutiles
    df = df.drop(all_concerns_cols, axis=1)

print(f"Taille de df : {df.shape}")

,cluster_geo,best_commune,code_insee,lat,lon,energie_totale,poids,prefix
0,2,Cruis,4065,44.0845,5.8397,20356525.0,0.22,CRU
1,4,Saint-Étienne-le-Laus,5140,44.5075,6.1616,325158.0,0.06,SEL
2,0,Saint-Vallier-de-Thiey,6130,43.6994,6.8516,344281.0,0.07,SVT
3,1,Bras,83021,43.4723,5.9558,10603661.0,0.29,BRA
4,3,Eygalières,13034,43.7638,4.9554,1510927.0,0.36,EYG

[0.22, 0.06, 0.07, 0.29, 0.36]
region_altitude : 5
region_azimuth : 5
region_bhi : 5
region_bni : 5
region_clear_sky_bhi : 5
region_clear_sky_bni : 5
region_clear_sky_dhi : 5
region_clear_sky_ghi : 5
region_dghi_dt : 5
region_dghi_lag_1 : 5
region_dghi_lag_2 : 5
region_dghi_lag_3 : 5
region_dhi : 5
region_dnebulosite_dt : 5
region_dnebulosite_lag_1 : 5
region_dnebulosite_lag_2 : 5
region_ghi : 5
region_ghi_lag_1 : 5
region_ghi_lag_2 : 5
region_ghi_mean_2h : 5
region_ghi_mean_4h : 5
region_ghi_std_2h : 5
region_ghi_std_4h : 5
region_humidite : 5
region_nebulosite : 5
region_nebulosite_lag_1 : 5
region_nebulosite_lag_2 : 5
region_temperature : 5
region_toa : 5
region_vitesse_vent : 5
Taille de df : (107589, 49)

In [47]:
# On enregistre 3 datasets pour train / valid / test
df[date_debut_train : date_fin_train].to_csv("../../data/train_region.csv")
df[date_debut_valid : date_fin_valid].to_csv("../../data/valid_region.csv")
df[date_debut_test : date_fin_test].to_csv("../../data/test_region.csv")

In [48]:
# Check
print("Train :")
df_train = pd.read_csv("../../data/train_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_train.head())
print("Taille du dataset :", df_train.shape)

print("\nValid :")
df_valid = pd.read_csv("../../data/valid_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_valid.head())
print("Taille du dataset :", df_valid.shape)

print("\nTest :")
df_test = pd.read_csv("../../data/test_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_test.head())
print("Taille du dataset :", df_test.shape)

Train :

,consommation,cos_doy,cos_hour,sin_doy,sin_hour,solaire,target,target_lag_1,target_lag_2,target_lag_3,...,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_humidite,region_nebulosite,region_nebulosite_lag_1,region_nebulosite_lag_2,region_temperature,region_toa,region_vitesse_vent
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 03:00:00+00:00,5332.0,1.0,0.707107,0.0,0.707107,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,73.3023,32.16660,19.95190,7.7372,3.36130,0.0,0.96980
2020-01-01 03:30:00+00:00,5219.0,1.0,0.608761,0.0,0.793353,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,72.5645,32.21870,32.16660,19.9519,3.26355,0.0,0.97035
2020-01-01 04:00:00+00:00,5157.0,1.0,0.500000,0.0,0.866025,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,71.8267,32.27080,32.21870,32.1666,3.16580,0.0,0.97090
2020-01-01 04:30:00+00:00,5161.0,1.0,0.382683,0.0,0.923880,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,70.5524,32.58025,32.27080,32.2187,3.22595,0.0,0.98650
2020-01-01 05:00:00+00:00,5108.0,1.0,0.258819,0.0,0.965926,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,69.2781,32.88970,32.58025,32.2708,3.28610,0.0,1.00210

Taille du dataset : (70122, 49)

Valid :

,consommation,cos_doy,cos_hour,sin_doy,sin_hour,solaire,target,target_lag_1,target_lag_2,target_lag_3,...,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_humidite,region_nebulosite,region_nebulosite_lag_1,region_nebulosite_lag_2,region_temperature,region_toa,region_vitesse_vent
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00+00:00,4812.0,1.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,96.33220,91.8536,88.0609,84.2682,2.66020,0.0,2.47700
2024-01-01 00:30:00+00:00,4833.0,1.0,0.991445,0.0,0.130526,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,95.95980,94.0952,91.8536,88.0609,2.58245,0.0,2.45855
2024-01-01 01:00:00+00:00,4863.0,1.0,0.965926,0.0,0.258819,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,95.58740,96.3368,94.0952,91.8536,2.50470,0.0,2.44010
2024-01-01 01:30:00+00:00,4903.0,1.0,0.923880,0.0,0.382683,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,95.19045,97.7836,96.3368,94.0952,2.47905,0.0,2.39285
2024-01-01 02:00:00+00:00,4737.0,1.0,0.866025,0.0,0.500000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,94.79350,99.2304,97.7836,96.3368,2.45340,0.0,2.34560

Taille du dataset : (17568, 49)

Test :

,consommation,cos_doy,cos_hour,sin_doy,sin_hour,solaire,target,target_lag_1,target_lag_2,target_lag_3,...,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_humidite,region_nebulosite,region_nebulosite_lag_1,region_nebulosite_lag_2,region_temperature,region_toa,region_vitesse_vent
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00+00:00,5277.0,1.0,1.000000,0.0,0.000000,0.0,0.0,0.0,-0.04,0.00,...,0.0,0.0,0.0,85.42900,68.10510,64.53005,60.95500,3.7956,0.0,0.7248
2025-01-01 00:30:00+00:00,5314.0,1.0,0.991445,0.0,0.130526,0.0,0.0,0.0,0.00,-0.04,...,0.0,0.0,0.0,85.57575,67.91415,68.10510,64.53005,3.7172,0.0,0.7478
2025-01-01 01:00:00+00:00,5262.0,1.0,0.965926,0.0,0.258819,0.0,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,85.72250,67.72320,67.91415,68.10510,3.6388,0.0,0.7708
2025-01-01 01:30:00+00:00,5287.0,1.0,0.923880,0.0,0.382683,0.0,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,85.41155,69.23185,67.72320,67.91415,3.6087,0.0,0.7865
2025-01-01 02:00:00+00:00,5070.0,1.0,0.866025,0.0,0.500000,0.0,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,85.10060,70.74050,69.23185,67.72320,3.5786,0.0,0.8022

Taille du dataset : (19899, 49)