In [1]:
# Chemin output
filepath_output = '/Projet_Moustafa_Datascience/aug25cds_variabilite/data/local_data/04_Features_engineering/output/'

In [2]:
# Gestion des chemins
from pathlib import Path

# Données et calculs
import pandas as pd
import numpy as np

# Dataviz
import matplotlib.pyplot as plt
%matplotlib inline

# Réduction de dimension
from sklearn.feature_selection import VarianceThreshold

In [3]:
# Lecture du fichier de données brutes 2020-2024 et affichage d'informations générales
# Chemin
filepath_2020_2024= Path("/Projet_Moustafa_Datascience/aug25cds_variabilite/data/local_data/02_Collecte_datasets/output/raw_2020_2024.csv")

# Charger le dataset
df_2020_2024 = pd.read_csv(filepath_2020_2024,
                           index_col='datetime_utc',
                           parse_dates=True)

# Afficher les premières lignes
display(df_2020_2024.head())

# Afficher les dimensions du dataset
print('Dimensions df_2020_2024 :', df_2020_2024.shape)

# Afficher les statistiques des variables numériques
display(df_2020_2024.describe())

# Afficher le type des colonnes, les valeurs manquantes
df_2020_2024.info()

C:\Users\mirai\AppData\Local\Temp\ipykernel_468\2490691551.py:6: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020_2024 = pd.read_csv(filepath_2020_2024,

,Périmètre,Nature,Consommation,Solaire,Ech. physiques,Stockage batterie,Déstockage batterie,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2019-12-31 23:00:00+00:00,PACA,Données définitives,6123.0,0.0,3332.0,-,-,0.0,0.0,335.596867,...,29.440,57.600,3.230,1.620,5.700,86.880,2.720,1.220,51.750,100.000
2019-12-31 23:30:00+00:00,PACA,Données définitives,5907.0,0.0,2837.0,-,-,0.0,0.0,353.817769,...,24.785,56.165,3.345,1.565,4.635,84.455,2.760,1.405,54.215,98.790
2020-01-01 00:00:00+00:00,PACA,Données définitives,5724.0,0.0,2668.0,-,-,0.0,0.0,12.883689,...,20.130,54.730,3.460,1.510,3.570,82.030,2.800,1.590,56.680,97.580
2020-01-01 00:30:00+00:00,PACA,Données définitives,5749.0,0.0,2754.0,-,-,0.0,0.0,30.261125,...,10.340,54.250,3.650,1.435,3.040,79.380,2.675,1.635,33.325,96.065
2020-01-01 01:00:00+00:00,PACA,Données définitives,5700.0,0.0,2886.0,-,-,0.0,0.0,44.631373,...,0.550,53.770,3.840,1.360,2.510,76.730,2.550,1.680,9.970,94.550

Dimensions df_2020_2024 : (87696, 89)

,Consommation,Solaire,Ech. physiques,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,CRU_altitude,SEL_azimuth,SEL_altitude,SVT_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
count,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,...,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000
mean,4485.721048,301.790241,2362.531826,6.700169,16.873232,180.414164,0.332711,180.600596,0.334114,180.383371,...,52.330814,69.673134,15.387987,2.713704,46.548744,67.673899,14.864098,2.941427,51.525113,68.993747
std,855.835873,438.892803,862.312299,9.822056,23.957124,101.362763,34.060740,101.415049,33.843022,101.319389,...,35.749373,15.507962,8.317463,1.804534,38.648557,21.023569,8.860135,1.993310,37.500944,21.480904
min,1640.000000,0.000000,-615.000000,0.000000,0.000000,0.017255,-69.332104,0.001426,-68.919902,0.005349,...,0.000000,16.700000,-2.950000,0.010000,0.000000,12.460000,-5.060000,0.010000,0.000000,11.140000
25%,3852.000000,0.000000,1793.000000,0.000000,0.000000,90.222951,-25.625496,90.314566,-25.403531,90.048959,...,17.890000,58.488750,8.700000,1.310000,6.973750,51.510000,7.975000,1.300000,12.680000,52.710000
50%,4379.000000,3.000000,2351.000000,0.080000,0.200000,180.009202,0.614024,179.996787,0.677727,180.004222,...,49.475000,70.885000,14.430000,2.220000,38.785000,69.890000,14.100000,2.440000,50.645000,72.660000
75%,5051.000000,559.000000,2895.000000,12.180000,32.320000,270.809415,26.241474,270.866820,25.979124,270.771208,...,91.290000,81.690000,21.260000,3.745000,90.201250,85.330000,21.035000,4.175000,93.141250,87.155000
max,8044.000000,1942.000000,5657.000000,62.320000,91.350000,359.990157,69.288364,359.969741,68.886867,359.995370,...,100.000000,100.000000,39.670000,13.020000,100.000000,100.000000,42.970000,11.240000,100.000000,100.000000

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 87696 entries, 2019-12-31 23:00:00+00:00 to 2024-12-31 22:30:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Périmètre            87696 non-null  object
 1   Nature               87696 non-null  object
 2   Consommation         87696 non-null  float64
 3   Solaire              87696 non-null  float64
 4   Ech. physiques       87696 non-null  float64
 5   Stockage batterie    87696 non-null  object
 6   Déstockage batterie  87696 non-null  object
 7   TCO Solaire (%)      87696 non-null  float64
 8   TCH Solaire (%)      87696 non-null  float64
 9   CRU_azimuth          87696 non-null  float64
 10  CRU_altitude         87696 non-null  float64
 11  SEL_azimuth          87696 non-null  float64
 12  SEL_altitude         87696 non-null  float64
 13  SVT_azimuth          87696 non-null  float64
 14  SVT_altitude         87696 non-null  float64
 15  BRA_azimuth          87696 non-null  float64
 16  BRA_altitude         87696 non-null  float64
 17  EYG_azimuth          87696 non-null  float64
 18  EYG_altitude         87696 non-null  float64
 19  CRU_TOA              87696 non-null  float64
 20  CRU_Clear sky GHI    87696 non-null  float64
 21  CRU_Clear sky BHI    87696 non-null  float64
 22  CRU_Clear sky DHI    87696 non-null  float64
 23  CRU_Clear sky BNI    87696 non-null  float64
 24  CRU_GHI              87696 non-null  float64
 25  CRU_BHI              87696 non-null  float64
 26  CRU_DHI              87696 non-null  float64
 27  CRU_BNI              87696 non-null  float64
 28  CRU_Reliability      87696 non-null  float64
 29  SEL_TOA              87696 non-null  float64
 30  SEL_Clear sky GHI    87696 non-null  float64
 31  SEL_Clear sky BHI    87696 non-null  float64
 32  SEL_Clear sky DHI    87696 non-null  float64
 33  SEL_Clear sky BNI    87696 non-null  float64
 34  SEL_GHI              87696 non-null  float64
 35  SEL_BHI              87696 non-null  float64
 36  SEL_DHI              87696 non-null  float64
 37  SEL_BNI              87696 non-null  float64
 38  SEL_Reliability      87696 non-null  float64
 39  SVT_TOA              87696 non-null  float64
 40  SVT_Clear sky GHI    87696 non-null  float64
 41  SVT_Clear sky BHI    87696 non-null  float64
 42  SVT_Clear sky DHI    87696 non-null  float64
 43  SVT_Clear sky BNI    87696 non-null  float64
 44  SVT_GHI              87696 non-null  float64
 45  SVT_BHI              87696 non-null  float64
 46  SVT_DHI              87696 non-null  float64
 47  SVT_BNI              87696 non-null  float64
 48  SVT_Reliability      87696 non-null  float64
 49  BRA_TOA              87696 non-null  float64
 50  BRA_Clear sky GHI    87696 non-null  float64
 51  BRA_Clear sky BHI    87696 non-null  float64
 52  BRA_Clear sky DHI    87696 non-null  float64
 53  BRA_Clear sky BNI    87696 non-null  float64
 54  BRA_GHI              87696 non-null  float64
 55  BRA_BHI              87696 non-null  float64
 56  BRA_DHI              87696 non-null  float64
 57  BRA_BNI              87696 non-null  float64
 58  BRA_Reliability      87696 non-null  float64
 59  EYG_TOA              87696 non-null  float64
 60  EYG_Clear sky GHI    87696 non-null  float64
 61  EYG_Clear sky BHI    87696 non-null  float64
 62  EYG_Clear sky DHI    87696 non-null  float64
 63  EYG_Clear sky BNI    87696 non-null  float64
 64  EYG_GHI              87696 non-null  float64
 65  EYG_BHI              87696 non-null  float64
 66  EYG_DHI              87696 non-null  float64
 67  EYG_BNI              87696 non-null  float64
 68  EYG_Reliability      87696 non-null  float64
 69  CRU_Temperature      87696 non-null  float64
 70  CRU_Vitesse_Vent     87696 non-null  float64
 71  CRU_Nebulosite       87696 non-null  float64
 72  CRU_Humidite         87696 non-null  float64
 73  SEL_Temperature      87696 non-null  float64
 74  SEL_Vitesse_Vent     87696 non-null  float64
 75  SEL_Nebulosite       87696 non-null  float64
 76  SEL_Humidite         87696 non-null  float64
 77  SVT_Temperature      87696 non-null  float64
 78  SVT_Vitesse_Vent     87696 non-null  float64
 79  SVT_Nebulosite       87696 non-null  float64
 80  SVT_Humidite         87696 non-null  float64
 81  BRA_Temperature      87696 non-null  float64
 82  BRA_Vitesse_Vent     87696 non-null  float64
 83  BRA_Nebulosite       87696 non-null  float64
 84  BRA_Humidite         87696 non-null  float64
 85  EYG_Temperature      87696 non-null  float64
 86  EYG_Vitesse_Vent     87696 non-null  float64
 87  EYG_Nebulosite       87696 non-null  float64
 88  EYG_Humidite         87696 non-null  float64
dtypes: float64(85), object(4)
memory usage: 60.2+ MB

In [4]:
# Lecture du fichier de données brutes 2025-2026 et affichage d'informations générales
# Chemin
filepath_2025_2026= Path("/Projet_Moustafa_Datascience/aug25cds_variabilite/data/local_data/02_Collecte_datasets/output/raw_2025_2026.csv")

# Charger le dataset
df_2025_2026 = pd.read_csv(filepath_2025_2026,
                           index_col='datetime_utc',
                           parse_dates=True)

# Afficher les premières lignes
display(df_2025_2026.head())

# Afficher les dimensions du dataset
print('Dimensions df_2025_2026 :', df_2025_2026.shape)

# Afficher le type des colonnes, les valeurs manquantes
df_2025_2026.info() # 'TCO Solaire (%)' est de type 'object'

df_pbl = df_2025_2026.loc[df_2025_2026['TCO Solaire (%)'] == 'ND']
print("\nNombre de lignes où 'TCO Solaire (%)' vaut 'ND' :", len(df_pbl))
print(f"Nombre de valeur de 'TCH Solaire (%)' correspondante : {df_pbl['TCH Solaire (%)'].nunique()} {df_pbl['TCH Solaire (%)'].unique()}")

# On remplace 'ND' par 0.0
df_2025_2026.loc[df_2025_2026['TCO Solaire (%)'] == 'ND'] = 0.0

# On converti le type de la colonne
df_2025_2026['TCO Solaire (%)'] = df_2025_2026['TCO Solaire (%)'].astype(float, errors="raise")

# On vérifie
df_2025_2026.info()

C:\Users\mirai\AppData\Local\Temp\ipykernel_468\555355089.py:6: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025_2026 = pd.read_csv(filepath_2025_2026,

,Périmètre,Nature,Consommation,Solaire,Ech. physiques,Stockage batterie,Déstockage batterie,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-12-31 23:00:00+00:00,PACA,Données temps réel,5583.0,0.0,4293.0,0.0,0.0,0.0,0.0,335.434321,...,52.460,84.21,5.60,0.16,83.520,87.540,3.310,1.010,81.11,93.650
2024-12-31 23:30:00+00:00,PACA,Données temps réel,5430.0,0.0,4290.0,0.0,0.0,0.0,0.0,353.592974,...,49.245,83.45,5.45,0.11,85.310,88.275,3.285,1.005,88.77,93.500
2025-01-01 00:00:00+00:00,PACA,Données temps réel,5277.0,0.0,4321.0,0.0,0.0,0.0,0.0,12.621973,...,46.030,82.69,5.30,0.06,87.100,89.010,3.260,1.000,96.43,93.350
2025-01-01 00:30:00+00:00,PACA,Données temps réel,5314.0,0.0,4380.0,0.0,0.0,0.0,0.0,30.001046,...,45.480,81.73,5.19,0.14,87.325,89.245,3.180,1.000,97.87,93.565
2025-01-01 01:00:00+00:00,PACA,Données temps réel,5262.0,0.0,4452.0,0.0,0.0,0.0,0.0,44.396127,...,44.930,80.77,5.08,0.22,87.550,89.480,3.100,1.000,99.31,93.780

Dimensions df_2025_2026 : (19901, 89)
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 19901 entries, 2024-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Périmètre            19901 non-null  object
 1   Nature               19901 non-null  object
 2   Consommation         19901 non-null  float64
 3   Solaire              19901 non-null  float64
 4   Ech. physiques       19901 non-null  float64
 5   Stockage batterie    19901 non-null  float64
 6   Déstockage batterie  19901 non-null  float64
 7   TCO Solaire (%)      19901 non-null  object
 8   TCH Solaire (%)      19901 non-null  float64
 9   CRU_azimuth          19901 non-null  float64
 10  CRU_altitude         19901 non-null  float64
 11  SEL_azimuth          19901 non-null  float64
 12  SEL_altitude         19901 non-null  float64
 13  SVT_azimuth          19901 non-null  float64
 14  SVT_altitude         19901 non-null  float64
 15  BRA_azimuth          19901 non-null  float64
 16  BRA_altitude         19901 non-null  float64
 17  EYG_azimuth          19901 non-null  float64
 18  EYG_altitude         19901 non-null  float64
 19  CRU_TOA              19901 non-null  float64
 20  CRU_Clear sky GHI    19901 non-null  float64
 21  CRU_Clear sky BHI    19901 non-null  float64
 22  CRU_Clear sky DHI    19901 non-null  float64
 23  CRU_Clear sky BNI    19901 non-null  float64
 24  CRU_GHI              19901 non-null  float64
 25  CRU_BHI              19901 non-null  float64
 26  CRU_DHI              19901 non-null  float64
 27  CRU_BNI              19901 non-null  float64
 28  CRU_Reliability      19901 non-null  float64
 29  SEL_TOA              19901 non-null  float64
 30  SEL_Clear sky GHI    19901 non-null  float64
 31  SEL_Clear sky BHI    19901 non-null  float64
 32  SEL_Clear sky DHI    19901 non-null  float64
 33  SEL_Clear sky BNI    19901 non-null  float64
 34  SEL_GHI              19901 non-null  float64
 35  SEL_BHI              19901 non-null  float64
 36  SEL_DHI              19901 non-null  float64
 37  SEL_BNI              19901 non-null  float64
 38  SEL_Reliability      19901 non-null  float64
 39  SVT_TOA              19901 non-null  float64
 40  SVT_Clear sky GHI    19901 non-null  float64
 41  SVT_Clear sky BHI    19901 non-null  float64
 42  SVT_Clear sky DHI    19901 non-null  float64
 43  SVT_Clear sky BNI    19901 non-null  float64
 44  SVT_GHI              19901 non-null  float64
 45  SVT_BHI              19901 non-null  float64
 46  SVT_DHI              19901 non-null  float64
 47  SVT_BNI              19901 non-null  float64
 48  SVT_Reliability      19901 non-null  float64
 49  BRA_TOA              19901 non-null  float64
 50  BRA_Clear sky GHI    19901 non-null  float64
 51  BRA_Clear sky BHI    19901 non-null  float64
 52  BRA_Clear sky DHI    19901 non-null  float64
 53  BRA_Clear sky BNI    19901 non-null  float64
 54  BRA_GHI              19901 non-null  float64
 55  BRA_BHI              19901 non-null  float64
 56  BRA_DHI              19901 non-null  float64
 57  BRA_BNI              19901 non-null  float64
 58  BRA_Reliability      19901 non-null  float64
 59  EYG_TOA              19901 non-null  float64
 60  EYG_Clear sky GHI    19901 non-null  float64
 61  EYG_Clear sky BHI    19901 non-null  float64
 62  EYG_Clear sky DHI    19901 non-null  float64
 63  EYG_Clear sky BNI    19901 non-null  float64
 64  EYG_GHI              19901 non-null  float64
 65  EYG_BHI              19901 non-null  float64
 66  EYG_DHI              19901 non-null  float64
 67  EYG_BNI              19901 non-null  float64
 68  EYG_Reliability      19901 non-null  float64
 69  CRU_Temperature      19901 non-null  float64
 70  CRU_Vitesse_Vent     19901 non-null  float64
 71  CRU_Nebulosite       19901 non-null  float64
 72  CRU_Humidite         19901 non-null  float64
 73  SEL_Temperature      19901 non-null  float64
 74  SEL_Vitesse_Vent     19901 non-null  float64
 75  SEL_Nebulosite       19901 non-null  float64
 76  SEL_Humidite         19901 non-null  float64
 77  SVT_Temperature      19901 non-null  float64
 78  SVT_Vitesse_Vent     19901 non-null  float64
 79  SVT_Nebulosite       19901 non-null  float64
 80  SVT_Humidite         19901 non-null  float64
 81  BRA_Temperature      19901 non-null  float64
 82  BRA_Vitesse_Vent     19901 non-null  float64
 83  BRA_Nebulosite       19901 non-null  float64
 84  BRA_Humidite         19901 non-null  float64
 85  EYG_Temperature      19901 non-null  float64
 86  EYG_Vitesse_Vent     19901 non-null  float64
 87  EYG_Nebulosite       19901 non-null  float64
 88  EYG_Humidite         19901 non-null  float64
dtypes: float64(86), object(3)
memory usage: 13.7+ MB

Nombre de lignes où 'TCO Solaire (%)' vaut 'ND' : 64
Nombre de valeur de 'TCH Solaire (%)' correspondante : 1 [0.]
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 19901 entries, 2024-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Périmètre            19901 non-null  object
 1   Nature               19901 non-null  object
 2   Consommation         19901 non-null  float64
 3   Solaire              19901 non-null  float64
 4   Ech. physiques       19901 non-null  float64
 5   Stockage batterie    19901 non-null  float64
 6   Déstockage batterie  19901 non-null  float64
 7   TCO Solaire (%)      19901 non-null  float64
 8   TCH Solaire (%)      19901 non-null  float64
 9   CRU_azimuth          19901 non-null  float64
 10  CRU_altitude         19901 non-null  float64
 11  SEL_azimuth          19901 non-null  float64
 12  SEL_altitude         19901 non-null  float64
 13  SVT_azimuth          19901 non-null  float64
 14  SVT_altitude         19901 non-null  float64
 15  BRA_azimuth          19901 non-null  float64
 16  BRA_altitude         19901 non-null  float64
 17  EYG_azimuth          19901 non-null  float64
 18  EYG_altitude         19901 non-null  float64
 19  CRU_TOA              19901 non-null  float64
 20  CRU_Clear sky GHI    19901 non-null  float64
 21  CRU_Clear sky BHI    19901 non-null  float64
 22  CRU_Clear sky DHI    19901 non-null  float64
 23  CRU_Clear sky BNI    19901 non-null  float64
 24  CRU_GHI              19901 non-null  float64
 25  CRU_BHI              19901 non-null  float64
 26  CRU_DHI              19901 non-null  float64
 27  CRU_BNI              19901 non-null  float64
 28  CRU_Reliability      19901 non-null  float64
 29  SEL_TOA              19901 non-null  float64
 30  SEL_Clear sky GHI    19901 non-null  float64
 31  SEL_Clear sky BHI    19901 non-null  float64
 32  SEL_Clear sky DHI    19901 non-null  float64
 33  SEL_Clear sky BNI    19901 non-null  float64
 34  SEL_GHI              19901 non-null  float64
 35  SEL_BHI              19901 non-null  float64
 36  SEL_DHI              19901 non-null  float64
 37  SEL_BNI              19901 non-null  float64
 38  SEL_Reliability      19901 non-null  float64
 39  SVT_TOA              19901 non-null  float64
 40  SVT_Clear sky GHI    19901 non-null  float64
 41  SVT_Clear sky BHI    19901 non-null  float64
 42  SVT_Clear sky DHI    19901 non-null  float64
 43  SVT_Clear sky BNI    19901 non-null  float64
 44  SVT_GHI              19901 non-null  float64
 45  SVT_BHI              19901 non-null  float64
 46  SVT_DHI              19901 non-null  float64
 47  SVT_BNI              19901 non-null  float64
 48  SVT_Reliability      19901 non-null  float64
 49  BRA_TOA              19901 non-null  float64
 50  BRA_Clear sky GHI    19901 non-null  float64
 51  BRA_Clear sky BHI    19901 non-null  float64
 52  BRA_Clear sky DHI    19901 non-null  float64
 53  BRA_Clear sky BNI    19901 non-null  float64
 54  BRA_GHI              19901 non-null  float64
 55  BRA_BHI              19901 non-null  float64
 56  BRA_DHI              19901 non-null  float64
 57  BRA_BNI              19901 non-null  float64
 58  BRA_Reliability      19901 non-null  float64
 59  EYG_TOA              19901 non-null  float64
 60  EYG_Clear sky GHI    19901 non-null  float64
 61  EYG_Clear sky BHI    19901 non-null  float64
 62  EYG_Clear sky DHI    19901 non-null  float64
 63  EYG_Clear sky BNI    19901 non-null  float64
 64  EYG_GHI              19901 non-null  float64
 65  EYG_BHI              19901 non-null  float64
 66  EYG_DHI              19901 non-null  float64
 67  EYG_BNI              19901 non-null  float64
 68  EYG_Reliability      19901 non-null  float64
 69  CRU_Temperature      19901 non-null  float64
 70  CRU_Vitesse_Vent     19901 non-null  float64
 71  CRU_Nebulosite       19901 non-null  float64
 72  CRU_Humidite         19901 non-null  float64
 73  SEL_Temperature      19901 non-null  float64
 74  SEL_Vitesse_Vent     19901 non-null  float64
 75  SEL_Nebulosite       19901 non-null  float64
 76  SEL_Humidite         19901 non-null  float64
 77  SVT_Temperature      19901 non-null  float64
 78  SVT_Vitesse_Vent     19901 non-null  float64
 79  SVT_Nebulosite       19901 non-null  float64
 80  SVT_Humidite         19901 non-null  float64
 81  BRA_Temperature      19901 non-null  float64
 82  BRA_Vitesse_Vent     19901 non-null  float64
 83  BRA_Nebulosite       19901 non-null  float64
 84  BRA_Humidite         19901 non-null  float64
 85  EYG_Temperature      19901 non-null  float64
 86  EYG_Vitesse_Vent     19901 non-null  float64
 87  EYG_Nebulosite       19901 non-null  float64
 88  EYG_Humidite         19901 non-null  float64
dtypes: float64(87), object(2)
memory usage: 13.7+ MB

In [5]:
df = pd.concat([df_2020_2024, df_2025_2026])

# Afficher les premières lignes
display(df.head())

# Afficher les dimensions du dataset
print('Dimensions df :', df.shape, '\n')
print('Taille de df_2020_2024 + taille de df_2025_2026 = taille de df ?',
      (df_2020_2024.shape[0] + df_2025_2026.shape[0] == df.shape[0]) and
      (df_2020_2024.shape[1] == df.shape[1]) and (df_2025_2026.shape[1] == df.shape[1]))

df.info()

,Périmètre,Nature,Consommation,Solaire,Ech. physiques,Stockage batterie,Déstockage batterie,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2019-12-31 23:00:00+00:00,PACA,Données définitives,6123.0,0.0,3332.0,-,-,0.0,0.0,335.596867,...,29.440,57.600,3.230,1.620,5.700,86.880,2.720,1.220,51.750,100.000
2019-12-31 23:30:00+00:00,PACA,Données définitives,5907.0,0.0,2837.0,-,-,0.0,0.0,353.817769,...,24.785,56.165,3.345,1.565,4.635,84.455,2.760,1.405,54.215,98.790
2020-01-01 00:00:00+00:00,PACA,Données définitives,5724.0,0.0,2668.0,-,-,0.0,0.0,12.883689,...,20.130,54.730,3.460,1.510,3.570,82.030,2.800,1.590,56.680,97.580
2020-01-01 00:30:00+00:00,PACA,Données définitives,5749.0,0.0,2754.0,-,-,0.0,0.0,30.261125,...,10.340,54.250,3.650,1.435,3.040,79.380,2.675,1.635,33.325,96.065
2020-01-01 01:00:00+00:00,PACA,Données définitives,5700.0,0.0,2886.0,-,-,0.0,0.0,44.631373,...,0.550,53.770,3.840,1.360,2.510,76.730,2.550,1.680,9.970,94.550

Dimensions df : (107597, 89)

Taille de df_2020_2024 + taille de df_2025_2026 = taille de df ? True
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 107597 entries, 2019-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Périmètre            107597 non-null  object
 1   Nature               107597 non-null  object
 2   Consommation         107597 non-null  float64
 3   Solaire              107597 non-null  float64
 4   Ech. physiques       107597 non-null  float64
 5   Stockage batterie    107597 non-null  object
 6   Déstockage batterie  107597 non-null  object
 7   TCO Solaire (%)      107597 non-null  float64
 8   TCH Solaire (%)      107597 non-null  float64
 9   CRU_azimuth          107597 non-null  float64
 10  CRU_altitude         107597 non-null  float64
 11  SEL_azimuth          107597 non-null  float64
 12  SEL_altitude         107597 non-null  float64
 13  SVT_azimuth          107597 non-null  float64
 14  SVT_altitude         107597 non-null  float64
 15  BRA_azimuth          107597 non-null  float64
 16  BRA_altitude         107597 non-null  float64
 17  EYG_azimuth          107597 non-null  float64
 18  EYG_altitude         107597 non-null  float64
 19  CRU_TOA              107597 non-null  float64
 20  CRU_Clear sky GHI    107597 non-null  float64
 21  CRU_Clear sky BHI    107597 non-null  float64
 22  CRU_Clear sky DHI    107597 non-null  float64
 23  CRU_Clear sky BNI    107597 non-null  float64
 24  CRU_GHI              107597 non-null  float64
 25  CRU_BHI              107597 non-null  float64
 26  CRU_DHI              107597 non-null  float64
 27  CRU_BNI              107597 non-null  float64
 28  CRU_Reliability      107597 non-null  float64
 29  SEL_TOA              107597 non-null  float64
 30  SEL_Clear sky GHI    107597 non-null  float64
 31  SEL_Clear sky BHI    107597 non-null  float64
 32  SEL_Clear sky DHI    107597 non-null  float64
 33  SEL_Clear sky BNI    107597 non-null  float64
 34  SEL_GHI              107597 non-null  float64
 35  SEL_BHI              107597 non-null  float64
 36  SEL_DHI              107597 non-null  float64
 37  SEL_BNI              107597 non-null  float64
 38  SEL_Reliability      107597 non-null  float64
 39  SVT_TOA              107597 non-null  float64
 40  SVT_Clear sky GHI    107597 non-null  float64
 41  SVT_Clear sky BHI    107597 non-null  float64
 42  SVT_Clear sky DHI    107597 non-null  float64
 43  SVT_Clear sky BNI    107597 non-null  float64
 44  SVT_GHI              107597 non-null  float64
 45  SVT_BHI              107597 non-null  float64
 46  SVT_DHI              107597 non-null  float64
 47  SVT_BNI              107597 non-null  float64
 48  SVT_Reliability      107597 non-null  float64
 49  BRA_TOA              107597 non-null  float64
 50  BRA_Clear sky GHI    107597 non-null  float64
 51  BRA_Clear sky BHI    107597 non-null  float64
 52  BRA_Clear sky DHI    107597 non-null  float64
 53  BRA_Clear sky BNI    107597 non-null  float64
 54  BRA_GHI              107597 non-null  float64
 55  BRA_BHI              107597 non-null  float64
 56  BRA_DHI              107597 non-null  float64
 57  BRA_BNI              107597 non-null  float64
 58  BRA_Reliability      107597 non-null  float64
 59  EYG_TOA              107597 non-null  float64
 60  EYG_Clear sky GHI    107597 non-null  float64
 61  EYG_Clear sky BHI    107597 non-null  float64
 62  EYG_Clear sky DHI    107597 non-null  float64
 63  EYG_Clear sky BNI    107597 non-null  float64
 64  EYG_GHI              107597 non-null  float64
 65  EYG_BHI              107597 non-null  float64
 66  EYG_DHI              107597 non-null  float64
 67  EYG_BNI              107597 non-null  float64
 68  EYG_Reliability      107597 non-null  float64
 69  CRU_Temperature      107597 non-null  float64
 70  CRU_Vitesse_Vent     107597 non-null  float64
 71  CRU_Nebulosite       107597 non-null  float64
 72  CRU_Humidite         107597 non-null  float64
 73  SEL_Temperature      107597 non-null  float64
 74  SEL_Vitesse_Vent     107597 non-null  float64
 75  SEL_Nebulosite       107597 non-null  float64
 76  SEL_Humidite         107597 non-null  float64
 77  SVT_Temperature      107597 non-null  float64
 78  SVT_Vitesse_Vent     107597 non-null  float64
 79  SVT_Nebulosite       107597 non-null  float64
 80  SVT_Humidite         107597 non-null  float64
 81  BRA_Temperature      107597 non-null  float64
 82  BRA_Vitesse_Vent     107597 non-null  float64
 83  BRA_Nebulosite       107597 non-null  float64
 84  BRA_Humidite         107597 non-null  float64
 85  EYG_Temperature      107597 non-null  float64
 86  EYG_Vitesse_Vent     107597 non-null  float64
 87  EYG_Nebulosite       107597 non-null  float64
 88  EYG_Humidite         107597 non-null  float64
dtypes: float64(85), object(4)
memory usage: 73.9+ MB

In [6]:
# Normalisation du nom des colonnes (minuscules, pas d'espace, pas de caractères spéciaux autre que '_')

# Récupération du nom des colunnes
nom_cols = df.columns

# Création d'une fonction pour normaliser le nom des colonnes
def clean_name(name):
    resultat = name.lower()
    resultat = resultat.replace('(', '')
    resultat = resultat.replace(')', '')
    resultat = resultat.replace('%', '')
    resultat = resultat.replace('.', '')
    resultat = resultat.strip()
    resultat = resultat.replace(' ', '_')
    resultat = resultat.replace('é', 'e')
    resultat = resultat.replace('è', 'e')
    return resultat

# Initialisation d'un dictionnaire
# les clés seront les noms initiaux
# les valeurs les noms normalisés
dico = {}

# Remplir le dictionnaire
for nom in nom_cols:
    dico[nom] = clean_name(nom)

# Normaliser le nom des colonnes
df = df.rename(columns=dico)
print(df.info())
df.tail()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 107597 entries, 2019-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   perimetre            107597 non-null  object
 1   nature               107597 non-null  object
 2   consommation         107597 non-null  float64
 3   solaire              107597 non-null  float64
 4   ech_physiques        107597 non-null  float64
 5   stockage_batterie    107597 non-null  object
 6   destockage_batterie  107597 non-null  object
 7   tco_solaire          107597 non-null  float64
 8   tch_solaire          107597 non-null  float64
 9   cru_azimuth          107597 non-null  float64
 10  cru_altitude         107597 non-null  float64
 11  sel_azimuth          107597 non-null  float64
 12  sel_altitude         107597 non-null  float64
 13  svt_azimuth          107597 non-null  float64
 14  svt_altitude         107597 non-null  float64
 15  bra_azimuth          107597 non-null  float64
 16  bra_altitude         107597 non-null  float64
 17  eyg_azimuth          107597 non-null  float64
 18  eyg_altitude         107597 non-null  float64
 19  cru_toa              107597 non-null  float64
 20  cru_clear_sky_ghi    107597 non-null  float64
 21  cru_clear_sky_bhi    107597 non-null  float64
 22  cru_clear_sky_dhi    107597 non-null  float64
 23  cru_clear_sky_bni    107597 non-null  float64
 24  cru_ghi              107597 non-null  float64
 25  cru_bhi              107597 non-null  float64
 26  cru_dhi              107597 non-null  float64
 27  cru_bni              107597 non-null  float64
 28  cru_reliability      107597 non-null  float64
 29  sel_toa              107597 non-null  float64
 30  sel_clear_sky_ghi    107597 non-null  float64
 31  sel_clear_sky_bhi    107597 non-null  float64
 32  sel_clear_sky_dhi    107597 non-null  float64
 33  sel_clear_sky_bni    107597 non-null  float64
 34  sel_ghi              107597 non-null  float64
 35  sel_bhi              107597 non-null  float64
 36  sel_dhi              107597 non-null  float64
 37  sel_bni              107597 non-null  float64
 38  sel_reliability      107597 non-null  float64
 39  svt_toa              107597 non-null  float64
 40  svt_clear_sky_ghi    107597 non-null  float64
 41  svt_clear_sky_bhi    107597 non-null  float64
 42  svt_clear_sky_dhi    107597 non-null  float64
 43  svt_clear_sky_bni    107597 non-null  float64
 44  svt_ghi              107597 non-null  float64
 45  svt_bhi              107597 non-null  float64
 46  svt_dhi              107597 non-null  float64
 47  svt_bni              107597 non-null  float64
 48  svt_reliability      107597 non-null  float64
 49  bra_toa              107597 non-null  float64
 50  bra_clear_sky_ghi    107597 non-null  float64
 51  bra_clear_sky_bhi    107597 non-null  float64
 52  bra_clear_sky_dhi    107597 non-null  float64
 53  bra_clear_sky_bni    107597 non-null  float64
 54  bra_ghi              107597 non-null  float64
 55  bra_bhi              107597 non-null  float64
 56  bra_dhi              107597 non-null  float64
 57  bra_bni              107597 non-null  float64
 58  bra_reliability      107597 non-null  float64
 59  eyg_toa              107597 non-null  float64
 60  eyg_clear_sky_ghi    107597 non-null  float64
 61  eyg_clear_sky_bhi    107597 non-null  float64
 62  eyg_clear_sky_dhi    107597 non-null  float64
 63  eyg_clear_sky_bni    107597 non-null  float64
 64  eyg_ghi              107597 non-null  float64
 65  eyg_bhi              107597 non-null  float64
 66  eyg_dhi              107597 non-null  float64
 67  eyg_bni              107597 non-null  float64
 68  eyg_reliability      107597 non-null  float64
 69  cru_temperature      107597 non-null  float64
 70  cru_vitesse_vent     107597 non-null  float64
 71  cru_nebulosite       107597 non-null  float64
 72  cru_humidite         107597 non-null  float64
 73  sel_temperature      107597 non-null  float64
 74  sel_vitesse_vent     107597 non-null  float64
 75  sel_nebulosite       107597 non-null  float64
 76  sel_humidite         107597 non-null  float64
 77  svt_temperature      107597 non-null  float64
 78  svt_vitesse_vent     107597 non-null  float64
 79  svt_nebulosite       107597 non-null  float64
 80  svt_humidite         107597 non-null  float64
 81  bra_temperature      107597 non-null  float64
 82  bra_vitesse_vent     107597 non-null  float64
 83  bra_nebulosite       107597 non-null  float64
 84  bra_humidite         107597 non-null  float64
 85  eyg_temperature      107597 non-null  float64
 86  eyg_vitesse_vent     107597 non-null  float64
 87  eyg_nebulosite       107597 non-null  float64
 88  eyg_humidite         107597 non-null  float64
dtypes: float64(85), object(4)
memory usage: 73.9+ MB
None

,perimetre,nature,consommation,solaire,ech_physiques,stockage_batterie,destockage_batterie,tco_solaire,tch_solaire,cru_azimuth,...,svt_nebulosite,svt_humidite,bra_temperature,bra_vitesse_vent,bra_nebulosite,bra_humidite,eyg_temperature,eyg_vitesse_vent,eyg_nebulosite,eyg_humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2026-02-19 11:00:00+00:00,PACA,Données temps réel,5181.0,678.0,3030.0,0.0,0.0,13.09,24.08,165.120233,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 11:30:00+00:00,PACA,Données temps réel,5211.0,825.0,2917.0,0.0,0.0,15.83,29.30,173.922880,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 12:00:00+00:00,PACA,Données temps réel,5152.0,842.0,2854.0,0.0,0.0,16.34,29.90,182.864978,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 12:30:00+00:00,PACA,Données temps réel,5177.0,909.0,2833.0,0.0,0.0,17.56,32.28,191.743652,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 13:00:00+00:00,PACA,Données temps réel,5060.0,726.0,2884.0,0.0,0.0,14.35,25.78,200.367731,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4

In [7]:
# Séparation train - valid - test
date_debut_train = '2019-12-31'
date_fin_train = '2023-12-31'
date_debut_valid = '2024-01-01'
date_fin_valid = '2024-12-31'
date_debut_test = '2025-01-01'
date_fin_test = '2026-12-31'

df_train = df[date_debut_train : date_fin_train] # 2020, 2021, 2022, 2023
df_valid = df[date_debut_valid : date_fin_valid] # 2024
df_test = df[date_debut_test : date_fin_test] # 2025

# Vu les NaN qui seraient introduits par le calcul des lags,
# on calculera les nouvelles variables sur df
# (pour le choix des colonnes à supprimer, on se base sur df_train)

print(f"df_train commence le {df_train.index[0]} et s'arrête le {df_train.index[-1]}")
print(f"df_valid commence le {df_valid.index[0]} et s'arrête le {df_valid.index[-1]}")
print(f"df_test commence le {df_test.index[0]} et s'arrête le {df_test.index[-1]}")

df_train commence le 2019-12-31 23:00:00+00:00 et s'arrête le 2023-12-31 23:30:00+00:00
df_valid commence le 2024-01-01 00:00:00+00:00 et s'arrête le 2024-12-31 23:30:00+00:00
df_test commence le 2025-01-01 00:00:00+00:00 et s'arrête le 2026-02-19 13:00:00+00:00

In [8]:
# Etude des variables de type object
col_object = df_train.select_dtypes(include=['object']).columns

for col in col_object:
    print(f'{col} : {df_train[col].nunique()} valeurs différentes {df_train[col].unique()}')

perimetre : 1 valeurs différentes ['PACA']
nature : 2 valeurs différentes ['Données définitives' 'Données consolidées']
stockage_batterie : 4 valeurs différentes ['-' '0' '0.0' 0.0]
destockage_batterie : 4 valeurs différentes ['-' '0' '0.0' 0.0]

In [9]:
# Les variables de type object ne transportent pas d'information pouvant être utile à notre problématique
df_train = df_train.drop(col_object, axis=1)
df_valid = df_valid.drop(col_object, axis=1)
df_test = df_test.drop(col_object, axis=1)

# On les supprimera du dataset consolidé
# On crée une liste des variables à supprimer
colonnes_a_supprimer = list(col_object)

In [10]:
# Trouver les variables explicatives qui ont une variance inférieure à 0.01
sel = VarianceThreshold(threshold=0.01)
sel.fit(df_train)

# Afficher les variables concernées
mask = sel.get_support()
print("Variables de faible variance :", df_train.columns[~mask])

# On supprime les variables dont la variance est trop faible
new_colonnes_a_supprimer = list(df_train.columns[~mask])

Variables de faible variance : Index(['cru_reliability', 'sel_reliability', 'svt_reliability',
       'bra_reliability', 'eyg_reliability'],
      dtype='object')

In [11]:
# La variable 'ech_physiques' correspond aux flux nets d'électricité échangés avec les zones voisines
# Elle ne concerne pas notre problématique
new_colonnes_a_supprimer.extend(['ech_physiques'])

In [12]:
# On a fini d'identifier les colonnes à supprimer à partir de df_train
# On applique à df
print(f"Taille de df_train avant supression des colonnes : {df_train.shape}")
df_train = df_train.drop(new_colonnes_a_supprimer, axis=1)
df_valid = df_valid.drop(new_colonnes_a_supprimer, axis=1)
df_test = df_test.drop(new_colonnes_a_supprimer, axis=1)
print(f"Taille de df_train après supression des colonnes : {df_train.shape}")

Taille de df_train avant supression des colonnes : (70130, 85)
Taille de df_train après supression des colonnes : (70130, 79)

In [13]:
# Construction de la variable cible :
# on calcule la variation absolue de `tch_solaire` entre t et t+1
# df_train['target'] = |tch_solaire(t+1) - tch_solaire(t)|
df_train['target'] = df_train['tch_solaire'].shift(-1).sub(df_train['tch_solaire']).abs()
df_valid['target'] = df_valid['tch_solaire'].shift(-1).sub(df_valid['tch_solaire']).abs()
df_test['target'] = df_test['tch_solaire'].shift(-1).sub(df_test['tch_solaire']).abs()

In [14]:
def ajout_encodage_temporel_cyclique(df):
    """
    Ajoute des variables cycliques liées au temps :
    - heure de la journée : sin_hour, cos_hour
    - jour de l'année : sin_doy, cos_doy
    
    """

    # Copie pour éviter de modifier le DataFrame original
    df = df.copy()

    # Encodage cyclique de l'heure (heure + minutes)
    hour = df.index.hour + df.index.minute / 60
    df['sin_hour'] = np.sin(2 * np.pi * hour / 24)
    df['cos_hour'] = np.cos(2 * np.pi * hour / 24)

    # Encodage cyclique du jour de l'année
    # dayofyear commence à 1, donc on retire 1 pour démarrer à 0
    doy = df.index.dayofyear - 1

    # Nombre de jours selon que l'année est bissextile ou non
    nb_jour_annee = np.where(df.index.is_leap_year, 366, 365)

    df['sin_doy'] = np.sin(2 * np.pi * doy / nb_jour_annee)
    df['cos_doy'] = np.cos(2 * np.pi * doy / nb_jour_annee)

    return df

df_train = ajout_encodage_temporel_cyclique(df_train)
df_valid = ajout_encodage_temporel_cyclique(df_valid)
df_test  = ajout_encodage_temporel_cyclique(df_test)

display(df_train[['sin_hour', 'cos_hour', 'sin_doy', 'cos_doy']].head())

print("Taille de df_train :", df_train.shape)
print("Taille de df_valid :", df_valid.shape)
print("Taille de df_test  :", df_test.shape)

                           sin_hour  cos_hour   sin_doy   cos_doy
datetime_utc
2019-12-31 23:00:00+00:00 -0.258819  0.965926 -0.017213  0.999852
2019-12-31 23:30:00+00:00 -0.130526  0.991445 -0.017213  0.999852
2020-01-01 00:00:00+00:00  0.000000  1.000000  0.000000  1.000000
2020-01-01 00:30:00+00:00  0.130526  0.991445  0.000000  1.000000
2020-01-01 01:00:00+00:00  0.258819  0.965926  0.000000  1.000000

Taille de df_train : (70130, 84)
Taille de df_valid : (17568, 84)
Taille de df_test  : (19899, 84)

In [15]:
# On va créé un second dataset avec moins de colonnes
# en utilisant des moyennes pondérées sur les colonnes concernant les 5 points d'intérêts retenus

# Chargement une seule fois du fichier des communes représentatives
df_communes = pd.read_csv(
    "/Projet_Moustafa_Datascience/aug25cds_variabilite/data/local_data/01_Clustering/output/best_communes_geo_energy.csv"
)

# Mise en minuscule des préfixes pour éviter les problèmes de correspondance
df_communes["prefix"] = df_communes["prefix"].str.lower()

# Série des poids indexée par préfixe de ville
poids_par_ville = df_communes.set_index("prefix")["poids"]
print(poids_par_ville)

# Liste des villes dans l'ordre des poids
villes = poids_par_ville.index.tolist()

villes

prefix
cru    0.22
sel    0.06
svt    0.07
bra    0.29
eyg    0.36
Name: poids, dtype: float64

['cru', 'sel', 'svt', 'bra', 'eyg']

> L'`azimuth` représente la position horizontale du soleil (angle entre 0° et 360°).
C'est une variable **circulaire** :
> - 0° et 360° correspondent à la même direction
> - 359° est très proche de 1°
>
> Un encodage classique introduit donc une discontinuité artificielle.
Pour corriger cela, on transforme l'`azimuth` en **sinus** et **cosinus**, ce qui permet de préserver sa nature cyclique et d'améliorer les performances des modèles.

In [16]:
def ajout_encodage_azimuth_cyclique(df, villes):
    """
    Ajoute un encodage cyclique de l'azimuth pour chaque ville :
    - {ville}_azimuth_sin
    - {ville}_azimuth_cos
    """

    # Copie pour éviter de modifier le DataFrame original
    df = df.copy()

    for ville in villes:
        col = f"{ville}_azimuth"

        # Vérifie que la colonne existe
        if col not in df.columns:
            continue

        # Conversion en radians
        azimuth_rad = np.radians(df[col])

        # Encodage cyclique
        df[f"{ville}_azimuth_sin"] = np.sin(azimuth_rad)
        df[f"{ville}_azimuth_cos"] = np.cos(azimuth_rad)

        # Suppression de la colonne brute
        df = df.drop(columns=[col])

    return df

df_train = ajout_encodage_azimuth_cyclique(df_train, villes)
df_valid = ajout_encodage_azimuth_cyclique(df_valid, villes)
df_test  = ajout_encodage_azimuth_cyclique(df_test, villes)

display(df_train[['bra_azimuth_sin', 'bra_azimuth_sin']].head())

print("Taille de df_train :", df_train.shape)
print("Taille de df_valid :", df_valid.shape)
print("Taille de df_test  :", df_test.shape)

                           bra_azimuth_sin  bra_azimuth_sin
datetime_utc
2019-12-31 23:00:00+00:00        -0.418802        -0.418802
2019-12-31 23:30:00+00:00        -0.105471        -0.105471
2020-01-01 00:00:00+00:00         0.234067         0.234067
2020-01-01 00:30:00+00:00         0.518630         0.518630
2020-01-01 01:00:00+00:00         0.715689         0.715689

Taille de df_train : (70130, 89)
Taille de df_valid : (17568, 89)
Taille de df_test  : (19899, 89)

In [17]:
# Récupération de la base des noms de colonnes concernés
col_par_ville = []
# Comme tous les points d'intérêts ont exactement les même colonnes les concernant
# On fait une recherche des noms concernant la ville de Bras
for col in df_train.columns :
    if col[:3] == "bra":
        col_par_ville.append(col[4:])
print(col_par_ville)
print("Nombre de colonnes concernant chaque point d'intérêt :", len(col_par_ville))

['altitude', 'toa', 'clear_sky_ghi', 'clear_sky_bhi', 'clear_sky_dhi', 'clear_sky_bni', 'ghi', 'bhi', 'dhi', 'bni', 'temperature', 'vitesse_vent', 'nebulosite', 'humidite', 'azimuth_sin', 'azimuth_cos']
Nombre de colonnes concernant chaque point d'intérêt : 16

In [18]:
def appliquer_ponderation_regionale(df, col_par_ville, poids_par_ville):
    """
    Crée des colonnes régionales pondérées à partir des colonnes par ville,
    puis supprime les anciennes colonnes par ville.

    Paramètres
    ----------
    df : pd.DataFrame
        DataFrame d'entrée à transformer.
    col_par_ville : list
        Liste des variables à agréger, par exemple :
        ["ghi", "dni", "temp"]
    poids_par_ville : pd.Series
        Série contenant les poids, indexée par le préfixe de la ville.

    Retour
    ------
    pd.DataFrame
        Nouveau DataFrame transformé.
    """

    # Copie pour éviter de modifier le DataFrame original
    df = df.copy()

    # Dictionnaire qui contiendra les nouvelles colonnes régionales calculées
    region_cols = {}

    # Liste des colonnes par ville à supprimer après agrégation
    cols_to_drop = []

    # Liste des villes dans l'ordre des poids
    # villes = poids_par_ville.index.tolist()

    # Tableau numpy des poids pour le calcul vectorisé
    weights = poids_par_ville.to_numpy()

    # Boucle sur chaque variable à agréger
    for col in col_par_ville:
        # Construction des noms de colonnes attendues pour cette variable
        # Exemple : marseille_ghi, nice_ghi, toulon_ghi, ...
        all_concerns_cols = [f"{ville}_{col}" for ville in villes]

        # Vérification que toutes les colonnes nécessaires existent bien
        missing_cols = [c for c in all_concerns_cols if c not in df.columns]
        if missing_cols:
            raise KeyError(f"Colonnes manquantes dans df pour '{col}' : {missing_cols}")

        # Calcul de la somme pondérée :
        # chaque colonne ville_variable est multipliée par son poids,
        # puis on somme ligne par ligne
        region_cols[f"region_{col}"] = (
            df[all_concerns_cols]
            .mul(weights, axis=1)
            .sum(axis=1)
        )

        # On mémorise les colonnes d'origine à supprimer ensuite
        cols_to_drop.extend(all_concerns_cols)

    # Ajout en une seule fois des nouvelles colonnes régionales
    df = pd.concat([df, pd.DataFrame(region_cols, index=df.index)], axis=1)

    # Suppression des anciennes colonnes par ville
    df = df.drop(columns=cols_to_drop)

    # Copie finale optionnelle pour défragmenter le DataFrame
    df = df.copy()

    return df

df_region_train = appliquer_ponderation_regionale(df_train, col_par_ville, poids_par_ville)
df_region_valid = appliquer_ponderation_regionale(df_valid, col_par_ville, poids_par_ville)
df_region_test  = appliquer_ponderation_regionale(df_test,  col_par_ville, poids_par_ville)

print("Taille de df_region_train :", df_region_train.shape)
print("Taille de df_region_valid :", df_region_valid.shape)
print("Taille de df_region_test  :", df_region_test.shape)

Taille de df_region_train : (70130, 25)
Taille de df_region_valid : (17568, 25)
Taille de df_region_test  : (19899, 25)

In [19]:
df_region_train.columns

Index(['consommation', 'solaire', 'tco_solaire', 'tch_solaire', 'target',
       'sin_hour', 'cos_hour', 'sin_doy', 'cos_doy', 'region_altitude',
       'region_toa', 'region_clear_sky_ghi', 'region_clear_sky_bhi',
       'region_clear_sky_dhi', 'region_clear_sky_bni', 'region_ghi',
       'region_bhi', 'region_dhi', 'region_bni', 'region_temperature',
       'region_vitesse_vent', 'region_nebulosite', 'region_humidite',
       'region_azimuth_sin', 'region_azimuth_cos'],
      dtype='object')

In [20]:
def construction_features_meteo(df, vars_meteo, lags, windows, prefix_list):
    new_cols = {}

    # Génération des variables dérivées pour chaque ville ou region et chaque variable météo
    for prefix in prefix_list:
        for var in vars_meteo:
            col_name = f"{prefix}{var}"
            if col_name not in df.columns:
                print(f"{col_name} n'existe pas.")

            serie = df[col_name]
            
            # Variation instantanée de la variable
            dserie = serie.diff()

            # Ajout de la différence première
            new_cols[f"{prefix}d{var}_dt"] = dserie

            # Création des variables retardées
            for lag in lags:
                new_cols[f"{prefix}{var}_lag_{lag}"] = serie.shift(lag)
                new_cols[f"{prefix}d{var}_lag_{lag}"] = dserie.shift(lag)

            # Calcul des statistiques glissantes
            for w in windows:
                new_cols[f"{prefix}{var}_roll_mean_{w}h"] = serie.rolling(w).mean()
                new_cols[f"{prefix}{var}_roll_std_{w}h"] = serie.rolling(w).std()

                new_cols[f"{prefix}d{var}_roll_mean_{w}h"] = dserie.rolling(w).mean()
                new_cols[f"{prefix}d{var}_roll_std_{w}h"] = dserie.rolling(w).std()

    return pd.concat([df, pd.DataFrame(new_cols, index=df.index)], axis=1)

prefix_villes = [f"{v}_" for v in villes]
prefix_region = ["region_"]

vars_meteo = ['ghi', 'nebulosite']
lags = [1, 2, 3]
windows = [4]

print("Shape avant construction_features_meteo:\n")
print(f"Taille de df_train : {df_train.shape}")
print(f"Taille de df_valid : {df_valid.shape}")
print(f"Taille de df_test  : {df_test.shape}\n")
print(f"Taille de df_region_train : {df_region_train.shape}")
print(f"Taille de df_region_valid : {df_region_valid.shape}")
print(f"Taille de df_region_test  : {df_region_test.shape}")

df_train = construction_features_meteo(df_train, vars_meteo, lags, windows, prefix_villes)
df_valid = construction_features_meteo(df_valid, vars_meteo, lags, windows, prefix_villes)
df_test  = construction_features_meteo(df_test, vars_meteo, lags, windows, prefix_villes)
df_region_train = construction_features_meteo(df_region_train, vars_meteo, lags, windows, prefix_region)
df_region_valid = construction_features_meteo(df_region_valid, vars_meteo, lags, windows, prefix_region)
df_region_test  = construction_features_meteo(df_region_test, vars_meteo, lags, windows, prefix_region)

print("Shape après construction_features_meteo:\n")
print(f"Taille de df_train : {df_train.shape}")
print(f"Taille de df_valid : {df_valid.shape}")
print(f"Taille de df_test  : {df_test.shape}\n")
print(f"Taille de df_region_train : {df_region_train.shape}")
print(f"Taille de df_region_valid : {df_region_valid.shape}")
print(f"Taille de df_region_test  : {df_region_test.shape}")

Shape avant construction_features_meteo:

Taille de df_train : (70130, 89)
Taille de df_valid : (17568, 89)
Taille de df_test  : (19899, 89)

Taille de df_region_train : (70130, 25)
Taille de df_region_valid : (17568, 25)
Taille de df_region_test  : (19899, 25)
Shape après construction_features_meteo:

Taille de df_train : (70130, 199)
Taille de df_valid : (17568, 199)
Taille de df_test  : (19899, 199)

Taille de df_region_train : (70130, 47)
Taille de df_region_valid : (17568, 47)
Taille de df_region_test  : (19899, 47)

In [21]:
def construction_features_ghi(df, prefixes):
    new_cols = {}

    # Calcul du maximum mensuel de la variable "solaire"
    # transform("max") permet de conserver un index aligné avec df
    solaire_monthly_max = df["solaire"].groupby(
        pd.Grouper(freq="ME")      #"ME" = new explicit name for month-end
    ).transform("max")

    for prefix in prefixes:
        # Extraction des variables GHI et de sa dérivée temporelle
        ghi = df[f"{prefix}ghi"]
        dghi = df[f"{prefix}dghi_dt"]
        clear = df[f"{prefix}clear_sky_ghi"]
        ghi_threshold = ghi.quantile(0.7)

        # Calcul du Clear Sky Index (CSI)
        # On évite la division par zéro avec clip
        csi = ghi / clear.clip(lower=1e-6)
        # On met à 0 les valeurs où le clear_sky est trop faible
        csi = csi.where(clear >= 1, 0)

        # Détection d'anomalies solaires (par mois)
        # Une anomalie est détectée si :
        # - irradiance élevée
        # - mais production solaire faible par rapport au max mensuel
        anomaly = (
            (ghi > ghi_threshold) & # Détection des périodes de forte irradiance
            (csi > 0.7) & # ciel clair
            (df["solaire"] < 0.9 * solaire_monthly_max) # production solaire faible par rapport au max mensuel
        ).astype(int)


        # Stockage des nouvelles variables dans un dictionnaire
        new_cols[f"{prefix}csi"] = csi
        new_cols[f"{prefix}abs_dghi_dt"] = dghi.abs()
        new_cols[f"{prefix}anomaly"] = anomaly

    return pd.concat([df, pd.DataFrame(new_cols, index=df.index)], axis=1)

df_train = construction_features_ghi(df_train, prefix_villes)
df_valid = construction_features_ghi(df_valid, prefix_villes)
df_test  = construction_features_ghi(df_test,  prefix_villes)

df_region_train = construction_features_ghi(df_region_train, prefix_region)
df_region_valid = construction_features_ghi(df_region_valid, prefix_region)
df_region_test  = construction_features_ghi(df_region_test,  prefix_region)

print("Shape après construction_features_ghi:\n")
print(f"Taille de df_train : {df_train.shape}")
print(f"Taille de df_valid : {df_valid.shape}")
print(f"Taille de df_test  : {df_test.shape}\n")
print(f"Taille de df_region_train : {df_region_train.shape}")
print(f"Taille de df_region_valid : {df_region_valid.shape}")
print(f"Taille de df_region_test  : {df_region_test.shape}")

Shape après construction_features_ghi:

Taille de df_train : (70130, 214)
Taille de df_valid : (17568, 214)
Taille de df_test  : (19899, 214)

Taille de df_region_train : (70130, 50)
Taille de df_region_valid : (17568, 50)
Taille de df_region_test  : (19899, 50)

In [22]:
def construction_features_tch(df, lags, windows):
    new_cols = {}

    tch = df["tch_solaire"]
    dtch = tch.diff()
    abs_dtch = dtch.abs()    
    new_cols["dtch_dt"] = dtch
    new_cols["abs_dtch_dt"] = abs_dtch
    # Variables retardées du TCH solaire et de ses variations
    for lag in lags:
        new_cols[f"tch_lag_{lag}"] = tch.shift(lag)
        new_cols[f"dtch_lag_{lag}"] = dtch.shift(lag)
        new_cols[f"abs_dtch_lag_{lag}"] = abs_dtch.shift(lag)

    # Statistiques glissantes
    for w in windows:
        new_cols[f"tch_roll_mean_{w}h"] = tch.rolling(w).mean()
        new_cols[f"tch_roll_std_{w}h"] = tch.rolling(w).std()

        new_cols[f"dtch_roll_mean_{w}h"] = dtch.rolling(w).mean()
        new_cols[f"dtch_roll_std_{w}h"] = dtch.rolling(w).std()

        new_cols[f"abs_dtch_roll_mean_{w}h"] = abs_dtch.rolling(w).mean()
        new_cols[f"abs_dtch_roll_std_{w}h"] = abs_dtch.rolling(w).std()

    df_new = pd.DataFrame(new_cols, index=df.index)
    return pd.concat([df, df_new], axis=1)

df_train = construction_features_tch(df_train, lags, windows)
df_valid = construction_features_tch(df_valid, lags, windows)
df_test  = construction_features_tch(df_test, lags, windows)
df_region_train = construction_features_tch(df_region_train, lags, windows)
df_region_valid = construction_features_tch(df_region_valid, lags, windows)
df_region_test  = construction_features_tch(df_region_test,  lags, windows)

print("Taille après construction_features_tch:\n")
print(f"Taille de df_train : {df_train.shape}")
print(f"Taille de df_valid : {df_valid.shape}")
print(f"Taille de df_test  : {df_test.shape}\n")
print(f"Taille de df_region_train : {df_region_train.shape}")
print(f"Taille de df_region_valid : {df_region_valid.shape}")
print(f"Taille de df_region_test  : {df_region_test.shape}")

Taille après construction_features_tch:

Taille de df_train : (70130, 231)
Taille de df_valid : (17568, 231)
Taille de df_test  : (19899, 231)

Taille de df_region_train : (70130, 67)
Taille de df_region_valid : (17568, 67)
Taille de df_region_test  : (19899, 67)

In [23]:
df_train.info() # toutes les colonnes sont de type float64

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 70130 entries, 2019-12-31 23:00:00+00:00 to 2023-12-31 23:30:00+00:00
Columns: 231 entries, consommation to abs_dtch_roll_std_4h
dtypes: float64(226), int32(5)
memory usage: 122.8 MB

In [24]:
# Réorganiser les colonnes, supprimer les valeurs manquantes introduites
df_train = df_train.reindex(columns=df_train.columns.sort_values()).dropna()
df_valid = df_valid.reindex(columns=df_valid.columns.sort_values()).dropna()
df_test = df_test.reindex(columns=df_test.columns.sort_values()).dropna()
df_region_train = df_region_train.reindex(columns=df_region_train.columns.sort_values()).dropna()
df_region_valid = df_region_valid.reindex(columns=df_region_valid.columns.sort_values()).dropna()
df_region_test = df_region_test.reindex(columns=df_region_test.columns.sort_values()).dropna()

# vérifier la taille
print("Taille de df_train :", df_train.shape)
print("Taille de df_valid :", df_valid.shape)
print("Taille de df_test  :", df_test.shape)
print(f"Taille de df_region_train : {df_region_train.shape}")
print(f"Taille de df_region_valid : {df_region_valid.shape}")
print(f"Taille de df_region_test  : {df_region_test.shape}")

# aperçu des données
display(df_train.head(2))
display(df_valid.head(2))
display(df_test.head(2))

Taille de df_train : (70125, 231)
Taille de df_valid : (17563, 231)
Taille de df_test  : (19894, 231)
Taille de df_region_train : (70125, 67)
Taille de df_region_valid : (17563, 67)
Taille de df_region_test  : (19894, 67)

,abs_dtch_dt,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_roll_mean_4h,abs_dtch_roll_std_4h,bra_abs_dghi_dt,bra_altitude,bra_anomaly,bra_azimuth_cos,...,svt_toa,svt_vitesse_vent,target,tch_lag_1,tch_lag_2,tch_lag_3,tch_roll_mean_4h,tch_roll_std_4h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 01:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-63.656435,0,0.698419,...,0.0,0.740,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 01:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-59.396257,0,0.542844,...,0.0,0.765,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,abs_dtch_dt,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_roll_mean_4h,abs_dtch_roll_std_4h,bra_abs_dghi_dt,bra_altitude,bra_anomaly,bra_azimuth_cos,...,svt_toa,svt_vitesse_vent,target,tch_lag_1,tch_lag_2,tch_lag_3,tch_roll_mean_4h,tch_roll_std_4h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-01-01 02:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-54.603773,0,0.402650,...,0.0,4.86,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 02:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-49.489244,0,0.278991,...,0.0,4.80,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,abs_dtch_dt,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_roll_mean_4h,abs_dtch_roll_std_4h,bra_abs_dghi_dt,bra_altitude,bra_anomaly,bra_azimuth_cos,...,svt_toa,svt_vitesse_vent,target,tch_lag_1,tch_lag_2,tch_lag_3,tch_roll_mean_4h,tch_roll_std_4h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 02:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-54.623026,0,0.405484,...,0.0,0.78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 02:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-49.513822,0,0.281615,...,0.0,0.78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
# On enregistre 3 datasets pour train / valid / test pour les 5 communes
df_train.to_csv(filepath_output + "train_5pts.csv")
df_valid.to_csv(filepath_output + "valid_5pts.csv")
df_test.to_csv(filepath_output + "test_5pts.csv")

# On enregistre 3 datasets pour train / valid / test pour la région
df_region_train.to_csv(filepath_output + "train_region.csv")
df_region_valid.to_csv(filepath_output + "valid_region.csv")
df_region_test.to_csv(filepath_output + "test_region.csv")

In [26]:
# Check
print("Train :")
df_train = pd.read_csv(filepath_output + "train_5pts.csv", index_col='datetime_utc', parse_dates=True)
display(df_train.head())
print("Taille du dataset :", df_train.shape)

print("\nValid :")
df_valid = pd.read_csv(filepath_output + "valid_5pts.csv", index_col='datetime_utc', parse_dates=True)
display(df_valid.head())
print("Taille du dataset :", df_valid.shape)

print("\nTest :")
df_test = pd.read_csv(filepath_output + "test_5pts.csv", index_col='datetime_utc', parse_dates=True)
display(df_test.head())
print("Taille du dataset :", df_test.shape)

Train :

,abs_dtch_dt,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_roll_mean_4h,abs_dtch_roll_std_4h,bra_abs_dghi_dt,bra_altitude,bra_anomaly,bra_azimuth_cos,...,svt_toa,svt_vitesse_vent,target,tch_lag_1,tch_lag_2,tch_lag_3,tch_roll_mean_4h,tch_roll_std_4h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 01:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-63.656435,0,0.698419,...,0.0,0.740,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 01:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-59.396257,0,0.542844,...,0.0,0.765,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 02:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-54.602951,0,0.402616,...,0.0,0.790,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 02:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-49.488368,0,0.278960,...,0.0,0.830,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 03:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-44.186485,0,0.169099,...,0.0,0.870,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Taille du dataset : (70125, 231)

Valid :

,abs_dtch_dt,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_roll_mean_4h,abs_dtch_roll_std_4h,bra_abs_dghi_dt,bra_altitude,bra_anomaly,bra_azimuth_cos,...,svt_toa,svt_vitesse_vent,target,tch_lag_1,tch_lag_2,tch_lag_3,tch_roll_mean_4h,tch_roll_std_4h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-01-01 02:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-54.603773,0,0.402650,...,0.0,4.86,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 02:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-49.489244,0,0.278991,...,0.0,4.80,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 03:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-44.187389,0,0.169127,...,0.0,4.74,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 03:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-38.786269,0,0.069772,...,0.0,4.68,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-01 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-33.347785,0,-0.021897,...,0.0,4.62,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Taille du dataset : (17563, 231)

Test :

,abs_dtch_dt,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_roll_mean_4h,abs_dtch_roll_std_4h,bra_abs_dghi_dt,bra_altitude,bra_anomaly,bra_azimuth_cos,...,svt_toa,svt_vitesse_vent,target,tch_lag_1,tch_lag_2,tch_lag_3,tch_roll_mean_4h,tch_roll_std_4h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 02:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-54.623026,0,0.405484,...,0.0,0.780,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 02:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-49.513822,0,0.281615,...,0.0,0.780,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 03:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-44.215055,0,0.171550,...,0.0,0.780,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 03:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-38.815396,0,0.072021,...,0.0,0.785,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-33.377127,0,-0.019794,...,0.0,0.790,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Taille du dataset : (19894, 231)

In [27]:
# Check
print("Train :")
df_train = pd.read_csv(filepath_output + "train_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_train.head(-1))
print("Taille du dataset :", df_train.shape)

print("\nValid :")
df_valid = pd.read_csv(filepath_output + "valid_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_valid.head(-1))
print("Taille du dataset :", df_valid.shape)

print("\nTest :")
df_test = pd.read_csv(filepath_output + "test_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_test.head(-1))
print("Taille du dataset :", df_test.shape)

Train :

,abs_dtch_dt,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_roll_mean_4h,abs_dtch_roll_std_4h,consommation,cos_doy,cos_hour,dtch_dt,...,sin_hour,solaire,target,tch_lag_1,tch_lag_2,tch_lag_3,tch_roll_mean_4h,tch_roll_std_4h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 01:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,5700.0,1.000000,0.965926,0.0,...,0.258819,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 01:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,5803.0,1.000000,0.923880,0.0,...,0.382683,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 02:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,5566.0,1.000000,0.866025,0.0,...,0.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 02:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,5433.0,1.000000,0.793353,0.0,...,0.608761,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 03:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,5332.0,1.000000,0.707107,0.0,...,0.707107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-31 20:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,4752.0,0.999852,0.608761,0.0,...,-0.793353,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-12-31 21:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,4752.0,0.999852,0.707107,0.0,...,-0.707107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-12-31 21:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,4827.0,0.999852,0.793353,0.0,...,-0.608761,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-12-31 22:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,4982.0,0.999852,0.866025,0.0,...,-0.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-12-31 22:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,5232.0,0.999852,0.923880,0.0,...,-0.382683,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Taille du dataset : (70125, 67)

Valid :

,abs_dtch_dt,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_roll_mean_4h,abs_dtch_roll_std_4h,consommation,cos_doy,cos_hour,dtch_dt,...,sin_hour,solaire,target,tch_lag_1,tch_lag_2,tch_lag_3,tch_roll_mean_4h,tch_roll_std_4h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-01-01 02:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,4737.0,1.000000,0.866025,0.0,...,0.500000,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
2024-01-01 02:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,4618.0,1.000000,0.793353,0.0,...,0.608761,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
2024-01-01 03:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,4464.0,1.000000,0.707107,0.0,...,0.707107,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
2024-01-01 03:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,4400.0,1.000000,0.608761,0.0,...,0.793353,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
2024-01-01 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,4349.0,1.000000,0.500000,0.0,...,0.866025,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 20:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,5543.0,0.999853,0.608761,0.0,...,-0.793353,1.0,0.00,0.04,0.04,0.04,0.04,0.0,0.04,0.02
2024-12-31 21:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,5466.0,0.999853,0.707107,0.0,...,-0.707107,1.0,0.00,0.04,0.04,0.04,0.04,0.0,0.04,0.02
2024-12-31 21:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,5508.0,0.999853,0.793353,0.0,...,-0.608761,1.0,0.00,0.04,0.04,0.04,0.04,0.0,0.04,0.02
2024-12-31 22:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,5718.0,0.999853,0.866025,0.0,...,-0.500000,1.0,0.00,0.04,0.04,0.04,0.04,0.0,0.04,0.02
2024-12-31 22:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,5908.0,0.999853,0.923880,0.0,...,-0.382683,1.0,0.04,0.04,0.04,0.04,0.04,0.0,0.04,0.02

Taille du dataset : (17563, 67)

Test :

,abs_dtch_dt,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_roll_mean_4h,abs_dtch_roll_std_4h,consommation,cos_doy,cos_hour,dtch_dt,...,sin_hour,solaire,target,tch_lag_1,tch_lag_2,tch_lag_3,tch_roll_mean_4h,tch_roll_std_4h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 02:00:00+00:00,0.00,0.00,0.00,0.00,0.0000,0.000000,5070.0,1.000000,0.866025,0.00,...,5.000000e-01,0.0,0.00,0.00,0.00,0.00,0.0000,0.000000,0.00,0.00
2025-01-01 02:30:00+00:00,0.00,0.00,0.00,0.00,0.0000,0.000000,4948.0,1.000000,0.793353,0.00,...,6.087614e-01,0.0,0.00,0.00,0.00,0.00,0.0000,0.000000,0.00,0.00
2025-01-01 03:00:00+00:00,0.00,0.00,0.00,0.00,0.0000,0.000000,4834.0,1.000000,0.707107,0.00,...,7.071068e-01,0.0,0.00,0.00,0.00,0.00,0.0000,0.000000,0.00,0.00
2025-01-01 03:30:00+00:00,0.00,0.00,0.00,0.00,0.0000,0.000000,4763.0,1.000000,0.608761,0.00,...,7.933533e-01,0.0,0.00,0.00,0.00,0.00,0.0000,0.000000,0.00,0.00
2025-01-01 04:00:00+00:00,0.00,0.00,0.00,0.00,0.0000,0.000000,4702.0,1.000000,0.500000,0.00,...,8.660254e-01,0.0,0.00,0.00,0.00,0.00,0.0000,0.000000,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-02-19 10:00:00+00:00,2.02,2.13,1.28,3.55,2.2450,0.948349,4964.0,0.664855,-0.866025,-2.02,...,5.000000e-01,535.0,4.93,21.02,18.89,17.61,19.1300,1.409137,19.00,10.78
2026-02-19 10:30:00+00:00,4.93,2.02,2.13,1.28,2.5900,1.605013,5066.0,0.664855,-0.923880,4.93,...,3.826834e-01,674.0,0.15,19.00,21.02,18.89,20.7100,2.359449,23.93,13.30
2026-02-19 11:00:00+00:00,0.15,4.93,2.02,2.13,2.3075,1.970319,5181.0,0.664855,-0.965926,0.15,...,2.588190e-01,678.0,5.22,23.93,19.00,21.02,22.0075,2.450270,24.08,13.09
2026-02-19 11:30:00+00:00,5.22,0.15,4.93,2.02,3.0800,2.429719,5211.0,0.664855,-0.991445,5.22,...,1.305262e-01,825.0,0.60,24.08,23.93,19.00,24.0775,4.206236,29.30,15.83
2026-02-19 12:00:00+00:00,0.60,5.22,0.15,4.93,2.7250,2.722334,5152.0,0.664855,-1.000000,0.60,...,1.224647e-16,842.0,2.38,29.30,24.08,23.93,26.8025,3.240127,29.90,16.34

Taille du dataset : (19894, 67)

In [28]:
sorted(df_train.columns.to_list())

['abs_dtch_dt',
 'abs_dtch_lag_1',
 'abs_dtch_lag_2',
 'abs_dtch_lag_3',
 'abs_dtch_roll_mean_4h',
 'abs_dtch_roll_std_4h',
 'consommation',
 'cos_doy',
 'cos_hour',
 'dtch_dt',
 'dtch_lag_1',
 'dtch_lag_2',
 'dtch_lag_3',
 'dtch_roll_mean_4h',
 'dtch_roll_std_4h',
 'region_abs_dghi_dt',
 'region_altitude',
 'region_anomaly',
 'region_azimuth_cos',
 'region_azimuth_sin',
 'region_bhi',
 'region_bni',
 'region_clear_sky_bhi',
 'region_clear_sky_bni',
 'region_clear_sky_dhi',
 'region_clear_sky_ghi',
 'region_csi',
 'region_dghi_dt',
 'region_dghi_lag_1',
 'region_dghi_lag_2',
 'region_dghi_lag_3',
 'region_dghi_roll_mean_4h',
 'region_dghi_roll_std_4h',
 'region_dhi',
 'region_dnebulosite_dt',
 'region_dnebulosite_lag_1',
 'region_dnebulosite_lag_2',
 'region_dnebulosite_lag_3',
 'region_dnebulosite_roll_mean_4h',
 'region_dnebulosite_roll_std_4h',
 'region_ghi',
 'region_ghi_lag_1',
 'region_ghi_lag_2',
 'region_ghi_lag_3',
 'region_ghi_roll_mean_4h',
 'region_ghi_roll_std_4h',
 'region_humidite',
 'region_nebulosite',
 'region_nebulosite_lag_1',
 'region_nebulosite_lag_2',
 'region_nebulosite_lag_3',
 'region_nebulosite_roll_mean_4h',
 'region_nebulosite_roll_std_4h',
 'region_temperature',
 'region_toa',
 'region_vitesse_vent',
 'sin_doy',
 'sin_hour',
 'solaire',
 'target',
 'tch_lag_1',
 'tch_lag_2',
 'tch_lag_3',
 'tch_roll_mean_4h',
 'tch_roll_std_4h',
 'tch_solaire',
 'tco_solaire']

In [29]:
df_test.loc[df_test.region_anomaly ==1, ['region_ghi', 'solaire']]

                           region_ghi  solaire
datetime_utc
2025-01-01 09:30:00+00:00  105.607573    699.0
2025-01-01 10:00:00+00:00  119.847479    796.0
2025-01-01 10:30:00+00:00  134.171688    889.0
2025-01-01 11:00:00+00:00  142.243127    948.0
2025-01-01 11:30:00+00:00  143.225557    926.0
...                               ...      ...
2026-02-18 14:30:00+00:00  157.838896    942.0
2026-02-18 15:00:00+00:00  137.990656    800.0
2026-02-18 15:30:00+00:00  108.447894    568.0
2026-02-19 11:00:00+00:00  212.048109    678.0
2026-02-19 11:30:00+00:00  221.065796    825.0

[4555 rows x 2 columns]

In [34]:
df_train.loc[df_train.region_ghi > 0, ['tch_solaire','dtch_dt', 'abs_dtch_dt', 'tch_lag_1', 'dtch_lag_1', 'target']]

,tch_solaire,dtch_dt,abs_dtch_dt,tch_lag_1,dtch_lag_1,target
datetime_utc,,,,,,
2020-01-01 07:00:00+00:00,0.00,0.00,0.00,0.00,0.00,0.52
2020-01-01 07:30:00+00:00,0.52,0.52,0.52,0.00,0.00,4.70
2020-01-01 08:00:00+00:00,5.22,4.70,4.70,0.52,0.52,7.89
2020-01-01 08:30:00+00:00,13.11,7.89,7.89,5.22,4.70,8.95
2020-01-01 09:00:00+00:00,22.06,8.95,8.95,13.11,7.89,8.71
...,...,...,...,...,...,...
2023-12-31 14:00:00+00:00,7.15,-1.57,1.57,8.72,-1.04,2.09
2023-12-31 14:30:00+00:00,5.06,-2.09,2.09,7.15,-1.57,1.31
2023-12-31 15:00:00+00:00,3.75,-1.31,1.31,5.06,-2.09,1.70
2023-12-31 15:30:00+00:00,2.05,-1.70,1.70,3.75,-1.31,1.61
2023-12-31 16:00:00+00:00,0.44,-1.61,1.61,2.05,-1.70,0.44

In [31]:
df_train.loc[df_train.region_ghi > 0, ['region_ghi', 'region_dghi_dt','region_dghi_lag_1', 'region_dghi_lag_2']]

,region_ghi,region_dghi_dt,region_dghi_lag_1,region_dghi_lag_2
datetime_utc,,,,
2020-01-01 07:00:00+00:00,0.005586,0.005586,0.000000,0.000000
2020-01-01 07:30:00+00:00,9.671917,9.666331,0.005586,0.000000
2020-01-01 08:00:00+00:00,41.024514,31.352597,9.666331,0.005586
2020-01-01 08:30:00+00:00,76.905586,35.881072,31.352597,9.666331
2020-01-01 09:00:00+00:00,111.046611,34.141025,35.881072,31.352597
...,...,...,...,...
2023-12-31 14:00:00+00:00,56.679010,10.640746,3.259539,-3.256863
2023-12-31 14:30:00+00:00,49.358970,-7.320040,10.640746,3.259539
2023-12-31 15:00:00+00:00,33.053629,-16.305341,-7.320040,10.640746
2023-12-31 15:30:00+00:00,16.731665,-16.321964,-16.305341,-7.320040
2023-12-31 16:00:00+00:00,3.060252,-13.671413,-16.321964,-16.305341