In [1]:
# Chemin output
filepath_output = '/Projet_Moustafa_Datascience/aug25cds_variabilite/data/local_data/04_Features_engineering/output/'

In [2]:
# Gestion des chemins
from pathlib import Path

# Données et calculs
import pandas as pd
import numpy as np

# Dataviz
import matplotlib.pyplot as plt
%matplotlib inline

# Réduction de dimension
from sklearn.feature_selection import VarianceThreshold

In [3]:
# Lecture du fichier de données brutes 2020-2024 et affichage d'informations générales
# Chemin
filepath_2020_2024= Path("/Projet_Moustafa_Datascience/aug25cds_variabilite/data/local_data/02_Collecte_datasets/output/raw_2020_2024.csv")

# Charger le dataset
df_2020_2024 = pd.read_csv(filepath_2020_2024,
                           index_col='datetime_utc',
                           parse_dates=True)

# Afficher les premières lignes
display(df_2020_2024.head())

# Afficher les dimensions du dataset
print('Dimensions df_2020_2024 :', df_2020_2024.shape)

# Afficher les statistiques des variables numériques
display(df_2020_2024.describe())

# Afficher le type des colonnes, les valeurs manquantes
df_2020_2024.info()

C:\Users\mirai\AppData\Local\Temp\ipykernel_12156\2490691551.py:6: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020_2024 = pd.read_csv(filepath_2020_2024,

,Périmètre,Nature,Consommation,Solaire,Ech. physiques,Stockage batterie,Déstockage batterie,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2019-12-31 23:00:00+00:00,PACA,Données définitives,6123.0,0.0,3332.0,-,-,0.0,0.0,335.596867,...,29.440,57.600,3.230,1.620,5.700,86.880,2.720,1.220,51.750,100.000
2019-12-31 23:30:00+00:00,PACA,Données définitives,5907.0,0.0,2837.0,-,-,0.0,0.0,353.817769,...,24.785,56.165,3.345,1.565,4.635,84.455,2.760,1.405,54.215,98.790
2020-01-01 00:00:00+00:00,PACA,Données définitives,5724.0,0.0,2668.0,-,-,0.0,0.0,12.883689,...,20.130,54.730,3.460,1.510,3.570,82.030,2.800,1.590,56.680,97.580
2020-01-01 00:30:00+00:00,PACA,Données définitives,5749.0,0.0,2754.0,-,-,0.0,0.0,30.261125,...,10.340,54.250,3.650,1.435,3.040,79.380,2.675,1.635,33.325,96.065
2020-01-01 01:00:00+00:00,PACA,Données définitives,5700.0,0.0,2886.0,-,-,0.0,0.0,44.631373,...,0.550,53.770,3.840,1.360,2.510,76.730,2.550,1.680,9.970,94.550

Dimensions df_2020_2024 : (87696, 89)

,Consommation,Solaire,Ech. physiques,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,CRU_altitude,SEL_azimuth,SEL_altitude,SVT_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
count,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,...,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000,87696.000000
mean,4485.721048,301.790241,2362.531826,6.700169,16.873232,180.414164,0.332711,180.600596,0.334114,180.383371,...,52.330814,69.673134,15.387987,2.713704,46.548744,67.673899,14.864098,2.941427,51.525113,68.993747
std,855.835873,438.892803,862.312299,9.822056,23.957124,101.362763,34.060740,101.415049,33.843022,101.319389,...,35.749373,15.507962,8.317463,1.804534,38.648557,21.023569,8.860135,1.993310,37.500944,21.480904
min,1640.000000,0.000000,-615.000000,0.000000,0.000000,0.017255,-69.332104,0.001426,-68.919902,0.005349,...,0.000000,16.700000,-2.950000,0.010000,0.000000,12.460000,-5.060000,0.010000,0.000000,11.140000
25%,3852.000000,0.000000,1793.000000,0.000000,0.000000,90.222951,-25.625496,90.314566,-25.403531,90.048959,...,17.890000,58.488750,8.700000,1.310000,6.973750,51.510000,7.975000,1.300000,12.680000,52.710000
50%,4379.000000,3.000000,2351.000000,0.080000,0.200000,180.009202,0.614024,179.996787,0.677727,180.004222,...,49.475000,70.885000,14.430000,2.220000,38.785000,69.890000,14.100000,2.440000,50.645000,72.660000
75%,5051.000000,559.000000,2895.000000,12.180000,32.320000,270.809415,26.241474,270.866820,25.979124,270.771208,...,91.290000,81.690000,21.260000,3.745000,90.201250,85.330000,21.035000,4.175000,93.141250,87.155000
max,8044.000000,1942.000000,5657.000000,62.320000,91.350000,359.990157,69.288364,359.969741,68.886867,359.995370,...,100.000000,100.000000,39.670000,13.020000,100.000000,100.000000,42.970000,11.240000,100.000000,100.000000

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 87696 entries, 2019-12-31 23:00:00+00:00 to 2024-12-31 22:30:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Périmètre            87696 non-null  object
 1   Nature               87696 non-null  object
 2   Consommation         87696 non-null  float64
 3   Solaire              87696 non-null  float64
 4   Ech. physiques       87696 non-null  float64
 5   Stockage batterie    87696 non-null  object
 6   Déstockage batterie  87696 non-null  object
 7   TCO Solaire (%)      87696 non-null  float64
 8   TCH Solaire (%)      87696 non-null  float64
 9   CRU_azimuth          87696 non-null  float64
 10  CRU_altitude         87696 non-null  float64
 11  SEL_azimuth          87696 non-null  float64
 12  SEL_altitude         87696 non-null  float64
 13  SVT_azimuth          87696 non-null  float64
 14  SVT_altitude         87696 non-null  float64
 15  BRA_azimuth          87696 non-null  float64
 16  BRA_altitude         87696 non-null  float64
 17  EYG_azimuth          87696 non-null  float64
 18  EYG_altitude         87696 non-null  float64
 19  CRU_TOA              87696 non-null  float64
 20  CRU_Clear sky GHI    87696 non-null  float64
 21  CRU_Clear sky BHI    87696 non-null  float64
 22  CRU_Clear sky DHI    87696 non-null  float64
 23  CRU_Clear sky BNI    87696 non-null  float64
 24  CRU_GHI              87696 non-null  float64
 25  CRU_BHI              87696 non-null  float64
 26  CRU_DHI              87696 non-null  float64
 27  CRU_BNI              87696 non-null  float64
 28  CRU_Reliability      87696 non-null  float64
 29  SEL_TOA              87696 non-null  float64
 30  SEL_Clear sky GHI    87696 non-null  float64
 31  SEL_Clear sky BHI    87696 non-null  float64
 32  SEL_Clear sky DHI    87696 non-null  float64
 33  SEL_Clear sky BNI    87696 non-null  float64
 34  SEL_GHI              87696 non-null  float64
 35  SEL_BHI              87696 non-null  float64
 36  SEL_DHI              87696 non-null  float64
 37  SEL_BNI              87696 non-null  float64
 38  SEL_Reliability      87696 non-null  float64
 39  SVT_TOA              87696 non-null  float64
 40  SVT_Clear sky GHI    87696 non-null  float64
 41  SVT_Clear sky BHI    87696 non-null  float64
 42  SVT_Clear sky DHI    87696 non-null  float64
 43  SVT_Clear sky BNI    87696 non-null  float64
 44  SVT_GHI              87696 non-null  float64
 45  SVT_BHI              87696 non-null  float64
 46  SVT_DHI              87696 non-null  float64
 47  SVT_BNI              87696 non-null  float64
 48  SVT_Reliability      87696 non-null  float64
 49  BRA_TOA              87696 non-null  float64
 50  BRA_Clear sky GHI    87696 non-null  float64
 51  BRA_Clear sky BHI    87696 non-null  float64
 52  BRA_Clear sky DHI    87696 non-null  float64
 53  BRA_Clear sky BNI    87696 non-null  float64
 54  BRA_GHI              87696 non-null  float64
 55  BRA_BHI              87696 non-null  float64
 56  BRA_DHI              87696 non-null  float64
 57  BRA_BNI              87696 non-null  float64
 58  BRA_Reliability      87696 non-null  float64
 59  EYG_TOA              87696 non-null  float64
 60  EYG_Clear sky GHI    87696 non-null  float64
 61  EYG_Clear sky BHI    87696 non-null  float64
 62  EYG_Clear sky DHI    87696 non-null  float64
 63  EYG_Clear sky BNI    87696 non-null  float64
 64  EYG_GHI              87696 non-null  float64
 65  EYG_BHI              87696 non-null  float64
 66  EYG_DHI              87696 non-null  float64
 67  EYG_BNI              87696 non-null  float64
 68  EYG_Reliability      87696 non-null  float64
 69  CRU_Temperature      87696 non-null  float64
 70  CRU_Vitesse_Vent     87696 non-null  float64
 71  CRU_Nebulosite       87696 non-null  float64
 72  CRU_Humidite         87696 non-null  float64
 73  SEL_Temperature      87696 non-null  float64
 74  SEL_Vitesse_Vent     87696 non-null  float64
 75  SEL_Nebulosite       87696 non-null  float64
 76  SEL_Humidite         87696 non-null  float64
 77  SVT_Temperature      87696 non-null  float64
 78  SVT_Vitesse_Vent     87696 non-null  float64
 79  SVT_Nebulosite       87696 non-null  float64
 80  SVT_Humidite         87696 non-null  float64
 81  BRA_Temperature      87696 non-null  float64
 82  BRA_Vitesse_Vent     87696 non-null  float64
 83  BRA_Nebulosite       87696 non-null  float64
 84  BRA_Humidite         87696 non-null  float64
 85  EYG_Temperature      87696 non-null  float64
 86  EYG_Vitesse_Vent     87696 non-null  float64
 87  EYG_Nebulosite       87696 non-null  float64
 88  EYG_Humidite         87696 non-null  float64
dtypes: float64(85), object(4)
memory usage: 60.2+ MB

In [4]:
# Lecture du fichier de données brutes 2025-2026 et affichage d'informations générales
# Chemin
filepath_2025_2026= Path("/Projet_Moustafa_Datascience/aug25cds_variabilite/data/local_data/02_Collecte_datasets/output/raw_2025_2026.csv")

# Charger le dataset
df_2025_2026 = pd.read_csv(filepath_2025_2026,
                           index_col='datetime_utc',
                           parse_dates=True)

# Afficher les premières lignes
display(df_2025_2026.head())

# Afficher les dimensions du dataset
print('Dimensions df_2025_2026 :', df_2025_2026.shape)

# Afficher le type des colonnes, les valeurs manquantes
df_2025_2026.info() # 'TCO Solaire (%)' est de type 'object'

df_pbl = df_2025_2026.loc[df_2025_2026['TCO Solaire (%)'] == 'ND']
print("\nNombre de lignes où 'TCO Solaire (%)' vaut 'ND' :", len(df_pbl))
print(f"Nombre de valeur de 'TCH Solaire (%)' correspondante : {df_pbl['TCH Solaire (%)'].nunique()} {df_pbl['TCH Solaire (%)'].unique()}")

# On remplace 'ND' par 0.0
df_2025_2026.loc[df_2025_2026['TCO Solaire (%)'] == 'ND'] = 0.0

# On converti le type de la colonne
df_2025_2026['TCO Solaire (%)'] = df_2025_2026['TCO Solaire (%)'].astype(float, errors="raise")

# On vérifie
df_2025_2026.info()

C:\Users\mirai\AppData\Local\Temp\ipykernel_12156\555355089.py:6: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025_2026 = pd.read_csv(filepath_2025_2026,

,Périmètre,Nature,Consommation,Solaire,Ech. physiques,Stockage batterie,Déstockage batterie,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-12-31 23:00:00+00:00,PACA,Données temps réel,5583.0,0.0,4293.0,0.0,0.0,0.0,0.0,335.434321,...,52.460,84.21,5.60,0.16,83.520,87.540,3.310,1.010,81.11,93.650
2024-12-31 23:30:00+00:00,PACA,Données temps réel,5430.0,0.0,4290.0,0.0,0.0,0.0,0.0,353.592974,...,49.245,83.45,5.45,0.11,85.310,88.275,3.285,1.005,88.77,93.500
2025-01-01 00:00:00+00:00,PACA,Données temps réel,5277.0,0.0,4321.0,0.0,0.0,0.0,0.0,12.621973,...,46.030,82.69,5.30,0.06,87.100,89.010,3.260,1.000,96.43,93.350
2025-01-01 00:30:00+00:00,PACA,Données temps réel,5314.0,0.0,4380.0,0.0,0.0,0.0,0.0,30.001046,...,45.480,81.73,5.19,0.14,87.325,89.245,3.180,1.000,97.87,93.565
2025-01-01 01:00:00+00:00,PACA,Données temps réel,5262.0,0.0,4452.0,0.0,0.0,0.0,0.0,44.396127,...,44.930,80.77,5.08,0.22,87.550,89.480,3.100,1.000,99.31,93.780

Dimensions df_2025_2026 : (19901, 89)
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 19901 entries, 2024-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Périmètre            19901 non-null  object
 1   Nature               19901 non-null  object
 2   Consommation         19901 non-null  float64
 3   Solaire              19901 non-null  float64
 4   Ech. physiques       19901 non-null  float64
 5   Stockage batterie    19901 non-null  float64
 6   Déstockage batterie  19901 non-null  float64
 7   TCO Solaire (%)      19901 non-null  object
 8   TCH Solaire (%)      19901 non-null  float64
 9   CRU_azimuth          19901 non-null  float64
 10  CRU_altitude         19901 non-null  float64
 11  SEL_azimuth          19901 non-null  float64
 12  SEL_altitude         19901 non-null  float64
 13  SVT_azimuth          19901 non-null  float64
 14  SVT_altitude         19901 non-null  float64
 15  BRA_azimuth          19901 non-null  float64
 16  BRA_altitude         19901 non-null  float64
 17  EYG_azimuth          19901 non-null  float64
 18  EYG_altitude         19901 non-null  float64
 19  CRU_TOA              19901 non-null  float64
 20  CRU_Clear sky GHI    19901 non-null  float64
 21  CRU_Clear sky BHI    19901 non-null  float64
 22  CRU_Clear sky DHI    19901 non-null  float64
 23  CRU_Clear sky BNI    19901 non-null  float64
 24  CRU_GHI              19901 non-null  float64
 25  CRU_BHI              19901 non-null  float64
 26  CRU_DHI              19901 non-null  float64
 27  CRU_BNI              19901 non-null  float64
 28  CRU_Reliability      19901 non-null  float64
 29  SEL_TOA              19901 non-null  float64
 30  SEL_Clear sky GHI    19901 non-null  float64
 31  SEL_Clear sky BHI    19901 non-null  float64
 32  SEL_Clear sky DHI    19901 non-null  float64
 33  SEL_Clear sky BNI    19901 non-null  float64
 34  SEL_GHI              19901 non-null  float64
 35  SEL_BHI              19901 non-null  float64
 36  SEL_DHI              19901 non-null  float64
 37  SEL_BNI              19901 non-null  float64
 38  SEL_Reliability      19901 non-null  float64
 39  SVT_TOA              19901 non-null  float64
 40  SVT_Clear sky GHI    19901 non-null  float64
 41  SVT_Clear sky BHI    19901 non-null  float64
 42  SVT_Clear sky DHI    19901 non-null  float64
 43  SVT_Clear sky BNI    19901 non-null  float64
 44  SVT_GHI              19901 non-null  float64
 45  SVT_BHI              19901 non-null  float64
 46  SVT_DHI              19901 non-null  float64
 47  SVT_BNI              19901 non-null  float64
 48  SVT_Reliability      19901 non-null  float64
 49  BRA_TOA              19901 non-null  float64
 50  BRA_Clear sky GHI    19901 non-null  float64
 51  BRA_Clear sky BHI    19901 non-null  float64
 52  BRA_Clear sky DHI    19901 non-null  float64
 53  BRA_Clear sky BNI    19901 non-null  float64
 54  BRA_GHI              19901 non-null  float64
 55  BRA_BHI              19901 non-null  float64
 56  BRA_DHI              19901 non-null  float64
 57  BRA_BNI              19901 non-null  float64
 58  BRA_Reliability      19901 non-null  float64
 59  EYG_TOA              19901 non-null  float64
 60  EYG_Clear sky GHI    19901 non-null  float64
 61  EYG_Clear sky BHI    19901 non-null  float64
 62  EYG_Clear sky DHI    19901 non-null  float64
 63  EYG_Clear sky BNI    19901 non-null  float64
 64  EYG_GHI              19901 non-null  float64
 65  EYG_BHI              19901 non-null  float64
 66  EYG_DHI              19901 non-null  float64
 67  EYG_BNI              19901 non-null  float64
 68  EYG_Reliability      19901 non-null  float64
 69  CRU_Temperature      19901 non-null  float64
 70  CRU_Vitesse_Vent     19901 non-null  float64
 71  CRU_Nebulosite       19901 non-null  float64
 72  CRU_Humidite         19901 non-null  float64
 73  SEL_Temperature      19901 non-null  float64
 74  SEL_Vitesse_Vent     19901 non-null  float64
 75  SEL_Nebulosite       19901 non-null  float64
 76  SEL_Humidite         19901 non-null  float64
 77  SVT_Temperature      19901 non-null  float64
 78  SVT_Vitesse_Vent     19901 non-null  float64
 79  SVT_Nebulosite       19901 non-null  float64
 80  SVT_Humidite         19901 non-null  float64
 81  BRA_Temperature      19901 non-null  float64
 82  BRA_Vitesse_Vent     19901 non-null  float64
 83  BRA_Nebulosite       19901 non-null  float64
 84  BRA_Humidite         19901 non-null  float64
 85  EYG_Temperature      19901 non-null  float64
 86  EYG_Vitesse_Vent     19901 non-null  float64
 87  EYG_Nebulosite       19901 non-null  float64
 88  EYG_Humidite         19901 non-null  float64
dtypes: float64(86), object(3)
memory usage: 13.7+ MB

Nombre de lignes où 'TCO Solaire (%)' vaut 'ND' : 64
Nombre de valeur de 'TCH Solaire (%)' correspondante : 1 [0.]
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 19901 entries, 2024-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Périmètre            19901 non-null  object
 1   Nature               19901 non-null  object
 2   Consommation         19901 non-null  float64
 3   Solaire              19901 non-null  float64
 4   Ech. physiques       19901 non-null  float64
 5   Stockage batterie    19901 non-null  float64
 6   Déstockage batterie  19901 non-null  float64
 7   TCO Solaire (%)      19901 non-null  float64
 8   TCH Solaire (%)      19901 non-null  float64
 9   CRU_azimuth          19901 non-null  float64
 10  CRU_altitude         19901 non-null  float64
 11  SEL_azimuth          19901 non-null  float64
 12  SEL_altitude         19901 non-null  float64
 13  SVT_azimuth          19901 non-null  float64
 14  SVT_altitude         19901 non-null  float64
 15  BRA_azimuth          19901 non-null  float64
 16  BRA_altitude         19901 non-null  float64
 17  EYG_azimuth          19901 non-null  float64
 18  EYG_altitude         19901 non-null  float64
 19  CRU_TOA              19901 non-null  float64
 20  CRU_Clear sky GHI    19901 non-null  float64
 21  CRU_Clear sky BHI    19901 non-null  float64
 22  CRU_Clear sky DHI    19901 non-null  float64
 23  CRU_Clear sky BNI    19901 non-null  float64
 24  CRU_GHI              19901 non-null  float64
 25  CRU_BHI              19901 non-null  float64
 26  CRU_DHI              19901 non-null  float64
 27  CRU_BNI              19901 non-null  float64
 28  CRU_Reliability      19901 non-null  float64
 29  SEL_TOA              19901 non-null  float64
 30  SEL_Clear sky GHI    19901 non-null  float64
 31  SEL_Clear sky BHI    19901 non-null  float64
 32  SEL_Clear sky DHI    19901 non-null  float64
 33  SEL_Clear sky BNI    19901 non-null  float64
 34  SEL_GHI              19901 non-null  float64
 35  SEL_BHI              19901 non-null  float64
 36  SEL_DHI              19901 non-null  float64
 37  SEL_BNI              19901 non-null  float64
 38  SEL_Reliability      19901 non-null  float64
 39  SVT_TOA              19901 non-null  float64
 40  SVT_Clear sky GHI    19901 non-null  float64
 41  SVT_Clear sky BHI    19901 non-null  float64
 42  SVT_Clear sky DHI    19901 non-null  float64
 43  SVT_Clear sky BNI    19901 non-null  float64
 44  SVT_GHI              19901 non-null  float64
 45  SVT_BHI              19901 non-null  float64
 46  SVT_DHI              19901 non-null  float64
 47  SVT_BNI              19901 non-null  float64
 48  SVT_Reliability      19901 non-null  float64
 49  BRA_TOA              19901 non-null  float64
 50  BRA_Clear sky GHI    19901 non-null  float64
 51  BRA_Clear sky BHI    19901 non-null  float64
 52  BRA_Clear sky DHI    19901 non-null  float64
 53  BRA_Clear sky BNI    19901 non-null  float64
 54  BRA_GHI              19901 non-null  float64
 55  BRA_BHI              19901 non-null  float64
 56  BRA_DHI              19901 non-null  float64
 57  BRA_BNI              19901 non-null  float64
 58  BRA_Reliability      19901 non-null  float64
 59  EYG_TOA              19901 non-null  float64
 60  EYG_Clear sky GHI    19901 non-null  float64
 61  EYG_Clear sky BHI    19901 non-null  float64
 62  EYG_Clear sky DHI    19901 non-null  float64
 63  EYG_Clear sky BNI    19901 non-null  float64
 64  EYG_GHI              19901 non-null  float64
 65  EYG_BHI              19901 non-null  float64
 66  EYG_DHI              19901 non-null  float64
 67  EYG_BNI              19901 non-null  float64
 68  EYG_Reliability      19901 non-null  float64
 69  CRU_Temperature      19901 non-null  float64
 70  CRU_Vitesse_Vent     19901 non-null  float64
 71  CRU_Nebulosite       19901 non-null  float64
 72  CRU_Humidite         19901 non-null  float64
 73  SEL_Temperature      19901 non-null  float64
 74  SEL_Vitesse_Vent     19901 non-null  float64
 75  SEL_Nebulosite       19901 non-null  float64
 76  SEL_Humidite         19901 non-null  float64
 77  SVT_Temperature      19901 non-null  float64
 78  SVT_Vitesse_Vent     19901 non-null  float64
 79  SVT_Nebulosite       19901 non-null  float64
 80  SVT_Humidite         19901 non-null  float64
 81  BRA_Temperature      19901 non-null  float64
 82  BRA_Vitesse_Vent     19901 non-null  float64
 83  BRA_Nebulosite       19901 non-null  float64
 84  BRA_Humidite         19901 non-null  float64
 85  EYG_Temperature      19901 non-null  float64
 86  EYG_Vitesse_Vent     19901 non-null  float64
 87  EYG_Nebulosite       19901 non-null  float64
 88  EYG_Humidite         19901 non-null  float64
dtypes: float64(87), object(2)
memory usage: 13.7+ MB

In [5]:
df = pd.concat([df_2020_2024, df_2025_2026])

# Afficher les premières lignes
display(df.head())

# Afficher les dimensions du dataset
print('Dimensions df :', df.shape, '\n')
print('Taille de df_2020_2024 + taille de df_2025_2026 = taille de df ?',
      (df_2020_2024.shape[0] + df_2025_2026.shape[0] == df.shape[0]) and
      (df_2020_2024.shape[1] == df.shape[1]) and (df_2025_2026.shape[1] == df.shape[1]))

df.info()

,Périmètre,Nature,Consommation,Solaire,Ech. physiques,Stockage batterie,Déstockage batterie,TCO Solaire (%),TCH Solaire (%),CRU_azimuth,...,SVT_Nebulosite,SVT_Humidite,BRA_Temperature,BRA_Vitesse_Vent,BRA_Nebulosite,BRA_Humidite,EYG_Temperature,EYG_Vitesse_Vent,EYG_Nebulosite,EYG_Humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2019-12-31 23:00:00+00:00,PACA,Données définitives,6123.0,0.0,3332.0,-,-,0.0,0.0,335.596867,...,29.440,57.600,3.230,1.620,5.700,86.880,2.720,1.220,51.750,100.000
2019-12-31 23:30:00+00:00,PACA,Données définitives,5907.0,0.0,2837.0,-,-,0.0,0.0,353.817769,...,24.785,56.165,3.345,1.565,4.635,84.455,2.760,1.405,54.215,98.790
2020-01-01 00:00:00+00:00,PACA,Données définitives,5724.0,0.0,2668.0,-,-,0.0,0.0,12.883689,...,20.130,54.730,3.460,1.510,3.570,82.030,2.800,1.590,56.680,97.580
2020-01-01 00:30:00+00:00,PACA,Données définitives,5749.0,0.0,2754.0,-,-,0.0,0.0,30.261125,...,10.340,54.250,3.650,1.435,3.040,79.380,2.675,1.635,33.325,96.065
2020-01-01 01:00:00+00:00,PACA,Données définitives,5700.0,0.0,2886.0,-,-,0.0,0.0,44.631373,...,0.550,53.770,3.840,1.360,2.510,76.730,2.550,1.680,9.970,94.550

Dimensions df : (107597, 89)

Taille de df_2020_2024 + taille de df_2025_2026 = taille de df ? True
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 107597 entries, 2019-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Périmètre            107597 non-null  object
 1   Nature               107597 non-null  object
 2   Consommation         107597 non-null  float64
 3   Solaire              107597 non-null  float64
 4   Ech. physiques       107597 non-null  float64
 5   Stockage batterie    107597 non-null  object
 6   Déstockage batterie  107597 non-null  object
 7   TCO Solaire (%)      107597 non-null  float64
 8   TCH Solaire (%)      107597 non-null  float64
 9   CRU_azimuth          107597 non-null  float64
 10  CRU_altitude         107597 non-null  float64
 11  SEL_azimuth          107597 non-null  float64
 12  SEL_altitude         107597 non-null  float64
 13  SVT_azimuth          107597 non-null  float64
 14  SVT_altitude         107597 non-null  float64
 15  BRA_azimuth          107597 non-null  float64
 16  BRA_altitude         107597 non-null  float64
 17  EYG_azimuth          107597 non-null  float64
 18  EYG_altitude         107597 non-null  float64
 19  CRU_TOA              107597 non-null  float64
 20  CRU_Clear sky GHI    107597 non-null  float64
 21  CRU_Clear sky BHI    107597 non-null  float64
 22  CRU_Clear sky DHI    107597 non-null  float64
 23  CRU_Clear sky BNI    107597 non-null  float64
 24  CRU_GHI              107597 non-null  float64
 25  CRU_BHI              107597 non-null  float64
 26  CRU_DHI              107597 non-null  float64
 27  CRU_BNI              107597 non-null  float64
 28  CRU_Reliability      107597 non-null  float64
 29  SEL_TOA              107597 non-null  float64
 30  SEL_Clear sky GHI    107597 non-null  float64
 31  SEL_Clear sky BHI    107597 non-null  float64
 32  SEL_Clear sky DHI    107597 non-null  float64
 33  SEL_Clear sky BNI    107597 non-null  float64
 34  SEL_GHI              107597 non-null  float64
 35  SEL_BHI              107597 non-null  float64
 36  SEL_DHI              107597 non-null  float64
 37  SEL_BNI              107597 non-null  float64
 38  SEL_Reliability      107597 non-null  float64
 39  SVT_TOA              107597 non-null  float64
 40  SVT_Clear sky GHI    107597 non-null  float64
 41  SVT_Clear sky BHI    107597 non-null  float64
 42  SVT_Clear sky DHI    107597 non-null  float64
 43  SVT_Clear sky BNI    107597 non-null  float64
 44  SVT_GHI              107597 non-null  float64
 45  SVT_BHI              107597 non-null  float64
 46  SVT_DHI              107597 non-null  float64
 47  SVT_BNI              107597 non-null  float64
 48  SVT_Reliability      107597 non-null  float64
 49  BRA_TOA              107597 non-null  float64
 50  BRA_Clear sky GHI    107597 non-null  float64
 51  BRA_Clear sky BHI    107597 non-null  float64
 52  BRA_Clear sky DHI    107597 non-null  float64
 53  BRA_Clear sky BNI    107597 non-null  float64
 54  BRA_GHI              107597 non-null  float64
 55  BRA_BHI              107597 non-null  float64
 56  BRA_DHI              107597 non-null  float64
 57  BRA_BNI              107597 non-null  float64
 58  BRA_Reliability      107597 non-null  float64
 59  EYG_TOA              107597 non-null  float64
 60  EYG_Clear sky GHI    107597 non-null  float64
 61  EYG_Clear sky BHI    107597 non-null  float64
 62  EYG_Clear sky DHI    107597 non-null  float64
 63  EYG_Clear sky BNI    107597 non-null  float64
 64  EYG_GHI              107597 non-null  float64
 65  EYG_BHI              107597 non-null  float64
 66  EYG_DHI              107597 non-null  float64
 67  EYG_BNI              107597 non-null  float64
 68  EYG_Reliability      107597 non-null  float64
 69  CRU_Temperature      107597 non-null  float64
 70  CRU_Vitesse_Vent     107597 non-null  float64
 71  CRU_Nebulosite       107597 non-null  float64
 72  CRU_Humidite         107597 non-null  float64
 73  SEL_Temperature      107597 non-null  float64
 74  SEL_Vitesse_Vent     107597 non-null  float64
 75  SEL_Nebulosite       107597 non-null  float64
 76  SEL_Humidite         107597 non-null  float64
 77  SVT_Temperature      107597 non-null  float64
 78  SVT_Vitesse_Vent     107597 non-null  float64
 79  SVT_Nebulosite       107597 non-null  float64
 80  SVT_Humidite         107597 non-null  float64
 81  BRA_Temperature      107597 non-null  float64
 82  BRA_Vitesse_Vent     107597 non-null  float64
 83  BRA_Nebulosite       107597 non-null  float64
 84  BRA_Humidite         107597 non-null  float64
 85  EYG_Temperature      107597 non-null  float64
 86  EYG_Vitesse_Vent     107597 non-null  float64
 87  EYG_Nebulosite       107597 non-null  float64
 88  EYG_Humidite         107597 non-null  float64
dtypes: float64(85), object(4)
memory usage: 73.9+ MB

In [6]:
# Normalisation du nom des colonnes (minuscules, pas d'espace, pas de caractères spéciaux autre que '_')

# Récupération du nom des colunnes
nom_cols = df.columns

# Création d'une fonction pour normaliser le nom des colonnes
def clean_name(name):
    resultat = name.lower()
    resultat = resultat.replace('(', '')
    resultat = resultat.replace(')', '')
    resultat = resultat.replace('%', '')
    resultat = resultat.replace('.', '')
    resultat = resultat.strip()
    resultat = resultat.replace(' ', '_')
    resultat = resultat.replace('é', 'e')
    resultat = resultat.replace('è', 'e')
    return resultat

# Initialisation d'un dictionnaire
# les clés seront les noms initiaux
# les valeurs les noms normalisés
dico = {}

# Remplir le dictionnaire
for nom in nom_cols:
    dico[nom] = clean_name(nom)

# Normaliser le nom des colonnes
df = df.rename(columns=dico)
print(df.info())
df.tail()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 107597 entries, 2019-12-31 23:00:00+00:00 to 2026-02-19 13:00:00+00:00
Data columns (total 89 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   perimetre            107597 non-null  object
 1   nature               107597 non-null  object
 2   consommation         107597 non-null  float64
 3   solaire              107597 non-null  float64
 4   ech_physiques        107597 non-null  float64
 5   stockage_batterie    107597 non-null  object
 6   destockage_batterie  107597 non-null  object
 7   tco_solaire          107597 non-null  float64
 8   tch_solaire          107597 non-null  float64
 9   cru_azimuth          107597 non-null  float64
 10  cru_altitude         107597 non-null  float64
 11  sel_azimuth          107597 non-null  float64
 12  sel_altitude         107597 non-null  float64
 13  svt_azimuth          107597 non-null  float64
 14  svt_altitude         107597 non-null  float64
 15  bra_azimuth          107597 non-null  float64
 16  bra_altitude         107597 non-null  float64
 17  eyg_azimuth          107597 non-null  float64
 18  eyg_altitude         107597 non-null  float64
 19  cru_toa              107597 non-null  float64
 20  cru_clear_sky_ghi    107597 non-null  float64
 21  cru_clear_sky_bhi    107597 non-null  float64
 22  cru_clear_sky_dhi    107597 non-null  float64
 23  cru_clear_sky_bni    107597 non-null  float64
 24  cru_ghi              107597 non-null  float64
 25  cru_bhi              107597 non-null  float64
 26  cru_dhi              107597 non-null  float64
 27  cru_bni              107597 non-null  float64
 28  cru_reliability      107597 non-null  float64
 29  sel_toa              107597 non-null  float64
 30  sel_clear_sky_ghi    107597 non-null  float64
 31  sel_clear_sky_bhi    107597 non-null  float64
 32  sel_clear_sky_dhi    107597 non-null  float64
 33  sel_clear_sky_bni    107597 non-null  float64
 34  sel_ghi              107597 non-null  float64
 35  sel_bhi              107597 non-null  float64
 36  sel_dhi              107597 non-null  float64
 37  sel_bni              107597 non-null  float64
 38  sel_reliability      107597 non-null  float64
 39  svt_toa              107597 non-null  float64
 40  svt_clear_sky_ghi    107597 non-null  float64
 41  svt_clear_sky_bhi    107597 non-null  float64
 42  svt_clear_sky_dhi    107597 non-null  float64
 43  svt_clear_sky_bni    107597 non-null  float64
 44  svt_ghi              107597 non-null  float64
 45  svt_bhi              107597 non-null  float64
 46  svt_dhi              107597 non-null  float64
 47  svt_bni              107597 non-null  float64
 48  svt_reliability      107597 non-null  float64
 49  bra_toa              107597 non-null  float64
 50  bra_clear_sky_ghi    107597 non-null  float64
 51  bra_clear_sky_bhi    107597 non-null  float64
 52  bra_clear_sky_dhi    107597 non-null  float64
 53  bra_clear_sky_bni    107597 non-null  float64
 54  bra_ghi              107597 non-null  float64
 55  bra_bhi              107597 non-null  float64
 56  bra_dhi              107597 non-null  float64
 57  bra_bni              107597 non-null  float64
 58  bra_reliability      107597 non-null  float64
 59  eyg_toa              107597 non-null  float64
 60  eyg_clear_sky_ghi    107597 non-null  float64
 61  eyg_clear_sky_bhi    107597 non-null  float64
 62  eyg_clear_sky_dhi    107597 non-null  float64
 63  eyg_clear_sky_bni    107597 non-null  float64
 64  eyg_ghi              107597 non-null  float64
 65  eyg_bhi              107597 non-null  float64
 66  eyg_dhi              107597 non-null  float64
 67  eyg_bni              107597 non-null  float64
 68  eyg_reliability      107597 non-null  float64
 69  cru_temperature      107597 non-null  float64
 70  cru_vitesse_vent     107597 non-null  float64
 71  cru_nebulosite       107597 non-null  float64
 72  cru_humidite         107597 non-null  float64
 73  sel_temperature      107597 non-null  float64
 74  sel_vitesse_vent     107597 non-null  float64
 75  sel_nebulosite       107597 non-null  float64
 76  sel_humidite         107597 non-null  float64
 77  svt_temperature      107597 non-null  float64
 78  svt_vitesse_vent     107597 non-null  float64
 79  svt_nebulosite       107597 non-null  float64
 80  svt_humidite         107597 non-null  float64
 81  bra_temperature      107597 non-null  float64
 82  bra_vitesse_vent     107597 non-null  float64
 83  bra_nebulosite       107597 non-null  float64
 84  bra_humidite         107597 non-null  float64
 85  eyg_temperature      107597 non-null  float64
 86  eyg_vitesse_vent     107597 non-null  float64
 87  eyg_nebulosite       107597 non-null  float64
 88  eyg_humidite         107597 non-null  float64
dtypes: float64(85), object(4)
memory usage: 73.9+ MB
None

,perimetre,nature,consommation,solaire,ech_physiques,stockage_batterie,destockage_batterie,tco_solaire,tch_solaire,cru_azimuth,...,svt_nebulosite,svt_humidite,bra_temperature,bra_vitesse_vent,bra_nebulosite,bra_humidite,eyg_temperature,eyg_vitesse_vent,eyg_nebulosite,eyg_humidite
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2026-02-19 11:00:00+00:00,PACA,Données temps réel,5181.0,678.0,3030.0,0.0,0.0,13.09,24.08,165.120233,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 11:30:00+00:00,PACA,Données temps réel,5211.0,825.0,2917.0,0.0,0.0,15.83,29.30,173.922880,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 12:00:00+00:00,PACA,Données temps réel,5152.0,842.0,2854.0,0.0,0.0,16.34,29.90,182.864978,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 12:30:00+00:00,PACA,Données temps réel,5177.0,909.0,2833.0,0.0,0.0,17.56,32.28,191.743652,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4
2026-02-19 13:00:00+00:00,PACA,Données temps réel,5060.0,726.0,2884.0,0.0,0.0,14.35,25.78,200.367731,...,66.73,97.92,9.15,1.75,25.58,100.0,9.81,1.6,35.96,99.4

In [7]:
# Séparation train - valid - test
date_debut_train = '2019-12-31'
date_fin_train = '2022-12-31'
date_debut_valid = '2023-01-01'
date_fin_valid = '2024-12-31'
date_debut_test = '2025-01-01'
date_fin_test = '2026-12-31'

df_train = df[date_debut_train : date_fin_train] # 2020, 2021, 2022, 2023
df_valid = df[date_debut_valid : date_fin_valid] # 2024
df_test = df[date_debut_test : date_fin_test] # 2025

# Vu les NaN qui seraient introduits par le calcul des lags,
# on calculera les nouvelles variables sur df
# (pour le choix des colonnes à supprimer, on se base sur df_train)

print(f"df_train commence le {df_train.index[0]} et s'arrête le {df_train.index[-1]}")
print(f"df_valid commence le {df_valid.index[0]} et s'arrête le {df_valid.index[-1]}")
print(f"df_test commence le {df_test.index[0]} et s'arrête le {df_test.index[-1]}")

df_train commence le 2019-12-31 23:00:00+00:00 et s'arrête le 2022-12-31 23:30:00+00:00
df_valid commence le 2023-01-01 00:00:00+00:00 et s'arrête le 2024-12-31 23:30:00+00:00
df_test commence le 2025-01-01 00:00:00+00:00 et s'arrête le 2026-02-19 13:00:00+00:00

In [8]:
# Etude des variables de type object
col_object = df_train.select_dtypes(include=['object']).columns

for col in col_object:
    print(f'{col} : {df_train[col].nunique()} valeurs différentes {df_train[col].unique()}')

perimetre : 1 valeurs différentes ['PACA']
nature : 1 valeurs différentes ['Données définitives']
stockage_batterie : 4 valeurs différentes ['-' '0' '0.0' 0.0]
destockage_batterie : 4 valeurs différentes ['-' '0' '0.0' 0.0]

In [9]:
# Les variables de type object ne transportent pas d'information pouvant être utile à notre problématique
df_train = df_train.drop(col_object, axis=1)
df_valid = df_valid.drop(col_object, axis=1)
df_test = df_test.drop(col_object, axis=1)

# On les supprimera du dataset consolidé
# On crée une liste des variables à supprimer
colonnes_a_supprimer = list(col_object)

In [10]:
# Trouver les variables explicatives qui ont une variance inférieure à 0.01
sel = VarianceThreshold(threshold=0.01)
sel.fit(df_train)

# Afficher les variables concernées
mask = sel.get_support()
print("Variables de faible variance :", df_train.columns[~mask])

Variables de faible variance : Index(['cru_reliability', 'sel_reliability', 'svt_reliability',
       'bra_reliability', 'eyg_reliability'],
      dtype='object')

In [11]:
# On supprime les variables dont la variance est trop faible
new_colonnes_a_supprimer = list(df_train.columns[~mask])
print(new_colonnes_a_supprimer)

['cru_reliability', 'sel_reliability', 'svt_reliability', 'bra_reliability', 'eyg_reliability']

In [12]:
# La variable 'ech_physiques' correspond aux flux nets d'électricité échangés avec les zones voisines
# Elle ne concerne pas notre problématique
new_colonnes_a_supprimer.extend(['ech_physiques'])

In [13]:
# On a fini d'identifier les colonnes à supprimer à partir de df_train
# On applique à df
print(f"Taille de df_train avant supression des colonnes : {df_train.shape}")
df_train = df_train.drop(new_colonnes_a_supprimer, axis=1)
df_valid = df_valid.drop(new_colonnes_a_supprimer, axis=1)
df_test = df_test.drop(new_colonnes_a_supprimer, axis=1)
print(f"Taille de df_train après supression des colonnes : {df_train.shape}")

Taille de df_train avant supression des colonnes : (52610, 85)
Taille de df_train après supression des colonnes : (52610, 79)

In [14]:
# Construction de la variable cible :
# on calcule la variation absolue de `tch_solaire` entre t et t+1
# df_train['target'] = |tch_solaire(t+1) - tch_solaire(t)|
df_train['target'] = df_train['tch_solaire'].shift(-1).sub(df_train['tch_solaire']).abs()
df_valid['target'] = df_valid['tch_solaire'].shift(-1).sub(df_valid['tch_solaire']).abs()
df_test['target'] = df_test['tch_solaire'].shift(-1).sub(df_test['tch_solaire']).abs()

In [15]:
def add_cyclic_time_features(df):
    """
    Ajoute des variables cycliques liées au temps :
    - heure de la journée : sin_hour, cos_hour
    - jour de l'année : sin_doy, cos_doy

    Le DataFrame doit avoir un index de type datetime.
    """

    # Copie pour éviter de modifier le DataFrame original
    df = df.copy()

    # Encodage cyclique de l'heure (heure + minutes)
    hour = df.index.hour + df.index.minute / 60
    df['sin_hour'] = np.sin(2 * np.pi * hour / 24)
    df['cos_hour'] = np.cos(2 * np.pi * hour / 24)

    # Encodage cyclique du jour de l'année
    # dayofyear commence à 1, donc on retire 1 pour démarrer à 0
    doy = df.index.dayofyear - 1

    # Nombre de jours selon que l'année est bissextile ou non
    nb_jour_annee = np.where(df.index.is_leap_year, 366, 365)

    df['sin_doy'] = np.sin(2 * np.pi * doy / nb_jour_annee)
    df['cos_doy'] = np.cos(2 * np.pi * doy / nb_jour_annee)

    return df

df_train = add_cyclic_time_features(df_train)
df_valid = add_cyclic_time_features(df_valid)
df_test  = add_cyclic_time_features(df_test)

display(df_train[['sin_hour', 'cos_hour', 'sin_doy', 'cos_doy']].head())

print("Taille de df_train :", df_train.shape)
print("Taille de df_valid :", df_valid.shape)
print("Taille de df_test  :", df_test.shape)

                           sin_hour  cos_hour   sin_doy   cos_doy
datetime_utc
2019-12-31 23:00:00+00:00 -0.258819  0.965926 -0.017213  0.999852
2019-12-31 23:30:00+00:00 -0.130526  0.991445 -0.017213  0.999852
2020-01-01 00:00:00+00:00  0.000000  1.000000  0.000000  1.000000
2020-01-01 00:30:00+00:00  0.130526  0.991445  0.000000  1.000000
2020-01-01 01:00:00+00:00  0.258819  0.965926  0.000000  1.000000

Taille de df_train : (52610, 84)
Taille de df_valid : (35088, 84)
Taille de df_test  : (19899, 84)

In [16]:
def create_meteo_features(df, vars_meteo, lags, windows, villes):
    new_cols = {}

    # Génération des variables dérivées pour chaque ville et chaque variable météo
    for ville in villes:
        for var in vars_meteo:
            serie = df[f"{ville}_{var}"]

            # Variation instantanée de la variable
            dserie = serie.diff()

            # Ajout de la différence première
            new_cols[f"{ville}_d{var}_dt"] = dserie

            # Création des variables retardées
            for lag in lags:
                new_cols[f"{ville}_{var}_lag_{lag}"] = serie.shift(lag)
                new_cols[f"{ville}_d{var}_lag_{lag}"] = dserie.shift(lag)

            # Calcul des statistiques glissantes
            for w in windows:
                new_cols[f"{ville}_{var}_roll_mean_{w}h"] = serie.rolling(w).mean()
                new_cols[f"{ville}_{var}_roll_std_{w}h"] = serie.rolling(w).std()

                new_cols[f"{ville}_d{var}_roll_mean_{w}h"] = dserie.rolling(w).mean()
                new_cols[f"{ville}_d{var}_roll_std_{w}h"] = dserie.rolling(w).std()

    df_new = pd.DataFrame(new_cols, index=df.index)
    return pd.concat([df, df_new], axis=1)

vars_meteo = ['ghi', 'bni', 'dhi', 'nebulosite']
lags = [1, 2, 3, 4, 6]
windows = [3, 4, 6]
villes = ['bra', 'cru', 'eyg', 'sel', 'svt']

print("Shape avant")
print(df_train.shape)
print(df_valid.shape)
print(df_test.shape)

df_train = create_meteo_features(df_train, vars_meteo, lags, windows, villes)
df_valid = create_meteo_features(df_valid, vars_meteo, lags, windows, villes)
df_test  = create_meteo_features(df_test, vars_meteo, lags, windows, villes)

print("Shape après")
print(f"Taille de df_train : {df_train.shape}")
print(f"Taille de df_valid : {df_valid.shape}")
print(f"Taille de df_test  : {df_test.shape}")

Shape avant
(52610, 84)
(35088, 84)
(19899, 84)
Shape après
Taille de df_train : (52610, 544)
Taille de df_valid : (35088, 544)
Taille de df_test  : (19899, 544)

In [17]:
def create_tch_features(df, lags, windows):
    new_cols = {}

    tch = df["tch_solaire"]
    dtch = tch.diff()
    abs_dtch = dtch.abs()

    # Variables retardées du TCH solaire et de ses variations
    for lag in lags:
        new_cols[f"tch_lag_{lag}"] = tch.shift(lag)
        new_cols[f"dtch_lag_{lag}"] = dtch.shift(lag)
        new_cols[f"abs_dtch_lag_{lag}"] = abs_dtch.shift(lag)

    # Statistiques glissantes
    for w in windows:
        new_cols[f"tch_roll_mean_{w}h"] = tch.rolling(w).mean()
        new_cols[f"tch_roll_std_{w}h"] = tch.rolling(w).std()

        new_cols[f"dtch_roll_mean_{w}h"] = dtch.rolling(w).mean()
        new_cols[f"dtch_roll_std_{w}h"] = dtch.rolling(w).std()

        new_cols[f"abs_dtch_roll_mean_{w}h"] = abs_dtch.rolling(w).mean()
        new_cols[f"abs_dtch_roll_std_{w}h"] = abs_dtch.rolling(w).std()

    df_new = pd.DataFrame(new_cols, index=df.index)
    return pd.concat([df, df_new], axis=1)

df_train = create_tch_features(df_train, lags, windows)
df_valid = create_tch_features(df_valid, lags, windows)
df_test  = create_tch_features(df_test, lags, windows)

print("Taille de df_train :", df_train.shape)
print("Taille de df_valid :", df_valid.shape)
print("Taille de df_test  :", df_test.shape)

Taille de df_train : (52610, 577)
Taille de df_valid : (35088, 577)
Taille de df_test  : (19899, 577)

In [18]:
df_train.info() # toutes les colonnes sont de type float64

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 52610 entries, 2019-12-31 23:00:00+00:00 to 2022-12-31 23:30:00+00:00
Columns: 577 entries, consommation to abs_dtch_roll_std_6h
dtypes: float64(577)
memory usage: 232.0 MB

In [19]:
# Réorganiser les colonnes, supprimer les valeurs manquantes introduites
df_train = df_train.reindex(columns=df_train.columns.sort_values()).dropna()
df_valid = df_valid.reindex(columns=df_valid.columns.sort_values()).dropna()
df_test = df_test.reindex(columns=df_test.columns.sort_values()).dropna()

# vérifier la taille
print("Taille de df_train :", df_train.shape)
print("Taille de df_valid :", df_valid.shape)
print("Taille de df_test  :", df_test.shape)

# aperçu des données
display(df_train.head(2))
display(df_valid.head(2))
display(df_test.head(2))

Taille de df_train : (52602, 577)
Taille de df_valid : (35080, 577)
Taille de df_test  : (19891, 577)

,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_lag_4,abs_dtch_lag_6,abs_dtch_roll_mean_3h,abs_dtch_roll_mean_4h,abs_dtch_roll_mean_6h,abs_dtch_roll_std_3h,abs_dtch_roll_std_4h,...,tch_lag_4,tch_lag_6,tch_roll_mean_3h,tch_roll_mean_4h,tch_roll_mean_6h,tch_roll_std_3h,tch_roll_std_4h,tch_roll_std_6h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 02:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 03:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_lag_4,abs_dtch_lag_6,abs_dtch_roll_mean_3h,abs_dtch_roll_mean_4h,abs_dtch_roll_mean_6h,abs_dtch_roll_std_3h,abs_dtch_roll_std_4h,...,tch_lag_4,tch_lag_6,tch_roll_mean_3h,tch_roll_mean_4h,tch_roll_mean_6h,tch_roll_std_3h,tch_roll_std_4h,tch_roll_std_6h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2023-01-01 03:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-01-01 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_lag_4,abs_dtch_lag_6,abs_dtch_roll_mean_3h,abs_dtch_roll_mean_4h,abs_dtch_roll_mean_6h,abs_dtch_roll_std_3h,abs_dtch_roll_std_4h,...,tch_lag_4,tch_lag_6,tch_roll_mean_3h,tch_roll_mean_4h,tch_roll_mean_6h,tch_roll_std_3h,tch_roll_std_4h,tch_roll_std_6h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 03:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
# On enregistre 3 datasets pour train / valid / test
df_train.to_csv(filepath_output + "train_5pts.csv")
df_valid.to_csv(filepath_output + "valid_5pts.csv")
df_test.to_csv(filepath_output + "test_5pts.csv")

In [21]:
# Check
print("Train :")
df_train = pd.read_csv(filepath_output + "train_5pts.csv", index_col='datetime_utc', parse_dates=True)
display(df_train.head())
print("Taille du dataset :", df_train.shape)

print("\nValid :")
df_valid = pd.read_csv(filepath_output + "valid_5pts.csv", index_col='datetime_utc', parse_dates=True)
display(df_valid.head())
print("Taille du dataset :", df_valid.shape)

print("\nTest :")
df_test = pd.read_csv(filepath_output + "test_5pts.csv", index_col='datetime_utc', parse_dates=True)
display(df_test.head())
print("Taille du dataset :", df_test.shape)

Train :

,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_lag_4,abs_dtch_lag_6,abs_dtch_roll_mean_3h,abs_dtch_roll_mean_4h,abs_dtch_roll_mean_6h,abs_dtch_roll_std_3h,abs_dtch_roll_std_4h,...,tch_lag_4,tch_lag_6,tch_roll_mean_3h,tch_roll_mean_4h,tch_roll_mean_6h,tch_roll_std_3h,tch_roll_std_4h,tch_roll_std_6h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 02:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 03:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 03:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01 04:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Taille du dataset : (52602, 577)

Valid :

,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_lag_4,abs_dtch_lag_6,abs_dtch_roll_mean_3h,abs_dtch_roll_mean_4h,abs_dtch_roll_mean_6h,abs_dtch_roll_std_3h,abs_dtch_roll_std_4h,...,tch_lag_4,tch_lag_6,tch_roll_mean_3h,tch_roll_mean_4h,tch_roll_mean_6h,tch_roll_std_3h,tch_roll_std_4h,tch_roll_std_6h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2023-01-01 03:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-01-01 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-01-01 04:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-01-01 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-01-01 05:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Taille du dataset : (35080, 577)

Test :

,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_lag_4,abs_dtch_lag_6,abs_dtch_roll_mean_3h,abs_dtch_roll_mean_4h,abs_dtch_roll_mean_6h,abs_dtch_roll_std_3h,abs_dtch_roll_std_4h,...,tch_lag_4,tch_lag_6,tch_roll_mean_3h,tch_roll_mean_4h,tch_roll_mean_6h,tch_roll_std_3h,tch_roll_std_4h,tch_roll_std_6h,tch_solaire,tco_solaire
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 03:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 04:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025-01-01 05:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Taille du dataset : (19891, 577)

In [22]:
# On va créé un second dataset avec moins de colonnes
# en utilisant des moyennes pondérées sur les colonnes concernant les 5 points d'intérêts retenus

# Récupération de la base des noms de colonnes concernés
col_par_ville = []
# Comme tous les points d'intérêts ont exactement les même colonnes les concernant
# On fait une recherche des noms concernant la ville de Bras
for col in df_train.columns :
    if col[:3] == "bra":
        col_par_ville.append(col[4:])
print(col_par_ville)
print("Nombre de colonnes concernant chaque point d'intérêt :", len(col_par_ville))

['altitude', 'azimuth', 'bhi', 'bni', 'bni_lag_1', 'bni_lag_2', 'bni_lag_3', 'bni_lag_4', 'bni_lag_6', 'bni_roll_mean_3h', 'bni_roll_mean_4h', 'bni_roll_mean_6h', 'bni_roll_std_3h', 'bni_roll_std_4h', 'bni_roll_std_6h', 'clear_sky_bhi', 'clear_sky_bni', 'clear_sky_dhi', 'clear_sky_ghi', 'dbni_dt', 'dbni_lag_1', 'dbni_lag_2', 'dbni_lag_3', 'dbni_lag_4', 'dbni_lag_6', 'dbni_roll_mean_3h', 'dbni_roll_mean_4h', 'dbni_roll_mean_6h', 'dbni_roll_std_3h', 'dbni_roll_std_4h', 'dbni_roll_std_6h', 'ddhi_dt', 'ddhi_lag_1', 'ddhi_lag_2', 'ddhi_lag_3', 'ddhi_lag_4', 'ddhi_lag_6', 'ddhi_roll_mean_3h', 'ddhi_roll_mean_4h', 'ddhi_roll_mean_6h', 'ddhi_roll_std_3h', 'ddhi_roll_std_4h', 'ddhi_roll_std_6h', 'dghi_dt', 'dghi_lag_1', 'dghi_lag_2', 'dghi_lag_3', 'dghi_lag_4', 'dghi_lag_6', 'dghi_roll_mean_3h', 'dghi_roll_mean_4h', 'dghi_roll_mean_6h', 'dghi_roll_std_3h', 'dghi_roll_std_4h', 'dghi_roll_std_6h', 'dhi', 'dhi_lag_1', 'dhi_lag_2', 'dhi_lag_3', 'dhi_lag_4', 'dhi_lag_6', 'dhi_roll_mean_3h', 'dhi_roll_mean_4h', 'dhi_roll_mean_6h', 'dhi_roll_std_3h', 'dhi_roll_std_4h', 'dhi_roll_std_6h', 'dnebulosite_dt', 'dnebulosite_lag_1', 'dnebulosite_lag_2', 'dnebulosite_lag_3', 'dnebulosite_lag_4', 'dnebulosite_lag_6', 'dnebulosite_roll_mean_3h', 'dnebulosite_roll_mean_4h', 'dnebulosite_roll_mean_6h', 'dnebulosite_roll_std_3h', 'dnebulosite_roll_std_4h', 'dnebulosite_roll_std_6h', 'ghi', 'ghi_lag_1', 'ghi_lag_2', 'ghi_lag_3', 'ghi_lag_4', 'ghi_lag_6', 'ghi_roll_mean_3h', 'ghi_roll_mean_4h', 'ghi_roll_mean_6h', 'ghi_roll_std_3h', 'ghi_roll_std_4h', 'ghi_roll_std_6h', 'humidite', 'nebulosite', 'nebulosite_lag_1', 'nebulosite_lag_2', 'nebulosite_lag_3', 'nebulosite_lag_4', 'nebulosite_lag_6', 'nebulosite_roll_mean_3h', 'nebulosite_roll_mean_4h', 'nebulosite_roll_mean_6h', 'nebulosite_roll_std_3h', 'nebulosite_roll_std_4h', 'nebulosite_roll_std_6h', 'temperature', 'toa', 'vitesse_vent']
Nombre de colonnes concernant chaque point d'intérêt : 107

In [23]:
# Chargement une seule fois du fichier des communes représentatives
df_communes = pd.read_csv(
    "/Projet_Moustafa_Datascience/aug25cds_variabilite/data/local_data/01_Clustering/output/best_communes_geo_energy.csv"
)

# Mise en minuscule des préfixes pour éviter les problèmes de correspondance
df_communes["prefix"] = df_communes["prefix"].str.lower()

# Série des poids indexée par préfixe de ville
poids_par_ville = df_communes.set_index("prefix")["poids"]
poids_par_ville

prefix
cru    0.22
sel    0.06
svt    0.07
bra    0.29
eyg    0.36
Name: poids, dtype: float64

In [24]:
def apply_region_weighting(df, col_par_ville, poids_par_ville):
    """
    Crée des colonnes régionales pondérées à partir des colonnes par ville,
    puis supprime les anciennes colonnes par ville.

    Paramètres
    ----------
    df : pd.DataFrame
        DataFrame d'entrée à transformer.
    col_par_ville : list
        Liste des variables à agréger, par exemple :
        ["ghi", "dni", "temp"]
    poids_par_ville : pd.Series
        Série contenant les poids, indexée par le préfixe de la ville.

    Retour
    ------
    pd.DataFrame
        Nouveau DataFrame transformé.
    """

    # Copie pour éviter de modifier le DataFrame original
    df = df.copy()

    # Dictionnaire qui contiendra les nouvelles colonnes régionales calculées
    region_cols = {}

    # Liste des colonnes par ville à supprimer après agrégation
    cols_to_drop = []

    # Liste des villes dans l'ordre des poids
    villes = poids_par_ville.index.tolist()

    # Tableau numpy des poids pour le calcul vectorisé
    weights = poids_par_ville.to_numpy()

    # Boucle sur chaque variable à agréger
    for col in col_par_ville:
        # Construction des noms de colonnes attendues pour cette variable
        # Exemple : marseille_ghi, nice_ghi, toulon_ghi, ...
        all_concerns_cols = [f"{ville}_{col}" for ville in villes]

        # Vérification que toutes les colonnes nécessaires existent bien
        missing_cols = [c for c in all_concerns_cols if c not in df.columns]
        if missing_cols:
            raise KeyError(f"Colonnes manquantes dans df pour '{col}' : {missing_cols}")

        # Calcul de la somme pondérée :
        # chaque colonne ville_variable est multipliée par son poids,
        # puis on somme ligne par ligne
        region_cols[f"region_{col}"] = (
            df[all_concerns_cols]
            .mul(weights, axis=1)
            .sum(axis=1)
        )

        # On mémorise les colonnes d'origine à supprimer ensuite
        cols_to_drop.extend(all_concerns_cols)

    # Ajout en une seule fois des nouvelles colonnes régionales
    df = pd.concat([df, pd.DataFrame(region_cols, index=df.index)], axis=1)

    # Suppression des anciennes colonnes par ville
    df = df.drop(columns=cols_to_drop)

    # Copie finale optionnelle pour défragmenter le DataFrame
    df = df.copy()

    return df

df_train = apply_region_weighting(df_train, col_par_ville, poids_par_ville)
df_valid = apply_region_weighting(df_valid, col_par_ville, poids_par_ville)
df_test  = apply_region_weighting(df_test,  col_par_ville, poids_par_ville)

print("Taille de df_train :", df_train.shape)
print("Taille de df_valid :", df_valid.shape)
print("Taille de df_test  :", df_test.shape)

Taille de df_train : (52602, 149)
Taille de df_valid : (35080, 149)
Taille de df_test  : (19891, 149)


# --- 1. Variations GHI ---
df["abs_dghi"] = df["region_dghi_dt"].abs()

# --- 2. Variabilité locale (robuste) ---
# df["ghi_mean_3h"] = df["region_ghi"].rolling(6).mean()
# df["ghi_std_3h"] = df["region_ghi"].rolling(6).std()
# df["ghi_cv"] = df["region_ghi_roll_std_6h"] / df["region_ghi_roll_mean_6h"].clip(lower=1e-6)
# forcer à 0 la nuit
# df.loc[df["region_ghi_roll_mean_6h"] < 1, "ghi_cv"] = 0

# --- 3. Clear Sky Index (CSI) ---
df["csi"] = df["region_ghi"] / df["region_clear_sky_ghi"].clip(lower=1e-6)
df.loc[df["region_clear_sky_ghi"] < 1, "csi"] = 0  # nuit

# --- 4. Régime de saturation (très important) ---
df["high_ghi"] = (df["region_ghi"] > 470).astype(int)


df["anomaly"] = (
    (df["csi"] > 0.8) &
    (df["tch_solaire"] < 0.2 * df["tch_solaire"].max())
).astype(int)
df.isna().sum().sum()

In [25]:
# On enregistre 3 datasets pour train / valid / test
df_train.to_csv(filepath_output + "train_region.csv")
df_valid.to_csv(filepath_output + "valid_region.csv")
df_test.to_csv(filepath_output + "test_region.csv")

In [26]:
# Check
print("Train :")
df_train = pd.read_csv(filepath_output + "train_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_train.head(-1))
print("Taille du dataset :", df_train.shape)

print("\nValid :")
df_valid = pd.read_csv(filepath_output + "valid_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_valid.head(-1))
print("Taille du dataset :", df_valid.shape)

print("\nTest :")
df_test = pd.read_csv(filepath_output + "test_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_test.head(-1))
print("Taille du dataset :", df_test.shape)

Train :

,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_lag_4,abs_dtch_lag_6,abs_dtch_roll_mean_3h,abs_dtch_roll_mean_4h,abs_dtch_roll_mean_6h,abs_dtch_roll_std_3h,abs_dtch_roll_std_4h,...,region_nebulosite_lag_6,region_nebulosite_roll_mean_3h,region_nebulosite_roll_mean_4h,region_nebulosite_roll_mean_6h,region_nebulosite_roll_std_3h,region_nebulosite_roll_std_4h,region_nebulosite_roll_std_6h,region_temperature,region_toa,region_vitesse_vent
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 02:30:00+00:00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,...,24.55650,11.388967,9.846325,13.311033,7.471846,6.889753,8.527640,3.51620,0.0,1.04585
2020-01-01 03:00:00+00:00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,...,25.24780,19.951900,16.583375,14.464167,12.214700,12.049887,10.497185,3.36130,0.0,0.96980
2020-01-01 03:30:00+00:00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,...,15.23310,28.112400,23.018600,17.295100,7.075640,11.712160,12.721136,3.26355,0.0,0.97035
2020-01-01 04:00:00+00:00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,...,5.21840,32.218700,29.152000,21.803833,0.374900,6.157056,12.357485,3.16580,0.0,0.97090
2020-01-01 04:30:00+00:00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,...,6.47780,32.356583,32.309087,26.154242,0.673197,0.609056,10.310398,3.22595,0.0,0.98650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-31 20:30:00+00:00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.008333,0.0,0.0,...,47.71525,42.088750,41.665112,41.261925,2.103944,3.078635,7.900394,10.25005,0.0,3.54810
2022-12-31 21:00:00+00:00,0.0,0.0,0.0,0.0,0.05,0.0,0.0,0.000000,0.0,0.0,...,40.47600,42.643450,42.317337,41.683108,2.680550,2.587997,5.088129,10.29750,0.0,3.55310
2022-12-31 21:30:00+00:00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,...,40.43510,42.081650,42.132187,41.710325,4.562144,4.282674,4.416027,10.30455,0.0,3.54590
2022-12-31 22:00:00+00:00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,...,40.39420,40.598400,41.109662,41.343575,7.712200,7.387159,6.780097,10.31160,0.0,3.53870
2022-12-31 22:30:00+00:00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.0,0.0,...,41.33900,37.814633,39.111750,40.229042,4.865679,7.109904,7.200324,10.27395,0.0,3.47140

Taille du dataset : (52602, 149)

Valid :

,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_lag_4,abs_dtch_lag_6,abs_dtch_roll_mean_3h,abs_dtch_roll_mean_4h,abs_dtch_roll_mean_6h,abs_dtch_roll_std_3h,abs_dtch_roll_std_4h,...,region_nebulosite_lag_6,region_nebulosite_roll_mean_3h,region_nebulosite_roll_mean_4h,region_nebulosite_roll_mean_6h,region_nebulosite_roll_std_3h,region_nebulosite_roll_std_4h,region_nebulosite_roll_std_6h,region_temperature,region_toa,region_vitesse_vent
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2023-01-01 03:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,30.08700,40.377883,40.676187,37.027042,3.409681,3.664739,7.655122,9.80140,0.0,2.91735
2023-01-01 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.78130,43.578050,42.610763,40.948392,5.731350,5.294490,6.296053,9.75450,0.0,2.85450
2023-01-01 04:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.67620,49.492300,46.580900,44.600600,6.093863,7.662007,7.179209,9.77035,0.0,2.81700
2023-01-01 05:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41.57110,55.589450,52.586600,47.983667,6.584250,8.089033,9.620251,9.78620,0.0,2.77950
2023-01-01 05:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,39.70890,60.365750,57.601663,51.971900,4.771575,6.975180,10.450315,9.71190,0.0,2.67510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 20:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,30.17005,46.702933,45.060350,41.857217,2.512590,4.203761,6.539235,4.18560,0.0,0.81120
2024-12-31 21:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.89040,47.631050,46.774150,44.040117,1.210750,2.211014,5.159294,4.10030,0.0,0.83530
2024-12-31 21:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,37.01150,48.421733,48.384875,46.312592,2.366462,2.399452,4.206227,4.05745,0.0,0.82800
2024-12-31 22:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40.13260,50.646350,49.892525,48.674642,3.702950,3.621784,4.006728,4.01460,0.0,0.82070
2024-12-31 22:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,44.20345,54.193733,52.392250,50.912392,3.637771,4.748888,4.711947,3.97415,0.0,0.79520

Taille du dataset : (35080, 149)

Test :

,abs_dtch_lag_1,abs_dtch_lag_2,abs_dtch_lag_3,abs_dtch_lag_4,abs_dtch_lag_6,abs_dtch_roll_mean_3h,abs_dtch_roll_mean_4h,abs_dtch_roll_mean_6h,abs_dtch_roll_std_3h,abs_dtch_roll_std_4h,...,region_nebulosite_lag_6,region_nebulosite_roll_mean_3h,region_nebulosite_roll_mean_4h,region_nebulosite_roll_mean_6h,region_nebulosite_roll_std_3h,region_nebulosite_roll_std_4h,region_nebulosite_roll_std_6h,region_temperature,region_toa,region_vitesse_vent
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 03:30:00+00:00,0.00,0.00,0.00,0.00,0.00,0.000000,0.0000,0.000000,0.000000,0.000000,...,67.91415,67.224250,68.103312,68.228050,3.503629,3.762546,4.233233,3.48685,0.000000,0.82015
2025-01-01 04:00:00+00:00,0.00,0.00,0.00,0.00,0.00,0.000000,0.0000,0.000000,0.000000,0.000000,...,67.72320,63.628250,65.119937,66.742017,4.992250,5.227523,5.673591,3.44950,0.000000,0.82530
2025-01-01 04:30:00+00:00,0.00,0.00,0.00,0.00,0.00,0.000000,0.0000,0.000000,0.000000,0.000000,...,69.23185,59.557783,61.780712,64.576392,4.201552,5.807861,6.642001,3.40500,0.000000,0.83875
2025-01-01 05:00:00+00:00,0.00,0.00,0.00,0.00,0.00,0.000000,0.0000,0.000000,0.000000,0.000000,...,70.74050,56.238100,58.085637,61.731175,3.641100,4.978808,7.255475,3.36050,0.000000,0.85220
2025-01-01 05:30:00+00:00,0.00,0.00,0.00,0.00,0.00,0.000000,0.0000,0.000000,0.000000,0.000000,...,69.59500,52.556317,54.118988,58.092283,4.956013,5.757526,8.213382,3.29580,0.000000,0.86105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-02-19 10:00:00+00:00,2.13,1.28,3.55,5.96,0.92,1.810000,2.2450,3.396667,0.462277,0.948349,...,43.62250,43.622500,43.622500,43.622500,0.000000,0.000000,0.000000,8.43170,342.485638,1.56160
2026-02-19 10:30:00+00:00,2.02,2.13,1.28,3.55,5.44,3.026667,2.5900,3.311667,1.649252,1.605013,...,43.62250,43.622500,43.622500,43.622500,0.000000,0.000000,0.000000,8.43170,368.848609,1.56160
2026-02-19 11:00:00+00:00,4.93,2.02,2.13,1.28,5.96,2.366667,2.3075,2.343333,2.408783,1.970319,...,43.62250,43.622500,43.622500,43.622500,0.000000,0.000000,0.000000,8.43170,387.297370,1.56160
2026-02-19 11:30:00+00:00,0.15,4.93,2.02,2.13,3.55,3.433333,3.0800,2.621667,2.847145,2.429719,...,43.62250,43.622500,43.622500,43.622500,0.000000,0.000000,0.000000,8.43170,397.516794,1.56160
2026-02-19 12:00:00+00:00,5.22,0.15,4.93,2.02,1.28,1.990000,2.7250,2.508333,2.806296,2.722334,...,43.62250,43.622500,43.622500,43.622500,0.000000,0.000000,0.000000,8.43170,399.332757,1.56160

Taille du dataset : (19891, 149)

In [27]:
sorted(df_train.columns.to_list())

['abs_dtch_lag_1',
 'abs_dtch_lag_2',
 'abs_dtch_lag_3',
 'abs_dtch_lag_4',
 'abs_dtch_lag_6',
 'abs_dtch_roll_mean_3h',
 'abs_dtch_roll_mean_4h',
 'abs_dtch_roll_mean_6h',
 'abs_dtch_roll_std_3h',
 'abs_dtch_roll_std_4h',
 'abs_dtch_roll_std_6h',
 'consommation',
 'cos_doy',
 'cos_hour',
 'dtch_lag_1',
 'dtch_lag_2',
 'dtch_lag_3',
 'dtch_lag_4',
 'dtch_lag_6',
 'dtch_roll_mean_3h',
 'dtch_roll_mean_4h',
 'dtch_roll_mean_6h',
 'dtch_roll_std_3h',
 'dtch_roll_std_4h',
 'dtch_roll_std_6h',
 'region_altitude',
 'region_azimuth',
 'region_bhi',
 'region_bni',
 'region_bni_lag_1',
 'region_bni_lag_2',
 'region_bni_lag_3',
 'region_bni_lag_4',
 'region_bni_lag_6',
 'region_bni_roll_mean_3h',
 'region_bni_roll_mean_4h',
 'region_bni_roll_mean_6h',
 'region_bni_roll_std_3h',
 'region_bni_roll_std_4h',
 'region_bni_roll_std_6h',
 'region_clear_sky_bhi',
 'region_clear_sky_bni',
 'region_clear_sky_dhi',
 'region_clear_sky_ghi',
 'region_dbni_dt',
 'region_dbni_lag_1',
 'region_dbni_lag_2',
 'region_dbni_lag_3',
 'region_dbni_lag_4',
 'region_dbni_lag_6',
 'region_dbni_roll_mean_3h',
 'region_dbni_roll_mean_4h',
 'region_dbni_roll_mean_6h',
 'region_dbni_roll_std_3h',
 'region_dbni_roll_std_4h',
 'region_dbni_roll_std_6h',
 'region_ddhi_dt',
 'region_ddhi_lag_1',
 'region_ddhi_lag_2',
 'region_ddhi_lag_3',
 'region_ddhi_lag_4',
 'region_ddhi_lag_6',
 'region_ddhi_roll_mean_3h',
 'region_ddhi_roll_mean_4h',
 'region_ddhi_roll_mean_6h',
 'region_ddhi_roll_std_3h',
 'region_ddhi_roll_std_4h',
 'region_ddhi_roll_std_6h',
 'region_dghi_dt',
 'region_dghi_lag_1',
 'region_dghi_lag_2',
 'region_dghi_lag_3',
 'region_dghi_lag_4',
 'region_dghi_lag_6',
 'region_dghi_roll_mean_3h',
 'region_dghi_roll_mean_4h',
 'region_dghi_roll_mean_6h',
 'region_dghi_roll_std_3h',
 'region_dghi_roll_std_4h',
 'region_dghi_roll_std_6h',
 'region_dhi',
 'region_dhi_lag_1',
 'region_dhi_lag_2',
 'region_dhi_lag_3',
 'region_dhi_lag_4',
 'region_dhi_lag_6',
 'region_dhi_roll_mean_3h',
 'region_dhi_roll_mean_4h',
 'region_dhi_roll_mean_6h',
 'region_dhi_roll_std_3h',
 'region_dhi_roll_std_4h',
 'region_dhi_roll_std_6h',
 'region_dnebulosite_dt',
 'region_dnebulosite_lag_1',
 'region_dnebulosite_lag_2',
 'region_dnebulosite_lag_3',
 'region_dnebulosite_lag_4',
 'region_dnebulosite_lag_6',
 'region_dnebulosite_roll_mean_3h',
 'region_dnebulosite_roll_mean_4h',
 'region_dnebulosite_roll_mean_6h',
 'region_dnebulosite_roll_std_3h',
 'region_dnebulosite_roll_std_4h',
 'region_dnebulosite_roll_std_6h',
 'region_ghi',
 'region_ghi_lag_1',
 'region_ghi_lag_2',
 'region_ghi_lag_3',
 'region_ghi_lag_4',
 'region_ghi_lag_6',
 'region_ghi_roll_mean_3h',
 'region_ghi_roll_mean_4h',
 'region_ghi_roll_mean_6h',
 'region_ghi_roll_std_3h',
 'region_ghi_roll_std_4h',
 'region_ghi_roll_std_6h',
 'region_humidite',
 'region_nebulosite',
 'region_nebulosite_lag_1',
 'region_nebulosite_lag_2',
 'region_nebulosite_lag_3',
 'region_nebulosite_lag_4',
 'region_nebulosite_lag_6',
 'region_nebulosite_roll_mean_3h',
 'region_nebulosite_roll_mean_4h',
 'region_nebulosite_roll_mean_6h',
 'region_nebulosite_roll_std_3h',
 'region_nebulosite_roll_std_4h',
 'region_nebulosite_roll_std_6h',
 'region_temperature',
 'region_toa',
 'region_vitesse_vent',
 'sin_doy',
 'sin_hour',
 'solaire',
 'target',
 'tch_lag_1',
 'tch_lag_2',
 'tch_lag_3',
 'tch_lag_4',
 'tch_lag_6',
 'tch_roll_mean_3h',
 'tch_roll_mean_4h',
 'tch_roll_mean_6h',
 'tch_roll_std_3h',
 'tch_roll_std_4h',
 'tch_roll_std_6h',
 'tch_solaire',
 'tco_solaire']